### ISSUE TITLE
iOS in-progress branch?

### ISSUE THREAD

**Issue by aleclarson** [kmagiera/react-native-gesture-handler#1]
I'd be interested in an `ios` branch, even if it's still in-progress. 😄

**Comment by kmagiera** [comment]
@aleclarson haven't started working on iOS just yet. Still exploring the API and making many changes there, so until it stabilises I think it doesn't make any sense to start with iOS (I think I'd need 2-3 more weeks for that)

**Comment by kmagiera** [comment]
Will just close this as iOS support has landed few weeks ago.
