### ISSUE TITLE
Is it possible to add a gesture on top of a WebView.

### ISSUE THREAD

**Issue by douglaslondrina** [kmagiera/react-native-gesture-handler#103]
I'm trying to get pan gestures made over the webview, mainly to hide/show a custom navigation bar.
I've tried some variations of the examples but couldn't get the gestures events to be called if the gesture came from the top of the webview. 

Is it even possible?

I see that we can use the WebView import from the library to assure the Webview will get the touches needed for it to work, but is it possible to first read the gesture than pass it to the webview?

**Comment by douglaslondrina** [comment]
react-native PanResponder api works if set in a view on top of the webview, and the webview works normally. It probably is a better solution for my case.

**Comment by haveamission** [comment]
@douglaslondrina Do you have an example of how this would look?

**Comment by goleary** [comment]
@douglaslondrina I'm trying to achieve something similar.

Do you have any recollection of how you got this to work?

I want to capture tap events/gestures made on the webview, but not prevent stuff like scrolling from taking place in the webview.

**Comment by Darren120** [comment]
@haveamission 
@goleary 

FUCK @oidoug U GATE KEEPING SHIT FACE.

here's the code

`    const panResponder = useRef(
      PanResponder.create({
        onStartShouldSetPanResponder: (evt, gestureState) => false,
        onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
        onMoveShouldSetPanResponder: (evt, gestureState) => true,
        onMoveShouldSetPanResponderCapture: (evt, gestureState) => false,
        onPanResponderTerminationRequest: (evt, gestureState) => false,
        onShouldBlockNativeResponder: (evt, gestureState) => false,
        onPanResponderMove: (e) =>
          console.log("hello2", e.nativeEvent?.locationY),
        onPanResponderRelease: () => {},
      })
    ).current;`

then

        {...panResponder.panHandlers}

on any <View         {...panResponder.panHandlers}/>

enjoy.
spent my weekend on this

**Comment by haveamission** [comment]
@oidoug React Native github getting spicy today apparently
