### ISSUE TITLE
Android: Unsupported top level event type

### ISSUE THREAD

**Issue by davidbiller** [kmagiera/react-native-gesture-handler#106]
Unsupported top level event type "topGestureHandlerStateChange" dispatched
extractEvents
```
    ReactNativeFiber-dev.js:3519:22
extractEvents
    ReactNativeFiber-dev.js:3298:71
handleTopLevel
    ReactNativeFiber-dev.js:3539:64
<unknown>
    ReactNativeFiber-dev.js:3560:55
batchedUpdates
    ReactNativeFiber-dev.js:2754:26
batchedUpdates
    ReactNativeFiber-dev.js:202:35
batchedUpdatesWithControlledComponents
    ReactNativeFiber-dev.js:209:34
_receiveRootNodeIDEvent
    ReactNativeFiber-dev.js:3559:50
receiveEvent
    ReactNativeFiber-dev.js:3564:60
__callFunction
    MessageQueue.js:299:47
<unknown>
    MessageQueue.js:111:26
__guard
    MessageQueue.js:262:6
callFunctionReturnFlushedQueue
    MessageQueue.js:110:17
```

In a Flatlist. just when i click everywhere.

"expo": "^24.0.0" with .29 Beta. Sorry for that

**Comment by Un3qual** [comment]
How did you fix this?

**Comment by JulianKingman** [comment]
@davidbiller if you solved this, please share, otherwise keep open

**Comment by JulianKingman** [comment]
I got this error after updating to 1.0.5, downgrading to 1.0.4 fixed the problem.
The issue appears to be this commit: https://github.com/kmagiera/react-native-gesture-handler/commit/10f239de4b315c34e145f6edf32a3e34b97bc65f

**Comment by qaiser110** [comment]
Thanks @JulianKingman  This helped me fix my issue. I was using Expo which already has react-native-gesture-handler bundled, but I installed it locally and was facing this issue. 

Looking at your comment, I removed my local installation, and i started working.

**Comment by elzii** [comment]
Same issue on 

```
  "react-native": "^0.57.3",
  "react-native-gesture-handler": "^1.0.8",
```

**Comment by balthazar** [comment]
Same issue for both `1.0.9` and `1.0.10`, I can't downgrade to `1.0.4` due to an incompatibility with another dependency.

**Comment by olegwn** [comment]
same issue on iOS

```
    "react-native": "^0.57.8",
    "react-native-gesture-handler": "^1.1.0",
```

**Comment by linjson** [comment]
same issue on android when release
```
    "reactxp":'2.0.0-rc.1'
    "react-native": "^0.61.1",
    "react-native-gesture-handler": "^1.4.1",

```
