### ISSUE TITLE
Not seeing RNGestureHandlerModule

### ISSUE THREAD

**Issue by allison7** [kmagiera/react-native-gesture-handler#107]
Are there any extra pieces I need on the native side to access that NativeModule?

![simulator screen shot - iphone 8 - 2018-01-18 at 09 40 53](https://user-images.githubusercontent.com/31011021/35103459-dfa14354-fc33-11e7-8d0a-12a993a90551.png)

**Comment by kmagiera** [comment]
It appears you might have skipped installation step where you run `react-native link react-native-gesture-handler` or this step could fail and the library ended up not linking properly with your native code.

**Comment by allison7** [comment]
Not skipped, but the app has a strange architecture and so linking failed in a way that wasn't obvious

Closing
