### ISSUE TITLE
Feature Request: Set Bounds on PanGestureHandler

### ISSUE THREAD

**Issue by zachgibson** [kmagiera/react-native-gesture-handler#110]
I ran into an Issue building a Slider where clamping the Animated Value resulted in the Slider handle not moving immediately when you’re at the beginning or end of the Slider. But, the width of the Slider handle has to be accounted for in the interpolation so it won’t slide past the end.

Notice the Slider handle when it’s in the middle versus the ends:

![rngesture_repro](https://user-images.githubusercontent.com/10658888/35158276-3c8b15ae-fcfc-11e7-8019-1afe99dfcaee.gif)

The code:
```JSX
this._onGestureEvent = Animated.event(
  [
    {
      nativeEvent: {
        translationX: this._translateX,
      },
    },
  ],
  {
    useNativeDriver: true,
  },
);
```
```JSX
translateX: this._translateX.interpolate({
  inputRange: [0, SLIDER_WIDTH - SLIDER_HAHNDLE_WIDTH],
  outputRange: [0, SLIDER_WIDTH - SLIDER_HAHNDLE_WIDTH],
  extrapolate: 'clamp',
})
```

If I don’t use interpolate the Slider works perfectly except it will drag past the ends. What if there was a configuration prop to specify beginning and ending values where the gesture will cancel once it hits them?

**Comment by kmagiera** [comment]
Hey @zachgibson ! Awesome to see the progress you're making on your slider thing. Also very much appreciate that you're taking your time and preparing such a detailed issue description (with videos and all that stuff). It saves me a lot of time understanding and coming up with the solution.

Before I answer I'd like to know a few more details:
 1) is you handler attached to the thumb (white circle) or the whole slider (blue rectangle)?
 2) since you are using translateX you need to somehow stash the last thumb position – how do you handle that?
 3) Have you considered using `nativeEvent.absoluteX` or `nativeEvent.x` instead of `nativeEvent.translateX` for your slider?

**Comment by zachgibson** [comment]
For sure! I knew that GIF would be a lot harder to explain than just show. Also the Slider would not be so cool without this native gesture handler. So yeah, I’m still super pumped about this project!

1. Handler is attached to the white circle—Slider Handle is what I’m calling it
2. I’m not doing this, but I do have a feeling my Animated Value just gets off maybe?
3. I can’t remember if I have, but I’ll give it a try and report back

I did notice it works if I’ve already started dragging the handle from anywhere besides the two ends. Notice when I go all the way to the beginning then start dragging back it immediately moves:

![rngesture_repro2](https://user-images.githubusercontent.com/10658888/35185443-31c8802e-fdca-11e7-84b2-90f8c0df92f4.gif)

**Comment by zachgibson** [comment]
I’ll try your suggestions and see if one of them solves my issue and report back here. Thanks for the help!

**Comment by AbdallaMohamed** [comment]
@zachgibson did you find a solution yet? I'd love to learn from your findings.

**Comment by zachgibson** [comment]
@AbdallaMohamed Yeah I think I just found the issue.

@kmagiera Setting the offset on state change plus using `shouldCancelWhenOutside={false}` seems to be my problem. When I drag past the beginning or end, `translationX` keeps getting set. I’m trying to figure out setting the right values at the right time, but haven’t figured it out yet.
```JSX
_onHandlerStateChange = event => {
  if (event.nativeEvent.oldState === GestureHandler.State.ACTIVE) {
    this._lastOffsetX += event.nativeEvent.translationX;
    this._translateX.setOffset(this._lastOffsetX);
    this._translateX.setValue(0);
  }

  if (event.nativeEvent.state === GestureHandler.State.END) {
    this._animateSliderHandleDown();
    this._setValueCallback();
  }
};
```

**Comment by zachgibson** [comment]
Figured it out! If `absoluteX` goes past the start or end of the Slider, I manually set offset to either 0 for the beginning or `MAX_OUTPUT_RANGE` for the end so `_translateX` will stop decrementing or incrementing and causing the delay once you try to drag again. These values—`32` and `width - 32`—are hardcoded for my testing purposes but they equate to the left and right offset of the Slider since usually your slider will have left and right “margin”.
```JSX
_onHandlerStateChange = event => {
  if (event.nativeEvent.oldState === GestureHandler.State.ACTIVE) {
    if (event.nativeEvent.absoluteX <= 32) {
      this._lastOffsetX = 0;
    } else if (event.nativeEvent.absoluteX >= width - 32) {
      this._lastOffsetX = MAX_OUTPUT_RANGE;
    } else {
      this._lastOffsetX += event.nativeEvent.translationX;
    }

    this._translateX.setOffset(this._lastOffsetX);
    this._translateX.setValue(0);
  }

  if (event.nativeEvent.state === GestureHandler.State.END) {
    this._animateSliderHandleDown();
    this._setValueCallback();
  }
};
```
![2018-02-20 15_15_11](https://user-images.githubusercontent.com/10658888/36450035-4f9b54f0-1652-11e8-8fa0-5eb0225a30bf.gif)

**Comment by zachgibson** [comment]
Just to clarify this issue: using Animated’s interpolate with `extrapolate: 'clamp'` set output bounds for my Slider. My issue was logic concerning setting the offset of the Slider Handle once you dragged past the beginning or end of the Slider bounds and let go since `translationX` value will keep decrementing or incrementing as you “over-drag”. Once you over-drag you need to account for this and offset the Animated Value to either the start or end value which will work perfectly and not result in my issue above where your dragging the Handle but it is delayed in moving.

I tried using `absoluteX` instead but it resulted in the slider not always following my finger. e.g. It would speed up and go past my finger once you got closer to the beginning or end, which isn’t ideal.

@kmagiera Chime in here if you see anything I’ve said isn’t accurate. I did use your code for a lot of this dragging functionality. 😉
