### ISSUE TITLE
How it's possible to catch onDrawerOpen?

### ISSUE THREAD

**Issue by greenzeal** [kmagiera/react-native-gesture-handler#112]
Hi!

I have drawer which you can swipe on every screen. But on some screens I have Modal DropDowns which if you leave dropdown open and then swipe to open drawer then drawer is under dropdown. 

So how it's possible to catch onDrawerOpen where I can just close all dropdowns.

Thanks!

**Comment by henrikra** [comment]
You mean this? https://github.com/kmagiera/react-native-gesture-handler/blob/master/DrawerLayout.js#L35

**Comment by osdnk** [comment]
This issue seems to be solved. 
@greenzeal 
If you still face the problem, reopen the issue
