### ISSUE TITLE
animation responding to gesture

### ISSUE THREAD

**Issue by erfanyousefifar** [kmagiera/react-native-gesture-handler#113]
Hi, first thanks for your great library. 
i don't understand something, and that is does the library and animated native driver work together? 
for example, a card like google now card, that when you swipe it to left or right, the opacity changes correspondingly, Can I do things like this with this library?

**Comment by AbdallaMohamed** [comment]
You can look at the examples and learn more about it. But in a nutshell, your PanGestureHandler should be controlling an Animated Value, and then you change the transform styles of an Animated View by interpolation. You also handle the change in gesture state to determine the final value of the Animated Value.

**Comment by kmagiera** [comment]
Hey @erfanyousefifar ! Sorry for late response. Also thanks to @AbdallaMohamed for answering. I will just repeat what @AbdallaMohamed said and direct you to the examples. You may also want to try the example app on Expo (although I don't have a link at hand). Just play with changing styles of Animated.Views in some examples and you should get a sense of what can be done (the things you've described should def work ok)
