### ISSUE TITLE
"Fat" longPresses not working on Android

### ISSUE THREAD

**Issue by scottmas** [kmagiera/react-native-gesture-handler#117]
This began failing after upgrading to the latest version of Expo. But when I make my thumb super fat, Android has a very hard time picking up on longPresses. It only works reliably with very small touch areas.

It's almost as if it's not registering ANY long press event when any part of my finger is outside the touchable area, even when the center of my finger is within the touchable area. 

I think there's also a related issue which may be making the bug more pronounced in my case. The `LongPressGestureHandler` has a nested `PanGestureHandler` with a minDist of 15, and I think when even a 1 pixel drag event occurs, the LongPress handler is aborted.

**Comment by kmagiera** [comment]
This sounds like the problem could be that we only use hitSlop for collecting handlers that can respond to the gesture, then we are no longer using it when there are subsequent touch events happening on the surface of the button. The behavior of LongPress has recently changed and as I'm not able to try it out right now I suggest you try one of the following:
a) set `shouldCancelWhenOutside={false}` for your longpresshandler
b) try setting `maxDist` to something big (e.g. 5000) for longpresshandler

**Comment by scottmas** [comment]
Let me test this out when I get home! I'll let you know.

**Comment by scottmas** [comment]
This fixed it! Thank you. Should I close this story?

**Comment by kmagiera** [comment]
Thanks for confirming that, will just close it now. Feel free to reopen if there is anything you'd like to discuss further
