### ISSUE TITLE
Gesture handler conflicted with other modules such as react-navigation

### ISSUE THREAD

**Issue by tikkichan4** [kmagiera/react-native-gesture-handler#118]
In react-navigation, it provides a swipe to left gesture. 
Also, i am using PanGestureHandler / DrawerLayout which provided by react-native-gesture-handler to make a right side menu (Because it is customizable rather than the drawer provided in react-navigation)

For my use case, i am turning the responding distance to full width for easier triggering in both component. 

There is a conflict that when i opened the drawer and try to swipe to close the drawer, the swipe to left gesture from react-navigation will be triggered at the same time (Actually i don't want to trigger the gesture from react-navigation).

Any workaround to solve this ? I tried to use redux to map the state in react-navigation, so the swipe to left gesture will not be trigger when the drawer is being opened. It works but it causes the drawer animation laggy.

**Comment by kmagiera** [comment]
Hey @tikkichan4 thanks for reaching out!
What is that react-navigation use left swipe for?

**Comment by tikkichan4** [comment]
@kmagiera it is used for pop the current scene and go back to the previous scene.
The gesture is usually enabled for

**Comment by tikkichan4** [comment]
Sorry for pressing the wrong button to close the issue.

@kmagiera it is used for pop the current scene and go back to the previous scene.
The gesture is usually enabled for IOS user in my app since they don't have other convenient way to go back (Android user can press hardware back button). So it is a must to solving this issue in my app. Hope the information helps. Thanks a lot !

**Comment by martsie** [comment]
Having the same issue unfortunately - even when PanGestureHandler is disabled native gesture handlers that are in child views are blocked

**Comment by pyankoff** [comment]
What's the best way to disable left-right swipe direction in Swipable? Having conflict with react-navigation swipe to go back gesture too.

**Comment by Nyadesune** [comment]
anyone got a workaround for this?

**Comment by filiptdz** [comment]
I don't know how much customisation you need, but you can customize the react-navigation drawer with the `contentComponent` prop, as such:
`
const DrawerNavigation = createDrawerNavigator(
  {
    /* navigators setup */
  },
  {
    contentComponent: Drawer,
  },
);
`

**Comment by MelonDeng** [comment]
I just added `hitSlop={{ left: -30 }}` property to the PanGestureHandler,  works fine for me

**Comment by brentvatne** [comment]
going to close this, if someone wants to share a reproducible example in a new issue that'd be excellent.

**Comment by elan** [comment]
Ran into this issue while dealing with RNGH conflicting with iOS back gesture, I was able to solve with `hitSlop={{left: -10}}` on the gesture handler itself.
