### ISSUE TITLE
 package com.swmansion.gesturehandler.react does not exist

### ISSUE THREAD

**Issue by DungBuiDeveloper** [kmagiera/react-native-gesture-handler#124]
i follow settup and always recived this issue . who can solve for me please.

**Comment by adirzoari** [comment]
same issue, did you find solution?

**Comment by DungBuiDeveloper** [comment]
i'm still wait for someone can solve , boring now

**Comment by kmagiera** [comment]
@DungBuiDeveloper, @adirzoari did the suggestion by @fera2k help you? I believe this is related to your setup and most likely the library is not properly linked.

Feel free to reopen this issue if the problem persists. Also next time would be much easier if you provide a more comprehensive description of the issue like the full error message, command you run to get the error, if it happens at the build step or runtime etc

**Comment by trimitrtechnologies** [comment]
People still struggling with it can try below command 

`react-native link react-native-gesture-handler`
and then 

`react-native run-android`

did work with me.!

**Comment by KalanaPerera** [comment]
To install react native cli

`npm install -g react-native-cli`

Happy coding

**Comment by AliYar-Khan** [comment]
> 
> 
> edit the file **android/app/build.gradle** and under the **dependencies** block, add this line:
> ` implementation project(':react-native-gesture-handler')`

this works for me ! thanks sir !

**Comment by claytongroth** [comment]
`implementation project(**path:** ':react-native-gesture-handler')`
Typed it wrong.

**Comment by SamiChab** [comment]
It happened to me as I commented following line in `app/build.gradle` and `settings.gradle`:
`apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)`

**Comment by musthafa-pa** [comment]
I have tried adding implementation project(':react-native-gesture-handler') inside app/build.gradle. But nothing seems to work for me. Also, I have followed everything closely according to your documentation.

**Comment by jakub-gonet** [comment]
@musthafa-pa, could you post more info about your RN and Gradle versions, if you installed RNGH for the first time or you're upgrading and if you cleared Gradle (and other) caches?

**Comment by jhoncar7** [comment]
Hola, tuvo el mismo inconveniente justo hace un día, y no encontré la solución.

intente volviendo a instalar la dependencia 'yarn add react-native-gesture-handler' y me funciono perfecto.

lo dejo por si le sirve a alguien mas.

saludos.

**Comment by Ha0ran2001** [comment]
> 

I got error: unknown command 'link'

**Comment by Ha0ran2001** [comment]
> People still struggling with it can try below command
> 
> `react-native link react-native-gesture-handler` and then
> 
> `react-native run-android`
> 
> did work with me.!

I got error: unknown command 'link'

**Comment by tchejanovich** [comment]
Hi, I'm still having this issue. 
```
 "react-native": "0.70.0",
"react-native-gesture-handler": "2.10.0",
```
None of the solutions above works for me.
