### ISSUE TITLE
Event when boundaries are reached with PanGestureHandler

### ISSUE THREAD

**Issue by brighthero** [kmagiera/react-native-gesture-handler#127]
What the best way to fire an event when a pan gesture has reached some specific transform value?

Specifically, I want to be able to drag a button to the right 50px and not any further. When the 50px is reached some predefined animation is to be played.
What's the most efficient way to achieve this?

**Comment by kmagiera** [comment]
Currently your best bet is to do this using Animated library. You will need to add an Animated value listener and monitor translate updates, then start animation at certain point and cancel PanGestureHandler (the easiest way to cancel handler is by setting enabled={false}). You may also want to use Animated.interpolate with `extrapolate: "clamp"` option for your translate value to make sure it doesn't go beyond 50px.
