### ISSUE TITLE
FlatList nested in GestureHandler make error

### ISSUE THREAD

**Issue by tsaohucn** [kmagiera/react-native-gesture-handler#129]
```
import React, { Component } from 'react';
import { Animated, Dimensions, StyleSheet, Text, View, Image } from 'react-native';
import {
  PanGestureHandler,
  TapGestureHandler,
  PinchGestureHandler,
  ScrollView,
  State,
  FlatList
} from 'react-native-gesture-handler';


  render() {
    return (
      <TapGestureHandler
        onHandlerStateChange={this._onSingleTap}
        waitFor={["double_tap","flatlist_pinch"]}
      >
        <TapGestureHandler
          id="double_tap"
          waitFor="flatlist_pinch"
          onHandlerStateChange={this._onDoubleTap}
          numberOfTaps={2}
        >
          <PinchGestureHandler
            id="flatlist_pinch"
            onHandlerStateChange={this._onPinchHandlerStateChange}
            onGestureEvent={this.xxx}
          >
            <FlatList
              data={content}
              renderItem={({ item }) =>
                <Image
                  resizeMode={'contain'} 
                  style={{width, height: item.height, backgroundColor: 'black'}}
                  source={{uri: item.key}}
                  />
                }
            />
          </PinchGestureHandler>
        </TapGestureHandler>
      </TapGestureHandler>
    )
  }
```

Here is my code, I saw example of this project, all scrollView component is in the outermost, I have tried it, the example code work correctly, but when I put the Flatlist nasted in the innermost, then show the error message.
By the way, if I use the original FlatList Component from react-native lib, then it work OK.

![screenshot_20180310-000411](https://user-images.githubusercontent.com/6713879/37219811-235ab2ac-23f7-11e8-8e0d-3101b80537be.png)

**Comment by osdnk** [comment]
Thank you for testing this library!
I took a look on this issue and tried to paste. However, as you surely know, your code is not working. Truly I don't know what was your intention but I managed to provide some workable app basing on your version. If you wish, take a look and paste it into `App.js` in our `Example`
https://gist.github.com/osdnk/8869d4ae2db642a366b075d537c6ec55

**Comment by osdnk** [comment]
Did it fix your issue? 
If not, please reopen this issue

**Comment by yeshengwu** [comment]
the same issue. FlatList cause problem.

**Comment by EvanKoe** [comment]
Same issue !
