### ISSUE TITLE
Support for native PanGestureHandler

### ISSUE THREAD

**Issue by DragonRaider5** [kmagiera/react-native-gesture-handler#13]
Hey,
first off: a big thanks to you for this awesome project.

I've got a question though: for when is native PanGestureHandler support planned? This would really help me out a lot, as there currently is no other way of smooth panning animations despite writing your own native components.

Thanks in advance!

DragonRaider5

**Comment by kmagiera** [comment]
Hey! Thanks for your interest in the project!

PanGestureHandler is one of the first components I've added to the project and is fully functional in the current version. You can check an example code here: https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/draggable/index.js

**Comment by DragonRaider5** [comment]
Hi,
Pleased to hear so. Maybe I'm missing something, but passing something to onGestureEvent doesn't Do anything for me and when passing onGestureHandlerEvent with `use_native_driver: true` I get an error regarding the native driver :/
