### ISSUE TITLE
Is there any callback or way to reset  value of event.nativeEvent.scale when only one finger leave screen ?

### ISSUE THREAD

**Issue by tsaohucn** [kmagiera/react-native-gesture-handler#130]
The PinchGestureHandler now only call onEnded when all two fingers leave screen, it cause a issue about big shake(by translation or scale) when I first leave one finger off screen then put all fingers back again, the reason cause the behavior over-here is event.nativeEvent.scale always be calculated by the origin distance when fingers first touch even though I have left one finger off, when we put all fingers back again, it cause a big gap like 1.2 -> 1.5(scale), I find a solution is setting props enabled=false when one finger leave off, then enabled=true when all fingers back, but I think it's a dirty trick, the other way it I divide scale of moment of I putting all fingers back, but it also not very well, the best way I think is that we have to think leaving of one finger Is stand for end of PinchGestureHandler because of pinch which need two fingers.

**Comment by tsaohucn** [comment]
I find in Android PinchGestureHandler call onEnded when one finger left off screen and also event.nativeEvent.numberOfTouches is undefined in Android from onGestureEvent callback, but It has event.nativeEvent.numberOfTouches value 1 or 2 in IOS, it seems like two different behavior in two different OS.

**Comment by tsaohucn** [comment]
I find there's a bug in IOS because the on single release behavior as I metioned above, I make a video in the below, android didn't occur this bug because single finger release will end pich callback on android.
 
https://youtu.be/1-aMryt-7o0

![20180311_180450](https://user-images.githubusercontent.com/6713879/37252859-78a60dd2-255b-11e8-880b-28e76ab19464.jpg)

Actually, my expect behavior is like the video in the below, so my real expect function is making android's behavior as same as single finger release behavior of IOS without bugs.


https://youtu.be/EJ88f6LSA1E

**Comment by osdnk** [comment]
Would you mind leaving us some sample in order to reproduce this issue?

**Comment by osdnk** [comment]
I decided to close the issue as it seems to be inactive. If you still face the problem, don't hesitate to write or reopen the issue
