### ISSUE TITLE
Something about the d.ts is off

### ISSUE THREAD

**Issue by jhalborg** [kmagiera/react-native-gesture-handler#135]
Hey :)

Just trying out the d.ts typings, and I think something's off. Just importing them into a file gives 5 warnings (at least on TS v 2.7.2)

Steps to reproduce: 

1. Open a TypeScript project
2. Copy+paste the raw d.ts file into the project, have Typescript try to parse it

**Comment by brunolemos** [comment]
Yes, there are pending fixes. If you can please do a PR.

**Comment by brunolemos** [comment]
Fixed on #138
