### ISSUE TITLE
2 fingers tap

### ISSUE THREAD

**Issue by ptaranto** [kmagiera/react-native-gesture-handler#146]
Is there a way to implement/detect a tap with 2 fingers?

**Comment by osdnk** [comment]
@ptaranto 
I think it will be done soon

**Comment by osdnk** [comment]
done :), @ptaranto

**Comment by ithieund** [comment]
@osdnk ,
Can you show me how to detect 2 fingers tap with this plugin?

Thanks.

**Comment by roviera** [comment]
@osdnk , I'm not being able to detect 2 fingers on just one tap, can you provide any guidance on this?
