### ISSUE TITLE
Demo GIFs?

### ISSUE THREAD

**Issue by deadcoder0904** [kmagiera/react-native-gesture-handler#149]
I know this is still in Alpha but would love to see some Demo GIFs like https://github.com/archriss/react-native-snap-carousel

**Comment by kmagiera** [comment]
Great suggestion @deadcoder0904. We are working on revamping docs for the project and will definitely make some demo videos for the next version. In the meantime if you have more suggestions on what should be put on the clips feel free to reopen this issue and we can discuss it here.
