### ISSUE TITLE
attachGestureHandler called with a null viewTag – problem with React 16.3

### ISSUE THREAD

**Issue by kmagiera** [kmagiera/react-native-gesture-handler#153]
Haven't verified it 100% but I think I was getting error that native method `attachGestureHandler` gets called with a null viewTag.

I believe the root cause could be that in React 16.3 the order of calling didMount and ref handler changed and so this._viewNode is now empty in componentDidMount which causes the aforementioned `attachGestureHandler` call.

Can you verify this @osdnk and think of some fix for it?

**Comment by osdnk** [comment]
Have just updated locally project with React 16.3 and put some hook on every `RNGestureHandlerModule.attachGestureHandler`. It seems to be perfectly mind.

How did you observe it? Would you mind giving me some details?

**Comment by kmagiera** [comment]
Could've been some weird setup issue my side. Closing
