### ISSUE TITLE
Question: Could this be used to create a custom Pull to Refresh for a FlatList

### ISSUE THREAD

**Issue by duro** [kmagiera/react-native-gesture-handler#158]
I have been working to get a custom PullToRefresh animation integrated on top of FlatList. I have been trying to use this library: https://github.com/NadiKuts/react-native-pull-refresh which uses the built in PanResponder in RN.

While this library does work, it suffers from some issues with blocking taps on the underlying list items before a scroll has occurred. As I was gearing up to do some serious debugging on a fork, I came across this library, which seems to be much more actively maintained, and far easier to reason about than the RN PanResponder.

But before I settle in to a rewrite of the functionality from scratch using this library, I would love to get some insight from those who maintain it, or have used it extensively, to see if I'm on the right track.

Any insight is greatly appreciated.

**Comment by osdnk** [comment]
I suppose it's fine to use our library here. 
If it was up me I would use `PanGestureHandler` here and change position of list using this handler. 
I think it's crucial to detect the moment to trigger animation in JS. Here you may use `minDeltaY` prop and handle callback on change state of gesture to trigger animation. Handler will become `active` when you move finger for enough offset.
However, maybe you wish to consider using native scrollView as well to manage increasing size of your loader.
Take a look here: https://youtu.be/V8maYc4R2G0?t=8m46s. @kmagiera is talking about quite similar issue.
If you still face any problem, please reopen this issue
