### ISSUE TITLE
Clarify differences from official PanResponder

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#16]
I haven't used any but it would help to know the differences in the readme. Thanks.

**Comment by kmagiera** [comment]
Thanks @brunolemos for a great suggestion. The docs are still sth we have on a radar. We hope to get to it very soon. I think it would be great to illustrate the differences for ppl familiar with PanResponder this way

**Comment by henrikra** [comment]
@brunolemos Check this out: https://www.youtube.com/watch?v=V8maYc4R2G0
There is everything you need to know :)

**Comment by osdnk** [comment]
@brunolemos, I suppose @henrikra gave you a good explanation
