### ISSUE TITLE
Huge Memory Leak in Release Builds

### ISSUE THREAD

**Issue by conyewest** [kmagiera/react-native-gesture-handler#167]
# UPDATE
### This memory leak was not directly caused by React Native Gesture Handler, but from React Native itself.

<del>I've noticed a huge memory leak that occurs when running release builds for iOS.</del>

<del>Given the following example:</del>

```
onTapGesture(event) {
    if(event.nativeEvent.state === State.ACTIVE) {
        Alert.alert("Tapped!");
    }
}

onLongPressGesture(event) {
    if(event.nativeEvent.state === State.ACTIVE) {
        Alert.alert("Long Press!");
    }
}

<TapGestureHandler onHandlerStateChange={ this.onTapGesture.bind(this }>
    <LongPressGestureHandler onHandlerStateChange={ this.onLongPressGesture.bind(this }>
        <Text>Hello World</Text>
    </LongPressGestureHandler>
</TapGestureHandler>
```

<del>In the development build, it operates exactly as expected, however, when building for release the gestures are not immediately available (they cannot be activated) and around 900MB of memory is allocated in a few seconds following which any gestures that occurred during this time are immediately executed.  This memory continue to be allocated in huge amounts every time a subsequent gesture is triggered until the application and/or the device crash.</del>

<del>Here's a release debug for the above example running for around 30 seconds and performing two long presses.</del>

<img width="269" alt="screen shot 2018-05-10 at 16 54 37" src="https://user-images.githubusercontent.com/36987742/39879569-13712234-5473-11e8-82cb-8ca85081abef.png">

## Environment:
  <del>OS: macOS High Sierra 10.13.2
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003</del>

<del>Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0
  react-native: 0.54.4 => 0.54.4</de>

**Comment by osdnk** [comment]
Hi, @conyewest 
Thank you fort using our library. 
Problem you describe seems to be serious and we wish to take a deep concern on this issue. 
I have pasted you code into out Example's `App.js`:
https://gist.github.com/osdnk/c7755ac3daba2ebd9591eb8130e656ba
and then opened app in release mode. Memory usage seems not to be weird (~66MB without changes).
Would you mind installing newer version of react and react-native? e.g.
```
    "react": "^16.3.2",
    "react-native": "^0.55.3",
```
If you still face the problem, please, prepare workable project and link a repository. Then we will check if we could reproduce it. Unfortunately, I cannot do i it now
Thank you again and I'm waiting for your response.
![image](https://user-images.githubusercontent.com/25709300/39923060-5cb52fd0-5522-11e8-9fcc-7a685bbace07.png)
![image](https://user-images.githubusercontent.com/25709300/39923066-6319d632-5522-11e8-8172-b0e0dca2f3dc.png)

**Comment by osdnk** [comment]
I did also checked this issue using 
```
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.4",
```
and still cannot repro

**Comment by osdnk** [comment]
Well, as i see this issue seems to be inactive and I decided to close it. If you still face the problem, please reopen the issue and attach some workable example.
Thank you for this issue and using our library
