### ISSUE TITLE
simultaneousHandlers doesn't to work on iOS

### ISSUE THREAD

**Issue by jhalborg** [kmagiera/react-native-gesture-handler#169]
Hey, 

I think something with `simultaneousHandlers` broke on iOS. The following snack works fine on Android, but not on iOS:

https://snack.expo.io/@jhalborg/sticker-example 

On Android, the photo is easily manipulated on both drag, zoom and rotate simultaneously, but on iOS only one gesture can be performed at a time. 

SDK 24
Expo client: 2.5
I also tried adding `"react-native-gesture-handler": "^1.0.0-alpha.43"` to `package.json`, but nothing changed, unfortunately

**Comment by brentvatne** [comment]
that's a pretty old sdk version. I updated to the latest and imported `GestureHandler` from `expo` (to ensure you get a compatible version) and it works as expected: https://snack.expo.io/SkJ0LUX0z

**Comment by jhalborg** [comment]
Thanks for getting back to me @brentvatne :-)

And, OK - upgrading to SDK 27 is also in our pipeline, but on first upgrade experimentation it messed a bit with our UI (probably due to React/RN changes), so it's been put off until next week I believe. In any case, shouldn't it still work with SDK24? It has worked previously.

**Comment by osdnk** [comment]
I'm sorry for not being active in this issue but as I notice it's already ha been solved.
Thank you for using our library

**Comment by brentvatne** [comment]
@jhalborg - not necessarily, it's possible that there was a bug in sdk24 with gesturehandler, it was in dangerzone at the time so no guarantees around it

**Comment by omarandstuff** [comment]
I'm running https://snack.expo.io/SkJ0LUX0z in my iOS device and is not working, only one gesture at a time

**Comment by brentvatne** [comment]
@omarandstuff - i changed that to sdk32 and it works fine: https://snack.expo.io/@notbrent/repro

**Comment by omarandstuff** [comment]
Hey thanks for the update, I opted out to use the Pan Responder from RN and worked well for me, but definitely is worth taking another look to this one for future work
