### ISSUE TITLE
"i" is read-only

### ISSUE THREAD

**Issue by macrozone** [kmagiera/react-native-gesture-handler#17]
in https://github.com/kmagiera/react-native-gesture-handler/blob/de3ae768a715f408cc3e361bcf46e6bd98402885/GestureHandler.js#L361

there is a `for (const i = ...)` which throws an error: "i" is read-only. This should be a let declaration.

Edit: I don't know why i get this error all of sudden. I don't have it in another project. But this line is clearly wrong

**Comment by kmagiera** [comment]
Thanks @macrozone will fix this with the next release

**Comment by kmagiera** [comment]
And the fix is here https://github.com/kmagiera/react-native-gesture-handler/commit/281b7921eb7dcce98517ad596437695449577bd3
Thanks again!
