### ISSUE TITLE
Integrate with Touchables inspector

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#170]
If you use `TouchableOpacity` and other such components, the Touchables inspector lets you visualize the touch area nicely.

![slack-imgs](https://user-images.githubusercontent.com/90494/39938791-ee7f4e42-5508-11e8-9d33-cb88c7d5bc27.png)

It'd be great to integrate react-native-gesture-handler in there as well, or have a comparable tool.

**Comment by osdnk** [comment]
I'll gonna take I look. 
I suppose that's even more crucial as long as RNGH gets crash with [React Native Debbuger](https://github.com/jhen0409/react-native-debugger) and I suppose it's quite similar issue
