### ISSUE TITLE
ReactNativeBridgeEventPlugin can not be used anymore

### ISSUE THREAD

**Issue by Un3qual** [kmagiera/react-native-gesture-handler#191]
`ReactNativeBridgeEventPlugin` was removed with this commit https://github.com/facebook/react-native/commit/906dde06b3f25b4e87adcbc8ed64f72bc930ac6a. It's used here: https://github.com/kmagiera/react-native-gesture-handler/blob/dd8c94fada3aec5f6fee3960a56b1170c112f659/GestureHandler.js#L19
I just discovered this project, so I don't know much about its internals, but it looks like `ReactNativeBridgeEventPlugin` was added in #44. Is it necessary for both platforms or just Android? 

Right now it's only broken for people using [facebook/react-native#master](https://github.com/facebook/react-native), (like me 😢), but it will probably be gone when 0.56 is released. I'm not sure what to do to replace it, but a quick Google search turned up [maicki/react-native-event-bridge](https://github.com/maicki/react-native-event-bridge). I'm not sure if that can work as a replacement, but just in case, I've linked it.

**Comment by kmagiera** [comment]
Hey @Un3qual Thanks for letting us know. We will look into this as soon as possible.
