### ISSUE TITLE
Swipeable: renderRightActions on Button press 

### ISSUE THREAD

**Issue by freshedgarT** [kmagiera/react-native-gesture-handler#192]
Is there a possibility to programmatically open the right or left action panel, as if a user had swiped.

An example:
I can swipe to open the right action panel or I press a button to open the same action panel.

**Comment by kmagiera** [comment]
Hey @freshedgarT! Thanks for reaching out.

Unfortunately there is no method for doing it with the current version.

Although it may be possible using a call to internal method called `_animateRow`. You can take a look at how `close` method is implemented: https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js#L261
Instead of passing `0` as a second arg you'd need to pass an offset to which the row should animate to.

In the meantime I'll flag this as a "feature request" and leave it open as it definitely makes sense to add such a method to Swipeable

**Comment by freshedgarT** [comment]
@kmagiera thanks for the quick reply and the advice.
I'll try it out and post if it worked.

**Comment by freshedgarT** [comment]
So i tried to implement a function to open the right action panel and used the `onSwipeableRightOpen` property to check if I am passing the correct parameters to `_animateRow`. When pressing my Button that calls my open right action panel function, the `onSwipeableRightOpen` callback is called, `_currentOffset` returns correctly (-192), but the right action panel does not open.

@kmagiera I was hoping you could look over my code, to check if I forgot something.

```
_swipeableRow: any;

openRightActions() {
  this._swipeableRow._animateRow(this._swipeableRow._currentOffset(), -192);
}

close = () => {
  this._swipeableRow.close();
};

_updateRef = (ref: any) => {
  this._swipeableRow = ref;
};

_renderRightAction = (text: string, color: string, x: number, progress: Object) => {
  const trans = progress.interpolate({
    inputRange: [0, 1],
    outputRange: [x, 0],
  });
  const pressHandler = () => {
    this.close();
  };
  return (
    <Animated.View style={{ flex: 1, transform: [{ translateX: trans }] }}>
      <RectButton style={[styles.rightAction, { backgroundColor: color }]} onPress={pressHandler}>
        <Text style={styles.actionText}>{text}</Text>
      </RectButton>
    </Animated.View>
  );
};

_renderRightActions = (progress: Object) => (
  <View style={{ width: 192, flexDirection: 'row' }}>
    {this._renderRightAction('More', '#C8C7CD', 192, progress)}
    {this._renderRightAction('Flag', '#ffab00', 128, progress)}
    {this._renderRightAction('More', '#dd2c00', 64, progress)}
  </View>
);

render() {
  const { children } = this.props;
  return (
        <Swipeable
          ref={this._updateRef}
          friction={1}
          rightThreshold={40}
          renderRightActions={this._renderRightActions}
          onSwipeableRightOpen={() => {
            console.log('openedRightWithCallback');
            console.log(this._swipeableRow._currentOffset());
          }}
          useNativeAnimations
        >
          {children}
        </Swipeable>
  );
}
```

**Comment by freshedgarT** [comment]
I found my mistake. We have a list of items that are SwipeableComponents. We were calling `openRightActions()`  on the wrong reference.
Creating an Object of references mapped to the id of our list items and calling `openRightActions()` in respect to the id, solved the problem.

@kmagiera  Thanks for the advice. It was a big help!

**Comment by kmagiera** [comment]
Great to hear it ended up working for you!

I you are willing to submit a PR with `openRightActions` and `openLeftActions` method I will be more than happy to merge that in.

In the meantime I will close this issue. If you'd like to discuss this topic further feel free to reopen
