### ISSUE TITLE
[Suggestion] Copy the documentation to the README?

### ISSUE THREAD

**Issue by Jarred-Sumner** [kmagiera/react-native-gesture-handler#193]
I like using `react-native-gesture-handler` and appreciate all the hard work you've put in! It's a great library.

It's really helpful to be able to quickly apple-f for documentation on specific components, and the new documentation site's layout makes it take a little bit longer to find what the expected props or import name is.

I'm not entirely sure what the best solution here is (or if it's a priority to fix), but one thought would be to copy all the documentation into the readme, so that developers can apple-f from the main github repo page to find everything they need without having to figure out which page to click on to get to the information

My apologies if this suggestion is unwanted

**Comment by osdnk** [comment]
Thank you, @Jarred-Sumner, for your suggestion
However we do not consider it as good idea.
I suppose that every code editor supports suggestions with methods exported from the library (as I checked in VSCode and WebStorm) as we added proper typings with TypeScript.
What's more, the file generated form whole documentation will be extremely long (as it was few commits ago) and then searching for anything is not simple and effective. 
In addition, I think thet everyone using this library needs to get acquainted with documentation as it's not so easy to use.
