### ISSUE TITLE
Is there anyway to add a snapTo function?

### ISSUE THREAD

**Issue by Burnsy** [kmagiera/react-native-gesture-handler#210]
Hello, experimenting with this library and I looked over the demo [Bottom Sheet Demo](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/bottomSheet/index.js)

Is there a way that I could call a function to move the position of the sheet to another snap point?
as in reference the PanGestureHandler and say snap to next point onPress? 

Thanks for the great library.

**Comment by kmagiera** [comment]
Hey @Burnsy, thanks for reaching out!

Imperative snapTo command would be more of a responsibility of animated library than handler component by itself. 

It's something that can definitely be added. If you'd be interested in playing with that I can point you to the source code of SwipeableRow where we have imperative commands for opening/closing swipeable row. What these command do is they start animation of the value that corresponds to the row offset. Something very similar should be possible for bottom sheet

**Comment by Burnsy** [comment]
If you could point me in the right direction that will be great! 👍🏻
