### ISSUE TITLE
Support disabled prop for buttons

### ISSUE THREAD

**Issue by janicduplessis** [kmagiera/react-native-gesture-handler#22]
I'm trying out to swap a generic Touchable component I use in an app to use this library instead of react-native TouchableX and one simple feature I noticed was missing is a way to disable the buttons, RN touchables have a disabled prop.

From what I understand this feature could be implemented in JS land by just not showing feedback and preventing the call to onPress.

**Comment by kmagiera** [comment]
👍 

This sounds good. Ideally I'd like for gesture handlers to have `active` property, which could be used for this purpose. If that'd only be done on the JS side the button would still capture click events which could be undesirable.

Also I think regular RN's touchables are "disabled" when `onPress` is empty

**Comment by janicduplessis** [comment]
True we'd have to handle this in native, I might try to implement it next time I get some free time :)

**Comment by kmagiera** [comment]
This has landed in #33 
Thanks for suggesting this feature!
