### ISSUE TITLE
Keyboard dismisses on state update inside any child of <GestureDetector>

### ISSUE THREAD

**Issue by taykay-bet** [kmagiera/react-native-gesture-handler#2249]
### Description

Can't update state in onChangeText of TextInputs because the rerender causes keyboard to be dismissed. This is not exclusive to just ScrollView without keyboardShouldPersistTaps, it seems to happen to any component. 

### Steps to reproduce

1. Create a TextInput inside any GestureDetector component
2. Set the onChangeText event 

### Snack or a link to a repository

https://snack.expo.dev/YU-v7tKAv

### Gesture Handler version

2.2.1

### React Native version

0.68.2

### Platforms

Android, iOS

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Acknowledgements

Yes

**Comment by Warus15** [comment]
Hi 👋 I've checked snack that you've provided on both iOS and Android and everything seems to work fine. Please try updating GestureHandler to new version (current one is [2.6.2](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.6.2)) and then check if the problem still occurs.

**Comment by taykay-bet** [comment]
Hi, I've updated the package but the problem still persists.

**Comment by j-piasecki** [comment]
In that case, could you provide more details? The snack you've provided seems to be working (besides style errors, you want to use `width: 50` instead of `width: '50px'`), both on Android and on iOS.

**Comment by taykay-bet** [comment]
@j-piasecki Hi, I've updated the snack at this link: https://snack.expo.dev/YU-v7tKAv. The bug should be able to show now.

**Comment by Warus15** [comment]
Hi! I've checked updated snack and it seems that it is not a problem with GestureHandler nor with having it inside modal. I've managed to make keyboard working by moving `const [text, setText] = useState('');` inside `<AndroidRootHOC/>` component. I'd say that this is related to how react-native handles state changes - probably `TextInput` loses focus.

**Comment by taykay-bet** [comment]
Hi @Warus15, Although this does solve the problem on the snack, it won't work if textinput is dynamically rendered inside the GestureModal as I'm intending to do. What I've noticed is that this bug only happens if GestureDetector is wrapped in a react-native Modal. Probably has to do with props.visible causing a re-render of the Modal every time any other state causes a re-render.

**Comment by Warus15** [comment]
Hi @taykay-bet! I've removed GestureHandler from your snack and the keyboard still dismisses, so I don't think that the problem lies in GestureHandler. Also you can try to extract `<AndroidRootHOC/>` into separate component, like in the code below - that should help. And the last thing, you said that you want to dynamically render TextInput, make sure that you follow [rules of hooks](https://reactjs.org/docs/hooks-rules.html).

```JSX
import React, { useState, useEffect } from 'react';
import { Modal, StyleSheet, View, Dimensions, TextInput } from 'react-native';
import {
  Gesture,
  GestureDetector,
  gestureHandlerRootHOC,
} from 'react-native-gesture-handler';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';

const AndroidRootHOC = gestureHandlerRootHOC((props) => {
  const position = useSharedValue(0);
  const [text, setText] = useState('');

  const windowHeight = Dimensions.get('window').height;

  const dragGesture = Gesture.Pan()
    .onChange((e) => {
      if (e.translationY > 0) {
        position.value = e.translationY;
      }
    })
    .onEnd((end) => {
      if (position.value > 100 && end.velocityY > 0) {
        position.value = withTiming(700, 150);
      } else {
        position.value = withTiming(0, 50);
      }
    });

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: position.value }],
  }));

  return (
    <Animated.View
      style={[
        {
          position: 'relative',
          flex: 1,
          marginTop: props.halfScreen ? windowHeight * 0.5 : windowHeight * 0.1,
        },
        animatedStyle,
      ]}>
      <GestureDetector gesture={dragGesture}>
        <View
          style={{
            width: '100%',
            height: '100%',
            backgroundColor: 'lightgrey',
            borderTopLeftRadius: 25,
            borderTopRightRadius: 25,
            elevation: 24,
          }}>
          <TextInput
            style={{
              width: '90%',
              height: 50,
              margin: 40,
              backgroundColor: 'white',
              alignSelf: 'center',
            }}
            onChangeText={(text, i) => {
              setText(text);
            }}
          />
        </View>
      </GestureDetector>
    </Animated.View>
  );
});

export default function GestureModal(props) {
  const { visible } = props;
  const position = useSharedValue(0);
  const [dismiss, setDismiss] = useState(false);

  //poll for dismiss at 30fps
  useEffect(() => {
    const check = setInterval(() => {
      if (position.value === 700) {
        setDismiss(true);
      }
    }, 1000 / 30);
    return () => clearInterval(check);
  }, []);

  useEffect(() => {
    if (dismiss && !!props.onRequestClose) {
      props.onRequestClose();
    }
  }, [dismiss]);

  // need this for android, no-op on iOS

  return (
    <Modal
      animationType={props.animationType || 'slide'}
      transparent={props.transparent || true}
      statusBarTranslucent={props.statusBarTranslucent || false}
      visible={visible}
      onRequestClose={() => props.onRequestClose()}>
      <AndroidRootHOC />
    </Modal>
  );
}
```
