### ISSUE TITLE
Cannot add property current, object is not extensible

### ISSUE THREAD

**Issue by Burnsy** [kmagiera/react-native-gesture-handler#227]
I have added the drawer to my project but it seems to be crashing. 

Unhandled JS Exception: TypeError: Cannot add property current, object is not extensible

![simulator screen shot - iphone x - 2018-06-26 at 09 30 57](https://user-images.githubusercontent.com/15834048/41899164-accc09ec-7923-11e8-832b-ee63236d174d.png)

the code is 100% the same as the example that works.

React-native: 0.55.4
react-native-gesture-handler: 1.0.5
If applicable;
react-native-navigation: 2.0.2349

`
This error is located at:
    in Handler (at Home.ios.js:109)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at Home.ios.js:101)
    in RCTView (at View.js:60)
    in View (at Home.ios.js:100)
    in Handler (at Home.ios.js:95)
    in BottomSheet (at Home.ios.js:155)
    in RCTView (at View.js:60)
    in View (at Home.ios.js:154)
    in Example (at ComponentWrapper.js:55)
    in WrappedComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)`

**Comment by osdnk** [comment]
Hi, @Burnsy 
Did it fixed tour problem?

**Comment by Burnsy** [comment]
yes! Sorry for the wait.
