### ISSUE TITLE
TapGestureHandler position information inconsistent

### ISSUE THREAD

**Issue by cwhenderson20** [kmagiera/react-native-gesture-handler#233]
When using the TapGestureHandler's event on state change to determine the location of the tap, that location relative to the root, denoted by `absoluteX`/`absoluteY`, is accurate when the handler requires only one tap (`numberOfTaps={1}`), but becomes more than occasionally _inconsistent_ when more than one tap is required.

Here is a snack to demonstrate:
https://snack.expo.io/@cwhenderson20/gesture-handler-double-tap-coordinate-bug

Try tapping the small green dot and note the approximate coordinates (approximately `{ x: 198, y: 341 }` on a 4.7" device). Then double-tap and you may notice that those coordinates also approximately double (to `{ x: 396, y: 680 }`). It doesn't happen every time, however, and from what I can tell, it only happens on iOS devices.

Similar odd behavior happens if you make the double-tap handler instead a triple-tap handler. Additionally, even after removing the single-tap handler completely (so the double-tap handler is the only one registered), the inconsistencies still occur.

Happy to provide more info if necessary. Thank you for the great library!

**Edit:**
It looks like this issue began when the `UITapGestureRecognizer` was replaced with `UIPanGestureRecognizer` in PR #143. Version 1.0.0-alpha.43 (the last version before the PR) gives the correct values, while 1.0.0 does not.

**Comment by cwhenderson20** [comment]
@osdnk maybe you'll have some thoughts on this as the author of the PR?

**Comment by osdnk** [comment]
Hi, @cwhenderson20 
I did take a lot on it for a while but IK didn't manage to find out the issue. I didn't have enough time to take a deeper care about it, but I wish to do it asap

**Comment by osdnk** [comment]
@cwhenderson20, 
Did you find any deterministic way to repro it?

**Comment by cwhenderson20** [comment]
@osdnk not yet; I’ve been trying though. It seems random, but I’m sure it’s not. I’ll continue to experiment. Thanks!

**Comment by osdnk** [comment]
I did manage to find solution I suppose and I will handle to do it as soon as possible

**Comment by cwhenderson20** [comment]
Great news! I'll be happy to help test if you need.

**Comment by osdnk** [comment]
@cwhenderson20 
Should be fixed.
