### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#243]
Is there any port of this library for the web?
I think @vincentriemer [started a port](https://twitter.com/vincentriemer/status/1006733233881600000) but not sure if that can be decoupled from react-native-dom.

Motivation: I'm a believer that all react-native packages should have web support.
Sharing code between platforms is one of the strengths of react-native, so every library I add I check if it has web support or how easy would it be to implement it myself.

**Comment by osdnk** [comment]
Hi, @brunolemos 
Thank you for this issue. We are conscious that this is extremely important to support web as well. We will keep it in mind to do it some day but unfortunately it won't be happen in the nearest future.
Thus I decided to close this issue, but I doesn't mean that your idea won't be done some day.

**Comment by jaulz** [comment]
@brunolemos I just created https://github.com/kmagiera/react-native-gesture-handler/pull/406 in case you want to use it on web as well.

**Comment by yairopro** [comment]
Seems it's being implemented.🤗

[Post on github](https://github.com/kmagiera/react-native-reanimated/issues/169#issuecomment-533803491)
[Post on tweeter](https://twitter.com/Baconbrix/status/1173825701192929280)

**Comment by elie222** [comment]
Wondering what the state of this is atm. Trying to convert a RN project to web, but ran into an issue around RNGH. For now, I'll just remove this functionality from web, but interested if there's a way to get it working already/timeline

**Comment by AntoineFacq** [comment]
Any news about it ? It seems like many libraries are dependent of this one to work on web, isn't it?

**Comment by moonman239** [comment]
I think Web functionality would be awesome, because it would help us to decentralize the mobile environment. Imagine a future where you can sell your apps & in-app purchases without paying Apple $99/year + 30% of sales. Plus you can take cryptocurrency payments.

**Comment by KhimGurung** [comment]
I am just wondering if it is now supporting web or not. I am using storybook with react-native-web. With the [addon-react-native-web](https://github.com/storybookjs/addon-react-native-web) everything is working in storybook but couldnt get it running in the project.
