### ISSUE TITLE
Add open method to Swipeable

### ISSUE THREAD

**Issue by henrikra** [kmagiera/react-native-gesture-handler#251]
Would it be possible to add `open` function for `Swipeable` similar to `close` https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js#L260

**Comment by osdnk** [comment]
Yes, I think it's fine. I could do it in near future if you you wish, you could make a PR as well.
But let you mind that you need also do consider direction. Maybe sth like that:
```
  openLeft = () => {
    // ...
  };
```

```
  openRight = () => {
    // ...
  };
```

**Comment by osdnk** [comment]
... or I done it

**Comment by henrikra** [comment]
@osdnk Why reopen? :D

**Comment by osdnk** [comment]
¯\_(ツ)_/¯
