### ISSUE TITLE
Can't disable PanGestureHandler

### ISSUE THREAD

**Issue by farkob** [kmagiera/react-native-gesture-handler#255]
I disable a PanGestureHandler through its `enabled` prop while it's responding, I disable it using setState when a value hits a limit while the interaction is going on. Handler stops responding as expected. However, after that when I start interacting again, even though `enabled={false}` it keeps responding. (On iOS, haven't tested on Android)

(Also not related but a question: This PanGestureHandler is inside a ScrollView, after I disable the PanGestureHandler, I want ScrollView to respond as normal in that same continuous finger move, how can I do this? Any ideas?)

**Comment by osdnk** [comment]
Hi,
I did wish to repro it so I've added `enabled={false}` to `draggable` example and it works as I expected. Would you mind providing some code?

**Comment by osdnk** [comment]
...so this example is working and you wish to remove `this.state = { disabled: false };`?

**Comment by farkob** [comment]
No no no. I meant if you set `this.state.disabled = true` from the get-go, PanGestureHandler does not respond to touches, as expected.

Actually, I made a snack here to make it easier to see. Then I realized it was working as expected. After testing everything I realized if I had it wrapped in a Modal, as in the snack it stopped working as expected. You can try it here. Pinch and zoom the image, then pan it to left until you hit the bound, you will see that it will stop responding as expected. But then move your finger away and try panning again, you can pan it! If you change the wrapper to be a `View` it won't pan after its disabled. https://snack.expo.io/@farkob/pangesturehandler-disabled.

**Comment by osdnk** [comment]
@farkob,
I strongly discourage you to use Modal with RNGH.
We suppose it should be fixed some day but it seems to be quite complicated issue

**Comment by osdnk** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/139

As you see, we have modals on radar, but frankly speaking, we cannot find out what's the problem 😢

**Comment by osdnk** [comment]
For now I decided to close this issue as it is related to another one
