### ISSUE TITLE
When I try to build in Xcode, I get 'React/RCTEventDispatcher.h' file not found

### ISSUE THREAD

**Issue by arnoldbird** [kmagiera/react-native-gesture-handler#262]
When I try to build, I am getting errors like...

```
In file included from /Users/me/inspira/ally_app/node_modules/react-native-gesture-handler/ios/RNGestureHandlerEvents.m:1:
/Users/me/inspira/ally_app/node_modules/react-native-gesture-handler/ios/RNGestureHandlerEvents.h:1:9: fatal error: 'React/RCTEventDispatcher.h' file not found
#import <React/RCTEventDispatcher.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

These errors reference react-native-gesture-handler, but actually began after I tried unsuccessfully to install react-native-image-picker.  I have since removed react-native-image-picker, but am still unable to build and still getting these errors referencing react-native-gesture-handler.

I'm using react-native-gesture-handler version 1.0.7.  I also was having the same issue with an alpha version of react-native-gesture-handler before I upgraded.
I'm using React Native version 0.54.2.

**Comment by osdnk** [comment]
Hi, @arnoldbird 
I did notice that this issue occurs from time to time. I also faced it some day. Would you mind trying:
`react-native start --reset-cache` or _clean build_ in XCode? I'm rather sure that it's not related to this picker.

**Comment by arnoldbird** [comment]
@osdnk 
I was able to resolve this.  I'm using Expo, and I resolved this by [un-detaching](https://docs.expo.io/versions/latest/expokit/advanced-expokit-topics.html) and then re-detaching to ExpoKit.

**Comment by FrancisRenaud** [comment]
I have the same issue. However only when I try to build in release ...
