### ISSUE TITLE
BottomSheet example doesn't work in Android

### ISSUE THREAD

**Issue by Stalder** [kmagiera/react-native-gesture-handler#264]
Hey, really nice lib! However, i met with a little trouble - BottomSheet example that works great with IOS, doesn't  react any gestures on Android

**Comment by Stalder** [comment]
Oops, my fault. It didn't react on the screen that contains another gesture handlers (It's weird too, but I believe it's smth in my code). However, it behave weird on android anyway, but it's already another issue, that I'll try to fix. Sorry for disturbing :)

**Comment by j1mie** [comment]
I have the bottomsheet working on Android, though with some strange behaviour. It seems to scroll the scrollview before the yOffset reaches the top

**Comment by sgtpsibin** [comment]
any update?
