### ISSUE TITLE
Removing Swipeable component with LayoutAnimation gives unexpected results

### ISSUE THREAD

**Issue by jarrx** [kmagiera/react-native-gesture-handler#267]
I want to remove components which are transparent and wrapped by Swipeables. Using LayoutAnimation when the components gets removed causes the right action buttons to appear.
![ezgif com-optimize](https://user-images.githubusercontent.com/31743687/43368999-66903cde-9366-11e8-84b9-aaf34e5fa07d.gif)

**Comment by osdnk** [comment]
Hi,  @jarrx 
Would you mind attach some source code?

**Comment by AbdallaMohamed** [comment]
Have you considered using Flipkart's recycler listview? https://github.com/Flipkart/recyclerlistview

I guess it has support for that.

**Comment by jarrx** [comment]
I realized this was probably a design error of my rightActions, i.e. not an error with the swappable component.
