### ISSUE TITLE
iOS crash perhaps caused divide by zero somewhere in gesture handler code

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#27]
![screen shot 2017-09-13 at 11 32 00 am](https://user-images.githubusercontent.com/90494/30394273-7ce1e414-9877-11e7-87c8-5aa6b6343690.png)

Ran into this error while recording the example from https://github.com/kmagiera/react-native-gesture-handler/issues/26: https://www.youtube.com/watch?v=g-LLvP5x6vk

@terribleben opined that "nan/inf suggests divide by zero in gesturehandler math"

**Comment by kmagiera** [comment]
So the issue was that sometimes pinch or scale UIGestureRecognizer would yield velocity = NaN
Made a workaround for this here https://github.com/kmagiera/react-native-gesture-handler/commit/b9730a94bea2da6f778b69d1743f540ec5fc9fa4
