### ISSUE TITLE
Position on Tap / LongPress

### ISSUE THREAD

**Issue by rt2zz** [kmagiera/react-native-gesture-handler#270]
I have the following use case: a chart scrubber that activates on long press.

This works on iOS where x/y is provided, but as discussed here those are not supported properties and do not work on android: https://github.com/kmagiera/react-native-gesture-handler/issues/187

I understand how to use a PanGH to handle the scrub on drag but it appears there may be no way to get the on press position in order to draw the scrubber from the LongPressGH. Thus a move is required before the PanGH activates and can draw the correct scrubber.

Is there any way to solve this in RNGH?

**Comment by osdnk** [comment]
Already done 👍

**Comment by chirhotec** [comment]
Could we get a new release to make this available?

**Comment by alamothe** [comment]
TypeScript definitions are not updated 🙂

**Comment by osdnk** [comment]
@alamothe would you like to do it?

**Comment by MrPluto** [comment]
run the example，and the tap gesture event always get me `{x:0,y:0}`
