### ISSUE TITLE
Preventing multiple pan handlers from being active simultaneously

### ISSUE THREAD

**Issue by jarrx** [kmagiera/react-native-gesture-handler#271]
Is it possible to prevent multiple pan handlers from being active simultaneously without changing the enable prop?

In my case I have a FlatList with swipeables  and if one of the swipeable is active, I want to prevent the user from activating any of the others with another finger.
For example IOS mail app works this way - you can never open more than one swipeable.

Changing the enable prop is too slow and waitFor didn't work.

**Comment by osdnk** [comment]
Hi, @jarrx 
I've just change Example app (`Gesture Handler Based Swipeable Row`) and added index as `id` with `waitFor={Object.keys([... new Array(8)])}` (I know it's very dirty) in for each `Swipeable`.
Everything seems to be perfectly fine.
Would you mind attach some example with your problem?

**Comment by co2nut** [comment]
@jacobrosenskold do you have any solution yet?

**Comment by NarendraKuruva** [comment]
Hi @osdnk 

This issue still persists while rendering a list of swipeables

When I swipe 3 items in the list with three fingers at a time, then the three items are being swiped.

**Comment by NarendraKuruva** [comment]
> Hi @osdnk
> 
> This issue still persists while rendering a list of swipeables
> 
> When I swipe 3 items in the list with three fingers at a time, then the three items are being swiped.

Here is an example snack :- https://snack.expo.dev/@narendra.kuruva/smart-watermelon

**Comment by NarendraKuruva** [comment]
@osdnk 

Any solution found for this one ?
