### ISSUE TITLE
PanGestureHandler minDeltaX not working as expected

### ISSUE THREAD

**Issue by jarrx** [kmagiera/react-native-gesture-handler#273]
Having PanGestureHandler with `minDeltaX={-10}` PREVENTS the handler from activating regardless of which direction you swipe.
Having `minDeltaX={10}` makes the handler ACTIVATE regardless of direction.

What I want to actieve is making the pan gesture handler activate only when you swipe from right to left, which minDeltaX={-10} should do.
Would really appreciate some help on this.

```
React: ^16.4.1
React native: ^0.55.4
RNGH: ^1.0.7
Tested on simulator and device in debug.
```

**Comment by osdnk** [comment]
Hi @jarrx 
Well, you're absolutely right. I was also surprised by this behaviour but it seems to be only bug in docs:
Take a look: https://github.com/kmagiera/react-native-gesture-handler/pull/274
