### ISSUE TITLE
<Swipeable> conflict with react navigation fullScreenGestureEnabled

### ISSUE THREAD

**Issue by fukemy** [kmagiera/react-native-gesture-handler#2745]
### Description

If the flatlist cell contain `Swipeable` => `fullScreenGestureEnabled` not working

### Steps to reproduce

1. make sure add `fullScreenGestureEnabled` to Stack:
   ``` <Stack.Navigator screenOptions={{
        fullScreenGestureEnabled: true
    }}> ... </>
    ```
2. Using FlatList with `<Swipeable>` => `fullScreenGestureEnabled` not working 

### Snack or a link to a repository

https://snack.expo.io/

### Gesture Handler version

2.9.0

### React Native version

0.72.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @fukemy! Please provide a reproduction that we can look at.

**Comment by helenaford** [comment]
```
   dragOffsetFromLeftEdge={onSwipeableOpen ? 0 : 60}
   onSwipeableOpen={() => {
      setOnSwipeableOpen(true);
    }}
    onSwipeableClose={() => setOnSwipeableOpen(false)}
```
      
this is what i've done, if it's helpful for anyone. I needed to be able to disable the left back behviour if the swipable item is open, but also have the navigation back gesture working too.
