### ISSUE TITLE
How the child view intercepts the parent view event

### ISSUE THREAD

**Issue by xpbtmusic** [kmagiera/react-native-gesture-handler#276]
hi，I use tab and webview, I use disallowInterruption=true to intercept the event, but I can't intercept the event of the child view webview, the parent view still has a response, the tab is still conflicting.

**Comment by xpbtmusic** [comment]
`   <NativeViewGestureHandler
                hitSlop={20}
                shouldCancelWhenOutside={false}
                shouldActivateOnStart={true}
                disallowInterruption={true}>
            <WebView
                ref={w => this.webView = w}
                source={uri}
                scrollEnabled={this.props.interceptTouchEvent}
                javaScriptEnabled={true}
                scalesPageToFit={Platform.OS !== 'ios'}
                domStorageEnabled={true}
                onLoad={this.onLoad}
                onMessage={event => this.props.onMessage ? this.props.onMessage(event.nativeEvent.data) : null}
            />
            </NativeViewGestureHandler>`

**Comment by xpbtmusic** [comment]
`   <NativeViewGestureHandler
                hitSlop={20}
                shouldCancelWhenOutside={false}
                shouldActivateOnStart={true}
                disallowInterruption={true}>
            <WebView
                ref={w => this.webView = w}
                source={uri}
                scrollEnabled={this.props.interceptTouchEvent}
                javaScriptEnabled={true}
                scalesPageToFit={Platform.OS !== 'ios'}
                domStorageEnabled={true}
                onLoad={this.onLoad}
                onMessage={event => this.props.onMessage ? this.props.onMessage(event.nativeEvent.data) : null}
            />
            </NativeViewGestureHandler>`

**Comment by xpbtmusic** [comment]
`<NativeViewGestureHandler
                hitSlop={20}
                shouldCancelWhenOutside={false}
                shouldActivateOnStart={true}
                disallowInterruption={true}>
            <WebView
                ref={w => this.webView = w}
                source={uri}
                scrollEnabled={this.props.interceptTouchEvent}
                javaScriptEnabled={true}
                scalesPageToFit={Platform.OS !== 'ios'}
                domStorageEnabled={true}
                onLoad={this.onLoad}
                onMessage={event => this.props.onMessage ? this.props.onMessage(event.nativeEvent.data) : null}
            />
            </NativeViewGestureHandler>`

**Comment by osdnk** [comment]
Hi, @xpbtmusic 
I suppose it's a very edge case and singe WebView is no longer part of RN, I'm afraid we're not really into supporting it. We will keep it tracked in our backlock, but I'm going to close this issue.
Now I propose you to use some transparent view and render webview beneath this view in order to handle your case
