### ISSUE TITLE
Long press doesn't work as expected on iOS

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#28]
Expected: once min duration is met, it should become active.
Actual iOS: only becomes active after min duration is met and touch is released
Actual Android: same as expected

**Comment by kmagiera** [comment]
I think that's actually an issue with simulator only. I think that long press recognizer under the hood works in response to touch event stream that may be paused when you hold your mouse on the button in simulator. Whereas with the real devices there are always some subtle differences even if you try to hold the finger still so new events would arrive. I noticed it some time ago. You don't actually need to lift the finger, it is sufficient to hold it for a while and then slightly move and the dialog will pop up. I also tested that it works flawlessly on device. On top of that I verified that it's UILongPressGestureRecognizer not calling action handler until there is some (even unnoticeable small) movement

**Comment by kmagiera** [comment]
This may be related: http://markmail.org/message/ij2y4qmax6squ5dd

**Comment by kmagiera** [comment]
It also works fine if you use a touchpad instead of a mouse.

@brentvatne do you hit this problem on device or simulator?

**Comment by kmagiera** [comment]
@brentvatne I wonder is the scroll + cancel event issue was maybe related to this bug report. When you have time can you check if you still encounter this after the fix has landed?

**Comment by kmagiera** [comment]
Seems I finally figured out what was wrong with longpress: https://github.com/kmagiera/react-native-gesture-handler/commit/86ef72ac8797980888bc8d414529da12da5d993a#diff-b16682bd3eb1da07c1f0a38594edb354R37

Closing this
