### ISSUE TITLE
PanGestureHandler: Cannot dynamically change minOffsetX/minDeltaX from defined to undefined

### ISSUE THREAD

**Issue by jarrx** [kmagiera/react-native-gesture-handler#280]
I have a use case where I first only want to be able to drag the finger from right to left, but when that  is done (rightButtonsAreaIsOpen === true in code below) I want to be able to drag both left and right.

My initial thought was to do something like
```
<PanGestureHandler
        minOffsetX={rightButtonsAreaIsOpen ? undefined : -10}
        minDeltaX={rightButtonsAreaIsOpen ? 10 : undefined}
        onGestureEvent={this.onGestureEvent}
        onHandlerStateChange={this.onPanHandlerStateChange}
      >
```
But with this solution, once the minDeltaX has gone from being undefined to 10, it won't go back to undefined, i.e. you will be able to scroll both directions even though rightButtonsAreaIsOpen === false.

I solved this by nestling two PanGestureHandlers
```
<PanGestureHandler
        enabled={!this.state.rightButtonsAreaIsOpen}
        minOffsetX={-10}
        onGestureEvent={this.onGestureEvent}
        onHandlerStateChange={this.onPanHandlerStateChange}
      >
        <PanGestureHandler
          enabled={this.state.rightButtonsAreaIsOpen}
          minDeltaX={10}
          onGestureEvent={this.onGestureEvent}
          onHandlerStateChange={this.onPanHandlerStateChange}
        >
          {....}
        </PanGestureHandler>
      </PanGestureHandler>
```

This works but the thing is that you can dynamically change minOffsetX/minDeltaX to different values, but not from a value to undefined.
E.g. `minOffsetX={this.state.rightButtonsAreaIsOpen ? -10 : 0}` works as expected.

Is this expected behavior or could this be solved somehow without nestling two gesture handlers?

```
"react": "^16.4.1",
"react-native": "^0.55.4",
"react-native-gesture-handler": "^1.0.7",
```

**Comment by osdnk** [comment]
This API is obsolete and no longer supported. Please use `failOffset` and `activeOffset`. If you still face the problem, please let us know 😃
