### ISSUE TITLE
FlingGestureHandler 

### ISSUE THREAD

**Issue by gorge2004** [kmagiera/react-native-gesture-handler#286]
It is no work . It is my code 
mi codigo es el siguiente

import {FlingGestureHandler, Directions, State} from 'react-native-gesture-handler'; import {AppRegistry, Dimensions, StyleSheet,TouchableOpacity,View} from 'react-native'; export default class App extends React.Component { constructor(props){ super(props); } render() { return (<View> <FlingGestureHandler direction={Directions.RIGHT} onHandlerStateChange={({ nativeEvent }) => { if (nativeEvent.state === State.ACTIVE) { Alert.alert("I'm flinged!"); } }}> <View style={{flex:1}} > <Text>Textoooo</Text> </View> </FlingGestureHandler>

); }}

And it thows:
Undefined object(evaluating _reactNativeGestureHandler.Directions.RIGHT)
[
![screenshot_2018-09-09-14-13-40](https://user-images.githubusercontent.com/20888572/45267858-3e3fa600-b442-11e8-9c83-23a5c9c3acc3.png)

**Comment by osdnk** [comment]
Hi, @gorge2004!
Thank you very much for your issue. Could you attach id of RNGH version? Are you using expo?
Please attach result of `console.log(Directions)`

**Comment by osdnk** [comment]
Hi, @gorge2004 
I tried to repro with: 
```
import React from 'react';
import { View, Alert, Text} from 'react-native';
import {FlingGestureHandler, Directions, State} from 'react-native-gesture-handler';
export default class App extends React.Component {


  render() {
    console.log(Directions);

    return (<View>
        <FlingGestureHandler
          direction={Directions.RIGHT}
          onHandlerStateChange={({ nativeEvent }) => {
            if (nativeEvent.state === State.ACTIVE) {
              Alert.alert("I'm flinged!");
            }
          }}>
          <View style={{flex:1}} >
            <View style={{width: 100, height: 100, backgroundColor: 'red'}}>
            <Text>Textoooo</Text>
          </View>
          </View>
        </FlingGestureHandler>
      </View>

    );
  }
}
```

```
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3"
```
with newest RNGH

I didn't manage to reproduce. If you still face the problem, let us know 😄
