### ISSUE TITLE
Unify PanGestureHandler activation/cancel criteria

### ISSUE THREAD

**Issue by kmagiera** [kmagiera/react-native-gesture-handler#289]
We now can set a range for when gesture can be activated (have `minOffsetY` and `minDeltaY`) but the criteria for cancelling can only be specified as a delta (that is we can only have symmetrical range in both directions using `maxDeltaY`)

The usecase for that would be when we want to have PanGestureHandler that can activate after pulling down 20 pts but immediately cancel when pulling up. Then if we have another handler waiting for that Pan we have to cancel instead of staying idle while pulling up.

I think the improvement we may try to make is to change the set of parameters on the native side to accept "minOffsetRangeStart" and "minOffsetRangeEnd" for both X and Y and then also have "maxOffsetRangeStart" and "maxOffsetRangeEnd" for both X and Y. Then we can use these to implement "minDelta", "minOffset" and "maxDelta" for compatibility (of course some mix of these props will not be supported)

**Comment by osdnk** [comment]
@kmagiera 
To make it clear. You mean `failing` by `canceling`?

**Comment by kmagiera** [comment]
This has been addressed with one of the recently merged PRs
