### ISSUE TITLE
[ios] Xcode reports nullability warnings

### ISSUE THREAD

**Issue by ide** [kmagiera/react-native-gesture-handler#29]
Xcode asks for some nullability annotations:

<img width="276" alt="warn" src="https://user-images.githubusercontent.com/379606/30523977-38bb1798-9bb9-11e7-80ea-1e7a560c3762.png">

**Comment by kmagiera** [comment]
thanks, I will look into that

**Comment by kmagiera** [comment]
Closing with d696474dfe55d65f6b62f91e8ef92f56490f3c26
