### ISSUE TITLE
onPress just do not works on Component Buttons

### ISSUE THREAD

**Issue by fabiancarlos** [kmagiera/react-native-gesture-handler#291]
I configurate everything, but when i use `BaseButton`, `RectButton` or `BorderlessButton`, they dont fire the `onPress` method. Rly strange i tap and they animate.

What could be the cause?

RN: 0.51.0
React: 16.0.0

**Comment by vlkosinov** [comment]
Did you miss this install step?
https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

**Comment by fabiancarlos** [comment]
Yes, onPress just not works, dont trigger any error, nothing... rly strange, ia have see on another issue closed here, thar in some versions of RN dont work... so i dont know why.

**Comment by vlkosinov** [comment]
Please try to install this lib in empty project produced by “react-native
init”

**Comment by osdnk** [comment]
This issue appears to be inactive, so I'm to close it. If you still face your problem, please let us know immediately, but I'm afraid you should attach some code in order to reproduce your case.

**Comment by luoyushouchai** [comment]
@osdnk @vlkosinov  RectButton triggers onPress if used in FlatList renderItem, but not in SectionList renderItem!  Test in Android platform , not sure in ios platform!

**Comment by Ashkan-Oliaie** [comment]
the RectButton and BaseButton are not triggering onPress for me neither

**Comment by afshawnlotfi** [comment]
Same not working

**Comment by luogao** [comment]
Same for me
Strange

**Comment by AlexHooperDev** [comment]
bump
