### ISSUE TITLE
Custom activation criteria for PanGestureHandler based on absolute x and y

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#293]
It would be useful to immediately fail to recognize a gesture if the x or y is greater than or less than some given threshold. For example, if I want to have a gesture recognizer that detects when the user swipes on the edge of the screen, I know that if the initial x is greater than 40, let's say, then they are not swiping at the edge and we can fail to recognize.

**Comment by brentvatne** [comment]
It's possible to solve this using `hitSlop` although on iOS there appears to be a bug - if you use `hitSlop={{ left: 0, width: 20 }}` then the right 20 points of the view will be the only touchable part, but if you change it to `right: 0` then it will do what you expect. I also couldn't get `{{ top: 0, height: 20 }}` to work, I didn't investigate that one too much. Negative hitSlop works as expected though - so `hitSlop={{ right: -355 }}` would make only the 20 pts on the left of the view touchable, assuming the view is 375 pts wide.

**Comment by kmagiera** [comment]
Closing as of 052f34f025da215874c40d93deb761fb2820ca8e
