### ISSUE TITLE
PanGestureHandler does not cancel when outside.

### ISSUE THREAD

**Issue by wmcbain** [kmagiera/react-native-gesture-handler#30]
Hey there, love what this project is trying to accomplish and I was hoping that it could assist with an use case in our app. What we have is a scroll view with a nested view that responds to both tap and pan gestures. Once activated with tap or pan we want the view to cancel the gesture and make the ScrollView the responder.

I've found that `shouldCancelWhenOutside` doesn't work with `PanGestureHandler`. I have [an example project here](https://github.com/wmcbain/gesture-handler-pan-issue-example/blob/master/main.js) that shows the issue. Is this expected? Related gif below as well.

Thanks for your help and appreciate the work you're doing. 👍🏻

![example](https://media.giphy.com/media/mHcnKEQZQPcME/giphy.gif)

**Edit:** Jumped into the source code and did a bit of debugging and I think I could handle the PR for this if that's alright. :smile:

**Comment by kmagiera** [comment]
Thanks @wmcbain for your report. Would be awesome if you could send the PR, and even better if you could verify it works on both platforms. Thanks so much!

**Comment by wmcbain** [comment]
@kmagiera I'll jump on it this weekend and will be in touch if I run into any issues 👍
