### ISSUE TITLE
Require cycle warnings.

### ISSUE THREAD

**Issue by dsznajder** [kmagiera/react-native-gesture-handler#300]
With new metro and RN 0.57, new warnings appear with `Require cycle warnings`.

Warning: 
```
Require cycle: node_modules/react-native-gesture-handler/GestureHandler.js -> node_modules/react-native-gesture-handler/Swipeable.js -> node_modules/react-native-gesture-handler/GestureHandler.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

Where this happens:
- [x] [GestureHandler](https://github.com/kmagiera/react-native-gesture-handler/blob/master/GestureHandler.js#L25)
- [x] [Swipeable](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js)
- [x] [DrawerLayout](https://github.com/kmagiera/react-native-gesture-handler/blob/master/DrawerLayout.js)

**Comment by kmagiera** [comment]
Thanks for reporting @dsznajder we will look into it some time this week

**Comment by todorone** [comment]
@dsznajder @kmagiera It's not related to RNGH, but it's more Metro-related issue, will be sorted out if this issue will be resolved - https://github.com/facebook/metro/issues/287

**Comment by dsznajder** [comment]
Closed by #323

**Comment by StevenMyers32** [comment]
FYI, with v1.0.9 I'm still seeing some require cycle warnings:
```
Require cycle: node_modules/react-native-gesture-handler/index.js -> node_modules/react-native-gesture-handler/Swipeable.js -> node_modules/react-native-gesture-handler/index.js
require.js:109
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/react-native-gesture-handler/index.js -> node_modules/react-native-gesture-handler/DrawerLayout.js -> node_modules/react-native-gesture-handler/index.js
require.js:109
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle
```

**Comment by dsznajder** [comment]
@kmagiera Should I reopen this issue to track those leave it to `metro`?

**Comment by kmagiera** [comment]
Yes. I'm reopening this issue. We should perhaps change imports in DrawerLayout and Swipeable to load from `./GestureHandler` module instead of using `react-native-gesture-handler`. Anyone would like to submit a PR?

**Comment by dsznajder** [comment]
I hope I will find time this week and do it :) 

If someone would like to handle this, just take it.

**Comment by kmagiera** [comment]
Just published 1.0.10 -> https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.0.10

**Comment by edmundojr** [comment]
Hey guys! I'm still seeing the warnings on `1.0.12`.

**Comment by ujwal-setlur** [comment]
Me too. Using RNGH-1.0.12, RN-0.57.8

**Comment by ujwal-setlur** [comment]
In DrawerLayout.js, I see:

```js
import {
  PanGestureHandler,
  TapGestureHandler,
  State,
} from 'react-native-gesture-handler';
```

So it looks like something reverted the change there...

**Comment by ujwal-setlur** [comment]
Changing the import code in DrawerLayout.js back to:

```js
import {
  PanGestureHandler,
  TapGestureHandler,
  State,
} from './GestureHandler';
```

resolves the problem

**Comment by darkrift** [comment]
This commit actually reverted the changes for the import ... https://github.com/kmagiera/react-native-gesture-handler/commit/48b66807c3577b99859f9aee9394105cf722f535

**Comment by darkrift** [comment]
@brentvatne @kmagiera Can you guys check the import regression ?
