### ISSUE TITLE
Is there a "onMoveShouldSetPanResponder" ?

### ISSUE THREAD

**Issue by nazarTrynko** [kmagiera/react-native-gesture-handler#31]
Hi! Is it possible to conditionally set handler like in PanResponder's onMoveShouldSetPanResponder method? I need it to catch swipe down, but not catch swipe up

**Comment by kmagiera** [comment]
Hi @nazarTrynko thanks for reaching out!

Gesture handler is quite different from PanResponder as far as the functionality you're looking for. As opposed to defining a method you can adjust the behaviour by using declarative API (just setting some props on handler objects).

In your case specifically you should use `PanGestureHandler` component. If you only want to trigger when pulled down you should set `minOffsetY` property to some positive value. 

For example setting `minOffsetY={10}` will make it activate only when pulled down by 10px (not actually pixels but units that are used by RN core for defining sizes etc). The above will make your handler triggered when someone puts the finger down and cumulatively dragged it down by 10px. Note that if they pull it up by 40px and then down by 50px it would also trigger. So if you'd like to avoid that you can additionally set `maxDeltaY={11}`, this will make the handler fail immediately if  pulled up by at least 11px, this won't affect pulling down as the handler would activate sooner (at 10px). You can also do the same for X axis if you don't want your component to trigger when pulling to the left or right (by setting `maxDeltaX`)


Below is the list of all the options you can use with `PanGestureHandler`:
 - minDeltaX
 - minDeltaY
 - maxDeltaX
 - maxDeltaY
 - minOffsetX
 - minOffsetY
 - minDist
 - minVelocity
 - minVelocityX
 - minVelocityY
 - minPointers
 - maxPointers

I hope this answers your question, so I'm going to close this issue. In case it doesn't feel free to reopen and we can discuss it here further
