### ISSUE TITLE
Unhandled JS Exception: undefined is not an object (evaluating 'RNGestureHandlerModule.State')

### ISSUE THREAD

**Issue by gao520sun** [kmagiera/react-native-gesture-handler#313]
Unhandled JS Exception: undefined is not an object (evaluating 'RNGestureHandlerModule.State')

"react-native-gesture-handler": "^1.0.8",
![81b021cc-da17-4158-ad89-a1e0968ee3e8](https://user-images.githubusercontent.com/8372369/46935662-6ef0ac00-d08e-11e8-9ead-43ea5f4d0ca6.png)

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

**Comment by tianyewai** [comment]
@gao520sun  How did you solve this problem? o(╯□╰)o

**Comment by luck2011** [comment]
Got the same error today, @gao520sun How did you solve this problem? o(╯□╰)o
