### ISSUE TITLE
LongPress gesture cancellation

### ISSUE THREAD

**Issue by rt2zz** [kmagiera/react-native-gesture-handler#316]
On Android, when a long press is activated, and the user then pans away (without lifting the gesture) the LongPressGestureHandler enters a cancelled state.

in iOS the gesture does not cancel and continues to fire gesture events until the gesture is released by lifting the finger.

This comment seems to suggest that the iOS behavior is intended and that android has a bug: https://github.com/kmagiera/react-native-gesture-handler/issues/94#issuecomment-355750006

The bug prevents (afaict) the feature I am working on from being possible in RNGH: activate a chart scrubber upon long press.

**Comment by jeanregisser** [comment]
I'm affected by this bug as well.

Did you find any workaround @rt2zz?

**Comment by rt2zz** [comment]
I have not, I suspect this could be achieved with PanGestureHandler with simultaneous handlers setup, but there were some implementation challenges I ran into and am not sure what a solution would look like.

**Comment by lvmtam** [comment]
I also have the same issue. Seem to be strange.

**Comment by rt2zz** [comment]
found the issue, on android `maxDist` defaults to a small value thus cancelling the gesture after a short pan. Set that to screen width, or whatever makes sense for your component to fix this issue.

Not sure why the iOS behavior does not match?
