### ISSUE TITLE
Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by isthaison** [kmagiera/react-native-gesture-handler#325]
![image](https://user-images.githubusercontent.com/22739578/47599549-d7b71d00-d9da-11e8-87b2-fe2f49484c7c.png)
![image](https://user-images.githubusercontent.com/22739578/47599683-39788680-d9dd-11e8-91ed-f13586343465.png)

**Comment by stan-sack** [comment]
If you want to render an array of elements you need to assign each a key to assist in the reconciliation process: https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by osdnk** [comment]
This issue appears to inactive
