### ISSUE TITLE
"The value '5e-324' could not be represented as a 'double' due to overflow" when using Swipeable

### ISSUE THREAD

**Issue by latir** [kmagiera/react-native-gesture-handler#326]
When running my RN project in Remote JS Debugging mode I get the following error:

`The value '5e-324' could not be represented as a 'double' due to overflow`

Occurs anytime I'm trying to use Swipeable

<img width="355" alt="screen shot 2018-10-29 at 11 11 22" src="https://user-images.githubusercontent.com/21192827/47646510-057f9b80-db6c-11e8-80c7-69f2eb85e167.png">

```
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-gesture-handler": "^1.0.8",
    "react-native-navigation": "1.1.483",
```

**Comment by latircoleetti** [comment]
Any word on this?
