### ISSUE TITLE
Support hitSlop on Android buttons

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#328]
Thanks to @janicduplessis this is [supported on iOS](https://github.com/kmagiera/react-native-gesture-handler/pull/283), it'd be useful to have on Android as well.

**Comment by danieljennings** [comment]
Issue #283 mentions in the opening paragraph that "Android already has support for it." Is that not correct?

**Comment by brentvatne** [comment]
as far as I can tell no https://github.com/kmagiera/react-native-gesture-handler/blob/master/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java

**Comment by osdnk** [comment]
I doesn't look like support 🤔

**Comment by osdnk** [comment]
Heh, support is provided with `NativeViewGestureHandler`  😅

**Comment by brentvatne** [comment]
interesting! thanks

**Comment by brentvatne** [comment]
looks like on master that doesn't work anymore, and when i tried it on 1.0.15 it would increase the touch area as expected but onPress for the RectButton wrapped by NativeViewGestureHandler didn't fire

**Comment by Guuz** [comment]
@kmagiera @jakub-gonet @sakshya73 It's unclear, to me at least, if Android supports hitslop on buttons (BorderlessButton for instance). I can't get it to work. But perhaps i'm doing something wrong... But the docs nor the issues on github seem to be conclusive about if support is actually there...
Any insight into this would be very helpful!
