### ISSUE TITLE
[Android] RectButton borderWidth not working

### ISSUE THREAD

**Issue by diegolmello** [kmagiera/react-native-gesture-handler#333]
Hey, guys.
I'm using RectButton and borderWidth works on iOS, but not on Android.

iOS and Android:
![untitled-1](https://user-images.githubusercontent.com/804994/48275336-617bd700-e42c-11e8-8133-8846294bb68d.png)

This can be achieved with this code:
```jsx
<RectButton
	onPress={onPress}
	style={{
		width: '100%',
		height: 48,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 15,
		borderRadius: 2,
		borderWidth: 1,
		borderColor: '#e1e5e8',
		marginBottom: 10
	}}
>
	<Image source={{ uri: icon }} style={styles.serviceIcon} />
	<Text style={styles.serviceText}>Continue with <Text style={styles.serviceName}>{name}</Text></Text>
</RectButton>
```
_Look how we use a single style_

### Workaround
The obvious workaround is to add a View inside of RectButton and apply borderWidth, but it adds unnecessary complexity into the code :(

Android with View:
![device-2018-11-09-142353](https://user-images.githubusercontent.com/804994/48275439-a56edc00-e42c-11e8-9ce9-55e7e7a38cf6.png)

Code for the workaround:
```jsx
<RectButton onPress={onPress} style={{ borderRadius: 2, marginBottom: 10 }}>
	<View style={{ borderRadius: 2, borderWidth: 1, borderColor: '#e1e5e8', width: '100%', height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 15,}}>
		<Image source={{ uri: icon }} style={styles.serviceIcon} />
		<Text style={styles.serviceText}>Continue with <Text style={styles.serviceName}>{name}</Text></Text>
	</View>
</RectButton>
```
_Look how we need to work with two styles and add an inner View_
_Also, we need to set borderRadius in both because of onPress_

Thanks and let me know if I can help with something! 👊

**Comment by ckknight** [comment]
This applies to all buttons, including `RawButton`.

**Comment by osdnk** [comment]
We agree that this is an issue. 
However, we do not intent to clone all layout logic for RN's View in our buttons. We added some basic and most important features (like `borderRadius`) which are required for proper working of native feedback, but I believe there's no point to handle every case when it's possible simply to wrap `View` with this button. I advise you not to hesitate with using RNGH's buttons as wrapper for more complex styled components.
