### ISSUE TITLE
Android build fails with RN 0.57.5

### ISSUE THREAD

**Issue by kevindoole** [kmagiera/react-native-gesture-handler#347]
Hey there,

`react-native run-android` fails with the current stable version of react-native (0.57.5) with the error:
```
* What went wrong:
A problem occurred configuring project ':react-native-gesture-handler'.
> Failed to find target with hash string 'android-25' in: /my/path/Library/Android/sdk
```

To reproduce:
- `react-native init whatever`
- proceed through react-native-gesture-handler installation steps
- `react-native run-android`

Thanks!

**Comment by kevindoole** [comment]
(i would provide a fix, but i'm a complete noob with android 🤤)

**Comment by kevindoole** [comment]
Sweet, thanks!

**Comment by osdnk** [comment]
https://github.com/kmagiera/react-native-gesture-handler/pull/377
also in order to bump your app please follow
