### ISSUE TITLE
Lack of testID prop to test it by detox. Documentation + Example

### ISSUE THREAD

**Issue by dsznajder** [kmagiera/react-native-gesture-handler#353]
Hi, this library is great and I'm using nearly everything from it together with `react-native-reanimated` but I'm stuck at some point to test it with [detox](https://github.com/wix/detox). 

I've tried to find GestureHandler Nodes inside but I failed. 

P.S. It's more like question / feature request.

**Comment by MajronMan** [comment]
Hi, you should check out my pull request: https://github.com/kmagiera/react-native-gesture-handler/pull/304 
As for now, there are only trivial tests, but there is fully configured and working test app.

**Comment by osdnk** [comment]
@dsznajder 
Well, the main point is that Handlers are not real component and are not represented by any node. https://github.com/kmagiera/react-native-gesture-handler/blob/master/GestureHandler.js#L356
So the id's passed to GH's don't change anything. Well, we hope to take a deeper look on detox' tests in the nearest future.

**Comment by enzomanuelmangano** [comment]
Since there is no testID, is there any way to test a TapGestureHandler without the simulator?
