### ISSUE TITLE
Multiple commands produce `.../libRNGestureHandler.a`

### ISSUE THREAD

**Issue by zknowles** [kmagiera/react-native-gesture-handler#370]
I've been having issues with using this package in my React Native app. After putting in a Podfile command to fix [this issue](https://github.com/kmagiera/react-native-gesture-handler/issues/179), I was able to get my app running in my iOS simulator with the package installed. However, I've tried many times to pass it through CI (using Bitrise) and I get the following error each time:

```error: Multiple commands produce '/Users/vagrant/Library/Developer/Xcode/DerivedData/sbook-dirdylnvgyvrdqeanixrtpxfsivb/Build/Intermediates.noindex/ArchiveIntermediates/sbook/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libRNGestureHandler.a'```

I googled many other solutions to this problem and none of what I have found works. I would really appreciate help with this in order to upgrade to `react-navigation-v3` in my app!

**Comment by zknowles** [comment]
I fixed my issue. I needed to add a flag in my CI settings to stop using the Xcode modern build system.

**Comment by mfbx9da4** [comment]
@zknowles  it's probably a configuration issue - the new build system is [better at catching these](https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce) configuration issues. Switching to legacy build system sounds like a hack. Is there an official solution?

**Comment by mfbx9da4** [comment]
My issue was that I had two references `GoogleService-Info.plist` in the project / file view. The correct location is in the project root. This error generally means, duplicate configuration.
