### ISSUE TITLE
Force/3D Touch Support

### ISSUE THREAD

**Issue by bhandarijiwan** [kmagiera/react-native-gesture-handler#373]
Even though it hasn't been documented much, react native provides `force` values in the nativeEvent for platforms that support force/3D touch. I was wondering if it was possible get the `force` value with this library ? I am trying to implement a force activated `LongPressHandler` to get a very simple peek and preview interaction ?

**Comment by osdnk** [comment]
`ForceTouchGestureHandler` incoming :3
