### ISSUE TITLE
maxDeltaY={N} is not replaceable with failOffsetY={[-N, N]}

### ISSUE THREAD

**Issue by spacesuitdiver** [kmagiera/react-native-gesture-handler#375]
I am trying to use the BottomSheet example as a reference point for my code to make a drawer which delegates to a native scrollview and despite the documentation saying that I can use `failOffsetY` instead of `maxDeltaY` it simply doesn't work.

https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/bottomSheet/index.js#L103

**Comment by osdnk** [comment]
Hi, @spacesuitdiver 
You've confused docs of `PanGestureHandler` and `TapGestureHandler` :)

**Comment by zachgibson** [comment]
@osdnk I’m confused. `PanGestureHandler ` [documents `failOffsetY `](https://kmagiera.github.io/react-native-gesture-handler/docs/handler-pan.html#failoffsety) as a property?

**Comment by osdnk** [comment]
Yes and you link to tap :)

**Comment by zachgibson** [comment]
My link links to handler-pan not handler-tap `/handler-pan.html#failoffsety`.

**Comment by osdnk** [comment]
Yes, but we used tap in example
