### ISSUE TITLE
activeOffsetX seems to apply to up/down (Y) movements

### ISSUE THREAD

**Issue by spacesuitdiver** [kmagiera/react-native-gesture-handler#376]
I think this is a bug?

**Comment by spacesuitdiver** [comment]
Same issue exists with `minOffsetX`. My use case is allowing for the PanResponder not to interact with X gestures as I have drawers in my app on both sides.

**Comment by osdnk** [comment]
Hi, @spacesuitdiver 
Thanks for the issue. I checked and everything appears to be workable. `activeOffsetX` block handler from changing its state to `active` until travelling given movement defined by range.

**Comment by spacesuitdiver** [comment]
@osdnk I see how it works now, sorry for the ticket. I'm going to spend some time writing up a ticket to basically mimic the "BottomSheet" (https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/bottomSheet/index.js). This example is a bit buggy so I'm seeing what we might need to keep everything on the opposite side of the bridge.

**Comment by flyinghawker** [comment]
regarding bottomsheet, `react-native-interactable` has a perfectly smooth example (MapPanel.js),  good to try.
