### ISSUE TITLE
IOS build failed 'Undefined symbols for architecture x86_64'

### ISSUE THREAD

**Issue by sliultron** [kmagiera/react-native-gesture-handler#387]
Updated React-Navigation to 3.0.8 and followed the instruction to install the react-native-gesture-handler.
after `react-native link react-native-gesture-handler`
i got error when building with `react-native run-ios` or building in the xCode.
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNForceTouchHandler", referenced from:

      objc-class-ref in libRNGestureHandler.a(RNGestureHandlerManager.o)

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

i am using following packages:
```
  "react-native": "0.57.3",
    "react-native-gesture-handler": "1.0.12",
    "react-navigation": "3.0.8"
```
How do i fix this?  Please help.
Appreciate :)

**Comment by osdnk** [comment]
Hi, @sliultron 
Try changing 'Build System' to 'Legacy Build System'. I've just made fresh app with `react-native init` and then linked RNGH and it appears to work fine.

**Comment by simonbengtsson** [comment]
Downgrading to `"react-native-gesture-handler": "1.0.10"` works for us.

**Comment by sliultron** [comment]
@osdnk 
finally got project compiled in xcode with a clean build. 
I have to run this first. 
```
rm -rf ~/Library/Developer/Xcode/DerivedData/*
``` 
Then building is ok.

However, running react-native run-ios still give me that error. Wondering if that is caused by npm cache?

**Comment by osdnk** [comment]
Hm, I wouldn't guess it's npm cache.

**Comment by DLlzw** [comment]
> react-native-gesture-handler": "1.0.10

I uset it solve

**Comment by osdnk** [comment]
I strongly advise you y to use the newest version since I suppose it's only matter of cache.

**Comment by huangdou0204** [comment]
> I strongly advise you to use the newest version since I suppose it's only matter of cache.

RN build  cache and xcode build cache is different  directory, so xcode build success, RN build fail

**Comment by arthurzeras** [comment]
I changed iOS Deployment Target from 8.0 to 9.0 in RNGestureHandler.xcodeproj and solved for me

**Comment by timmywil** [comment]
Cleaning the project and removing derived data doesn't do it for me. Seems to be more than a cache issue. Downgrading for now until the regression is fixed. I don't think using the Legacy Build System is a viable long-term solution. `1.0.10` seems to be fine. My guess is it has to do with https://github.com/kmagiera/react-native-gesture-handler/commit/8f0b33f5e93fe71b968da3a51c2f6d91a0f91996

**Comment by obsidianart** [comment]
@osdnk 
1.0.15 fails for me too, I cleaned every possible cache "rm -rf $TMPDIR/react-* && rm -rf ~/Library/Developer/Xcode/DerivedData/* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && yarn install"

**Comment by nidzola** [comment]
I was getting the same issue, but after next steps I got it resolved:

1. Close the Metro bundler
2. `rm -rf ~/Library/Developer/Xcode/DerivedData/*`
2. Product -> Clean Build Folder
3. Build from xcode

I've managed to compile and run the build with the latest `1.0.15` version, both on device and emulator.

```
"react-native": "0.57.7"
"react-native-gesture-handler": "1.0.15"
```

**Comment by sliultron** [comment]
@nidzola this works for me as well. thx

**Comment by raulghm** [comment]
In my case, after cleaning eveything and install dependencies, I changed target to 10.0 

Like https://github.com/kmagiera/react-native-gesture-handler/issues/387#issuecomment-449424335

**Comment by Biplovkumar** [comment]
> @osdnk
> finally got project compiled in xcode with a clean build.
> I have to run this first.
> 
> ```
> rm -rf ~/Library/Developer/Xcode/DerivedData/*
> ```
> 
> Then building is ok.
> 
> However, running react-native run-ios still give me that error. Wondering if that is caused by npm cache?

thanks

**Comment by huy-lv** [comment]
I got the same error, i update to latest version `"react-native-gesture-handler": "1.10.1"` and everything work fine :D
