### ISSUE TITLE
Swipeable, DrawerLayout not included in build

### ISSUE THREAD

**Issue by jpaas** [kmagiera/react-native-gesture-handler#40]
The last bunch of npm builds including 1.0.0-alpha.26 are missing the Swipeable.js and DrawerLayout.js files.

**Comment by kmagiera** [comment]
Thanks for reporting @jpaas 
This got fixed here https://github.com/kmagiera/react-native-gesture-handler/pull/39 and I released alpha.27 with the missing components included
