### ISSUE TITLE
[Swipeable] Overflow hidden limits usability

### ISSUE THREAD

**Issue by tedcurrent** [kmagiera/react-native-gesture-handler#403]
A Swipeable component not full width clips on swipe. This is due to
```
container: {
    overflow: 'hidden'
  },
```

Can we have a style prop for managing the `Animated.View` that wraps the children?

If this breaks something, I'm open for suggestions. Full width is not really an option.

**Comment by roydigerhund** [comment]
I'm currently having the same issue. A card that isn't fullwidth and get's cropped on swipe due to the `overflow: 'hidden'` style settings. 

A `containerStyle` would help, or omit `overflow: 'hidden'` completely, I haven't experienced issues without this style.

**Comment by osdnk** [comment]
🎉
