### ISSUE TITLE
Warning: bind(): You are binding a component method...

### ISSUE THREAD

**Issue by dsznajder** [kmagiera/react-native-gesture-handler#421]
![image](https://user-images.githubusercontent.com/17621507/51683270-bff73100-1fe9-11e9-800f-b2ed84783ac1.png)

Affected Version: `1.0.14`

This [line](https://github.com/kmagiera/react-native-gesture-handler/blob/eef7fff9c4f3ec45cabb09defb871989615367a6/GestureHandler.js#L675) causing a warning.

**Comment by tannera** [comment]
Yep, can confirm 1.0.14 added this warning. It was not present in 1.0.12.

**Comment by jsamr** [comment]
I bet it's related to RN 0.58, from [their release notes](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#0580):

> Break changes to `ScrollView`, `CameraRollView`, and `SwipeableRow` that make it no longer bound to the component instance in certain methods

So 1.0.14 should have a peer dependency to RN `~0.58`
I'll go for a `1.1.0`, and make  a `1.0.15` with a RN peer dep to `<=0.57`

**Comment by andresmtz98** [comment]
I have this code without any 'bind' method but that warning appears :/

`
const CustomTable = props => (
  <View {...props}>
    <View style={styles.sectionHeader}>
      <Text style={styles.headerTitle}>{props.titulo}</Text>
    </View>
    <Grid style={styles.grid}>
      <Col
        style={styles.col}>
        <Text style={styles.colText}>{props.tituloLeftColumn}</Text>
      </Col>
      <Col
        style={{ ...styles.col, borderRightWidth: 0 }}>
        <Text style={{ ...styles.colText, textAlign: 'right' }}>{props.tituloRightColumn}</Text>
      </Col>
    </Grid>
    <FlatList
      data={props.data}
      style={styles.flatList}      
      renderItem={renderItemList}      
      ListEmptyComponent={
        <Text style={styles.textEmpty}>No hay registros</Text>
      }
    />
  </View>
);
`

**Comment by guveniscan** [comment]
I spent a good 3 hours tracking this issue, it makes the debug logs completely unusable bc warning fires every couple seconds. Pasting the warning so it becomes searchable:

> Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See ScrollView

**Comment by osdnk** [comment]
PR is pending

**Comment by linus** [comment]
Is it customary to close a bug report before there is a fix? I've been wrestling with this (and related expo/react-navigation/react-native-gesture-handler bugs) for the last couple of weeks--I was under the understanding that this had been fixed and was investigating version clashes or strangeness in my project setup. (AFAIK it's impossible to run Expo 32 with react-navigation 3, so that should probably not have been released yet).

**Comment by osdnk** [comment]
I though it will be merged faster. Reopen

**Comment by linus** [comment]
Amazing! Ship it!

**Comment by quarrant** [comment]
I think, you need upgrade npm package 'cause it doesn't include this fix

**Comment by kmagiera** [comment]
hey @linus and @quarrant – I'll be publishing new version in a few days, still waiting for a bunch of other updates to land.

**Comment by somangshu** [comment]
Using ScrollView (or other core components) from react-native core removes the warning for now. Waiting for the pr merge so that the original package can be used. :)

**Comment by shubham6996** [comment]
Just import `ScrollView` from react-native and not react-native-gesture-handler

**Comment by declanelcocks** [comment]
@shubham6996 I can't really do that since I'm using `ScrollView` from other libraries which depend on this lib (e.g. `react-navigation`). I imagine others are too.

**Comment by marcusstenbeck** [comment]
I'm waiting patiently for this fix to be released. :)

**Comment by stevematdavies** [comment]
Still waiting, dont like putting another warning on the yellow box exceptions

**Comment by osdnk** [comment]
Bumped!

**Comment by kmagiera** [comment]
This went out as a part of 1.1.0 release and since 1.1.0 requires RN 0.57.2+ I also cherry-picked the fix and released 1.0.17 with it.
