### ISSUE TITLE
[1.0.14] App stucked

### ISSUE THREAD

**Issue by NichAga** [kmagiera/react-native-gesture-handler#422]
Hi,
I don't have a lot of informations, but updating from 1.0.12 to 1.0.14 made my app unresponsive to touch, only the drawer works.

Just to inform.

**Comment by angly-cat** [comment]
I have the same issue. However, I just tested RNGH 1.0.14 on a blank React Native 0.57.8 project (same versions as in my app), and it didn't reproduce.

**Comment by angly-cat** [comment]
This happens on Android only, iOS isn't affected. Symptoms: RNGH buttons work, and apparently anything else doesn't respond to touches. Like `<TextInput>`s, `<Text onclick={callback}>`s, and even when Inspector is toggled, none of it's buttons (Inspect/Perf/Network/Touchables) works and nothing can be selected at all.

**Comment by waleedsarwar86** [comment]
I have also faced the same issue Button and TextInput not responding on Android

**Comment by hoboman313** [comment]
Same issue after upgrading. No errors or warnings. Everything is just no longer responsive to touch.

**Comment by angly-cat** [comment]
I've reduced my application to just a `TextInput`, and `RectButton` being conditionally rendered. After `RectButton` is rendered once, `TextInput` no longer detects touches, even if `RectButton` is deleted after that.

However, I can't reproduce the issue with the same code within a new blank project.

My guess is that RNGH is conflicting either with some special settings of my app, or with some third-party React Native packages with native code that I use.

**Comment by Freddy03h** [comment]
Same issue after upgrading from 1.0.12 to 1.0.14 on Android
react-native: 0.57.8
react-native-screens: 1.0.0-alpha.22

**Comment by angly-cat** [comment]
I've bisected the issue. This regression come from https://github.com/kmagiera/react-native-gesture-handler/commit/3def2e1d72f8556dd368cb85570f9a4ab00b0fec

**Comment by jiasongs** [comment]
same issue

**Comment by guhungry** [comment]
I also affect too confirm android

**Comment by kmagiera** [comment]
Thanks @angly-cat for investigating this. we will look into this shortly
