### ISSUE TITLE
rippleColor only applies if background isn't transparent

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#425]
Repro: https://snack.expo.io/@notbrent/upbeat-waffle

It's worth noting that it additionally has particularly strange behavior on Snack - without the background color set both ripples will not be red. If you add a background color then they will be red on the one with the background color and grey on the other, but all bets are off for changes you make after that.

In the react-native-gesture-handler example app the buttons with rippleColor have backgrounds and so it's not noticeable.

**Comment by osdnk** [comment]
Thanks
Fixed with https://github.com/kmagiera/react-native-gesture-handler/pull/400
