### ISSUE TITLE
Crash iOS / Android using 1.0.15

### ISSUE THREAD

**Issue by Titozzz** [kmagiera/react-native-gesture-handler#432]
Hello there,

We were updating from 1.0.12, and updated to 1.0.14, it was working fine on iOS and touch event were broken on android #422 , then we updated to 1.0.15 and now app crashes on start for iOS and android. The crash is: 

> Invariant Violation: Could not find "store" in the context of "Connect(v)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(v) in connect options.

Changing my version back to 1.0.12 fixes this issue. I've reviewed the differences between 1.0.14 and 1.0.15 and I'm not sure what would do that 😢 . Maybe something related to the event change that would break redux-offline ?

Just posting this in case you have an idea, please let me know if you need more details. I'll investigate if you need me to !

React-native 0.58.1
RNGH 1.0.15

🚀

**Comment by ujwal-setlur** [comment]
I am using 1.0.15 with RN 0.58.3, and am seeing no crash...

**Comment by osdnk** [comment]
Hello, @Titozzz 
Could you prepare some minimal example?

**Comment by Titozzz** [comment]
I'm still debbuging this, but it does not seem related to RNGH, as bumping another lib created the same issue. I'll close for now.
