### ISSUE TITLE
RectButton borderTopLeftRadius

### ISSUE THREAD

**Issue by Bardiamist** [kmagiera/react-native-gesture-handler#435]
Style props `borderTopRightRadius`, `borderBottomLeftRadius`, `borderBottomRightRadius`, `borderTopLeftRadius` not works for ReactButton.

**Comment by osdnk** [comment]
Hello @Bardiamist 
Yes, it does not work and we're sorry for it. However, I see not point for copying every single prop implementation and and not going to add this specific one.

https://github.com/kmagiera/react-native-gesture-handler/blob/master/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java#L114

It should be regarded as limitation of this library, but it does not mean that you cannot achieve it in another way. Consider wrapping button in another component and then use it for achieving required radii and disable overflowing.
