### ISSUE TITLE
Unsupported top level event type "onGestureHandlerStateChange" dispatched

### ISSUE THREAD

**Issue by musicode** [kmagiera/react-native-gesture-handler#439]
OS: ios
RN version: 0.58.3
RNGH version: 1.0.15

![image](https://user-images.githubusercontent.com/2732303/52047560-349b1400-2584-11e9-9087-4252b11ed507.png)

**Comment by sinhpn92** [comment]
I have same issue with:

```
"react-navigation": "^3.1.0",
"react-native-gesture-handler": "^1.0.15",
```
I did put import 'react-native-gesture-handler' on top of index.js but it's doesn't work :(

**Comment by wbercx** [comment]
Version `1.0.14` does not seem to have this problem.

**Comment by Simek** [comment]
@kmagiera Can we get a status or an update about this issue?

**Comment by kmagiera** [comment]
cc @osdnk

**Comment by Simek** [comment]
I'm experiencing this exception on iOS while navigating back in stack using swipe or back button.

React Navigation users also suffered from this issue and seems that most of them go with downgrade:
https://github.com/react-navigation/react-navigation/issues/5208

It seems that only three comments has been added between `1.0.14` and `1.0.15` and after a bit of research I can tell that changes from commit 35c57a0f4930210c3b152e33e814e97ec1e23d92 (#429) are causing this issue but I'm not sure why.

**Comment by osdnk** [comment]
Hello, could you please assure that you're actually requiring RNGH on very top level of your app. I mean you could add some `console.log` on top of `GestureHandler.js` and then determine whether it's really invoking on App's start.

**Comment by kmagiera** [comment]
Hello all!

Thanks for reporting the issue, however in the future it would be much easier for us to address your problems quicker, if you help us and prepare a small repo that reproduces the problem.

I went ahead to try it and started new project with RN 0.58.4 and GH 1.0.15 (similar setup to what @musicode posted) here https://github.com/kmagiera/GHBug439 – apparently the problem cannot be reproduced there.

It makes sense to try @osdnk suggestion and add the following code to your main javascript file (e.g. usually it is `App.js` file):
```
require('react-native-gesture-handler');
```

Gesture handler lib requires that parts of the library code runs on load time (specifically even registration code that is the reason why you're seeing the crash).

**Comment by osdnk** [comment]
rel https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-463341145

**Comment by osdnk** [comment]
I have testes the newest version with an Example app on `0.58.4` and `0.58.0` version of RN on Android and iOS in release and debug mode as well and still can't observe the problem. I believe it's possible that it breaks in some cases, but I'm seriously not able to reproduce. 

If you consider it as a problem please attach an example with newest version of RN and RNGH and deterministic steps to observe the problem.

**Comment by wbercx** [comment]
For what it's worth, I've just upgraded from RN `0.55.4` to `0.58.6` and no longer seem to have this issue. 

Prior to that, it occurred anytime I used any version of RNGH > `1.0.14`, but only on iOS. Android has always been fine for me.

**Comment by Simek** [comment]
Issue is still occurring with RN `0.58.6` and RNGH `1.0.17` in my iOS app.  Same circumstances as @wbercx mentioned. Also "swipe back"  gesture (swipe from most left edge of display) generates this error for me. Not much changed from last message: https://github.com/kmagiera/react-native-gesture-handler/issues/439#issuecomment-462834883.

**Comment by tikkichan4** [comment]
Just facing the same problem in 0.59.0 when i turn on inlineRequires in metro.config.js which introduced in react native 0.59.0. After i change inlineRequires to false, everything works fine.

But inlineRequires off can causes slower app launches. Looking forward the answer which can turn on inlineRequires without conflicting react-native-gesture-handler.

**Comment by Simek** [comment]
After upgrading to RN `0.59.1` issue still happens in my app, but there is a little bit more information about exception:
<img width="1001" alt="Screenshot 2019-03-21 at 07 07 41" src="https://user-images.githubusercontent.com/719641/54735804-728ddf00-4ba8-11e9-9d0f-c06ded022a00.png">

```
Unsupported top level event type "onGestureHandlerStateChange" dispatched

Object.extractEvents
    ReactNativeRenderer-dev.js:2465:4
extractEvents
    ReactNativeRenderer-dev.js:1022:43
runExtractedEventsInBatch
    ReactNativeRenderer-dev.js:1066:15
<unknown>
    ReactNativeRenderer-dev.js:2707:4
batchedUpdates$1
    ReactNativeRenderer-dev.js:18527:11
batchedUpdates
    ReactNativeRenderer-dev.js:2611:11
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2706:2
Object.receiveEvent
    ReactNativeRenderer-dev.js:2726:2
MessageQueue.__callFunction
    MessageQueue.js:366:41
```

**Comment by nicholasrq** [comment]
same issue as @tikkichan4 on RN 0.59 with `inlineRequires: true`

**Comment by osdnk** [comment]
Close ind in favor of #320 .
