### ISSUE TITLE
Add docs for touchables

### ISSUE THREAD

**Issue by osdnk** [kmagiera/react-native-gesture-handler#441]
I see that there's need to explain deeply motivation and advantages for using RNGH's touchables instead of RN's core ones

**Comment by m1ck2** [comment]
I want to I need to be able to get there somehow was hoping someone can help me get there after charging stuff up. 


Sent from Yahoo Mail for iPhone


On Wednesday, February 27, 2019, 9:50 pm, Michał Osadnik <notifications@github.com> wrote:


Closed #441.
