### ISSUE TITLE
Question: Enable PanGestureHandler after a longpress

### ISSUE THREAD

**Issue by neiker** [kmagiera/react-native-gesture-handler#445]
Hi! Theres a way to wait N time before `PanGestureHandler` is activated? 
I have draggable elements that can be dragged only on two situations:
- Item is selected (previously by a tap). This case is easy using `enabled` flag.
- Item is not selected but the users presshold over it for 300ms

I have tried to archive this the last couple of hours unsuccessfully

https://github.com/neiker/canvas/commit/2c3002e2710e21aade67c32d482155e18d3cf10c#diff-1bb3bfdc3ff1c249a9ee5c9100ac909aR153

On native this can be archived this way: https://stackoverflow.com/questions/30014846/enable-uipangesturerecognizer-when-did-longpress

**Comment by osdnk** [comment]
Close in favor of #434
