### ISSUE TITLE
Swipeable: renderLeftActions "The data couldn't be read because it isn't in the correct format"

### ISSUE THREAD

**Issue by peterpme** [kmagiera/react-native-gesture-handler#46]
Hey,

Awesome module! I'm here to ask about the `Swipeable` component. When adding `renderLeftActions` or `renderRightActions` I get a red box:

```
The data couldn't be read because it isn't in the correct format
```

I've narrowed it down to the ` { translateX: this._leftActionTranslate } ` located here:
https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js#L226

If I set translateX to `this._transX`, it works correctly (it doesn't bounce back all the way but hopefully I'll figure it out soon)

I'm going to keep hunting down the problem and will try to put together a PR. Any hints would be appreciated.

Thanks again for the library!!!!

**Comment by kmagiera** [comment]
Thanks for reporting @peterpme 

Can you share more details on how you get this error? Is that a redbox you're seeing or maybe you found it on the console output? Also is this on iOS or Android or both?

**Comment by peterpme** [comment]
Hey,

- Right now I've only tested it on `iOS`.
- I get the redbox
- *it happens when i'm debugging my app*

https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/f/fa583a711f2b06baa1c5a582d476a6e605ffa11e.png

I originally thought it was an Expo issue:
https://forums.expo.io/t/react-native-gesture-handler-swipeable-data-couldnt-be-read-because-it-isnt-in-the-correct-format/4124/7

**Comment by peterpme** [comment]
Would you think I'm crazy if I told you this only seems to be happening when Chrome debugger is activated?

**Comment by kmagiera** [comment]
Hey @peterpme! Sorry for getting back here so late. Would you be able to provide a more detailed description of this issue? Both `renderLeftActions` and `renderRightActions` are set in the example app and I haven't seen anyone else reporting similar issues (I've tried running example app with chrome debugger and seems fine as well). Are you running into this when using the library with expo? Have you tried it with non-expo app? Maybe it is something wrong in you application code? Would you be able to share some pieces of your code that results in this error? Does the app redbox immediately when the component gets rendered or do you have to interact with it (pan or sth)?

PS: I've seen issues that happens only with chrome debugger ON (also seen issues that happens with JSC but not with chrome debugger). In any case this should get fixed

**Comment by peterpme** [comment]
Hey!

I'll do the best I can! It still takes place in debug mode only but I'll look into any logs I get on the native side

**Comment by peterpme** [comment]
Hey,

I've been out on holiday for the past week. You are right! It only happens when chrome debugger is ON! In this case I will close the issue :)

Thanks again!

**Comment by keeleycarrigan** [comment]
I know this issue is closed but I am experiencing this issue as well using the example Swipeable row. It doesn't error out if I turn off the debugger **OR** if I build the project through XCode 9.2. So maybe this is some kind of RN build system thing?

**Comment by deepankarsandy** [comment]
Workaround to this is just dismiss the error `ESC` and do the debugging
