### ISSUE TITLE
Add Example for Drag and Drop in FlatList

### ISSUE THREAD

**Issue by delianides** [kmagiera/react-native-gesture-handler#466]
I'm working on a drag and drop implementation with RNGH and any advice would be greatly appreciated.

**Comment by dsznajder** [comment]
@delianides What you actually need? I have in my project Drag&Drop of elements inside horizontal list :) If you have some code examples I can help you achieve some point.

**Comment by henrikra** [comment]
@delianides Do you mean something like this? https://github.com/ollija/react-native-sortable-grid I would like to see this too done with `react-native-gesture-handler`! <3

**Comment by kevtran410** [comment]
@delianides can you help me? I have an image gallery and can zoom and drag image inside. i want drag this image but don't want image moving out of screen, it look like view photo in Facebook.

**Comment by delianides** [comment]
@kevtran410 I'm sorry I don't understand what you need. My advice would be to ask either in the expo forums or in the expo spectrum.chat.
