### ISSUE TITLE
Swipeable on Android throws exception if component is removed

### ISSUE THREAD

**Issue by tallenh** [kmagiera/react-native-gesture-handler#48]
I have a FlatList with Swipeable items.  I have a handler onSwipeableLeftOpen that will remove the item from the list.  Each item also has a checkbox that when clicked will remove the item from the list.  If the only way you remove items is to swipe them away everything works great.  If you click the checkbox the item is removed, but the next time you touch the list it will throw an exception.

  I have only tested this on Android.

  I tried to debug but I haven't had much luck tracking it down.  I can say the exception is thrown in GestureHandlerOrchestrator.java line 318:

      throw new IllegalArgumentException("Parent is null? View is no longer in the tree");

I have a small example of this at
https://gist.github.com/tallenh/dfebf73859cca956bf8d6f31ccc4bf7c

**Comment by kmagiera** [comment]
Thanks for reporting @tallenh I'm going to take a look at this soon

**Comment by osdnk** [comment]
I also came across this issue and made a PR. It works in my case

**Comment by kmagiera** [comment]
@osdnk have you managed to repro this issue on the example app @tallenh provided: https://gist.github.com/tallenh/dfebf73859cca956bf8d6f31ccc4bf7c

**Comment by osdnk** [comment]
Yes. I've just pasted this gist into app 
GenyMotion, Nexus 5, API 23

**Comment by kmagiera** [comment]
Thanks a lot @tallenh for reporting this issue. I allowed me to catch two serious problems with Android implementation. These are fixed in #53 which will go out in the next release today or tomorrow
