### ISSUE TITLE
ViewPagerAndroid and Slider moved from RN 0.59 to external packages

### ISSUE THREAD

**Issue by farwayer** [kmagiera/react-native-gesture-handler#482]
Warning: ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'. See https://github.com/react-native-community/react-native-viewpager

Warning: Slider has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/slider' instead of 'react-native'. See https://github.com/react-native-community/react-native-slider

**Comment by retyui** [comment]
@kmagiera 
When do you publish a new version with these changes?

**Comment by betoharres** [comment]
Will be needed to run `react-native link` after upgrade?

**Comment by lucasbento** [comment]
@betoharres: no need to do that.

While this is not released you may run `yarn add kmagiera/react-native-gesture-handler#ff74e0e` which points to https://github.com/kmagiera/react-native-gesture-handler/pull/506.

**Comment by farshidshahmoradi1996** [comment]
released with this changes now?

**Comment by hu-qi** [comment]
![image](https://user-images.githubusercontent.com/17986122/58231022-813f7080-7d68-11e9-9783-74c2234ba232.png)
Same problem happens when I navigate to screen that has "Swiper".（import Swiper from 'react-native-swiper'）
my package.json:
```
{
  "name": "thirtyDays",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-gesture-handler": "kmagiera/react-native-gesture-handler",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by YajanaRao** [comment]
When can we expect a new release with this warning fix?

**Comment by SmirnovM91** [comment]
+1
