### ISSUE TITLE
Imperative Cancellation

### ISSUE THREAD

**Issue by jacobp100** [kmagiera/react-native-gesture-handler#484]
I understand you can disable the gesture handler, and that will cancel an in-progress gesture. However, is there a way to cancel a gesture, but not disable it.

My use-case is an iOS-like keyboard, but if you long press some buttons, it inputs the value, and cancels the gesture (so you can't trigger other buttons)

**Comment by osdnk** [comment]
@jacobp100 
It's a quite a nice case. I think that it's a good use case. I could take a look on it. But it appears to be quite easy to implement to if we you want, feel free to add some PR which I will happily review.

**Comment by jacobp100** [comment]
Yeah I can probably add the iOS version! I’m not great at android, but I can take a look!

**Comment by osdnk** [comment]
So I’ll add android then if needed

**Comment by jacobp100** [comment]
Sorry I’m taking so long on this! I am still planning to do it!

**Comment by osdnk** [comment]
@jacobp100 Thanks!
I'm afraid that there's no reason for keeping this issue open

**Comment by jacobp100** [comment]
Ah, sorry. I will get round to it at some point, but yes, we can close for now

**Comment by euroclydon37** [comment]
I really need this on both platforms. Basically, I have ScrollView that I would _love_ to have `waitFor` a pan responder that gives up control after a certain distance. Working on a bottom sheet that will stop at a certain point, but if the gesture is still moving up, it will scroll the content in a ScrollView instead.

**Comment by little-buddy** [comment]
@jacobp100 
I need your help!!!
I need functional fo Canceling...
I'm going nuts

**Comment by jacobp100** [comment]
Ahh sorry, I really want to find some time to do this! I haven't updated my project to use rn-gesture-handler yet, and I would like to have used that as a test-bed for this
