### ISSUE TITLE
Touchable not allow use array of styles

### ISSUE THREAD

**Issue by matpaul** [kmagiera/react-native-gesture-handler#488]
Hello, just test 1.1.0 in our project
```
import { TouchableOpacity } from 'react-native-gesture-handler'; 
...
 <TouchableOpacity
   onPress={onPress}
   style={[styles.touchable, style]}
 />
```
not work as expected (in RN Touchable work)

**Comment by fouad1994** [comment]
You have imported wrong class TouchableOpacity it is not an class from react-native-gesture-handler you have to use
import { TapGestureHandler } from 'react-native-gesture-handler'; 

or

import { TouchableOpacity } from 'react-native';

**Comment by matpaul** [comment]
@fouad1994 this is new feature in 1.1.0

https://kmagiera.github.io/react-native-gesture-handler/docs/component-touchables.html

**Comment by fouad1994** [comment]
Ah ok Sorry I don't know that please can you take a view for my issue may you can help me?
https://github.com/kmagiera/react-native-gesture-handler/issues/485

**Comment by matpaul** [comment]
@fouad1994 as i understand this is not issue, post it on stackoverflow with your code - more faster way to make your code work as expected))

**Comment by matpaul** [comment]
Thanks!

**Comment by Emekaer** [comment]
Use the containerStyle prop instead of the style prop for styling TouchableOpacity from react-native-gvesture-handler.

<TouchableOpacity containerStyle={"whatever style object"}>
