### ISSUE TITLE
'getDrawable(int)' is deprecated(IS BUG)

### ISSUE THREAD

**Issue by AMINDRH91** [kmagiera/react-native-gesture-handler#489]
i find bug on react-native-gesture-handler please fix this 
`getResources().getDrawable(sResolveOutValue.resourceId);`   TO=>
`ContextCompat.getDrawable(getContext(),sResolveOutValue.resourceId)` on 155  line  in *RNGestureHandlerButtonViewManager* class

**Comment by osdnk** [comment]
Hello,
Yes it's deprecated since API 22, but this line is performed if API is lower than 22 and it's necessary.

**Comment by sinisa-nimcevic** [comment]
Very useful. No course of action to take - no nothing. Plus closed another thread saying it's a duplicate of this :D good work

**Comment by osdnk** [comment]
could you elaborate a bit what’s in your mind?

**Comment by madgreasemonkey** [comment]
Now how to find answer for this? @osdnk closed another issue telling its duplicate of this, and closed this issue without giving a proper answer. Super course of action by @osdnk

**Comment by vikramkh** [comment]
+1 I am also having this issue. If anyone finds an answer please share

**Comment by xxczaki** [comment]
@vikramkh @madgreasemonkey @sinisa-nimcevic @AMINDRH91 This might help you:

https://github.com/software-mansion/react-native-gesture-handler/issues/509#issuecomment-565743081

**Comment by krszwsk** [comment]
For anyone else still facing this issue (after upgrading to 0.60+), **make sure you removed `react-native-gesture-handler` from `settings.gradle`.**

**Comment by acrabb** [comment]
This is breaking my android build trying to update to RN 0.60.0.

Anyone else seeing this as not just a warning but an error?
(Downgrading to ~1.3.0 didn't work for me unfortunately)
