### ISSUE TITLE
Wrong latest version on npm

### ISSUE THREAD

**Issue by retyui** [kmagiera/react-native-gesture-handler#490]
When I called:
```sh
npm i react-native-gesture-handler
```
I will expect to install `1.1.0` version, but I got 1.0.17

You should adhere to Semantic Versioning rules.

![image](https://user-images.githubusercontent.com/4661784/53720437-d2c71600-3e71-11e9-822e-ff0ff76f9d8b.png)

**Comment by kmagiera** [comment]
1.0.17 was a patch version on top of 1.0.16 for people who are not able to upgrade just yet (1.1.0 requires newer version of RN). It appears like a problem with npm. It should not install the version that has been uploaded the latest but the one with the most recent name

**Comment by retyui** [comment]
>>> 1.1.0 requires newer version of RN
In my opinion, is broken changes and you must increment the major version

**Comment by kmagiera** [comment]
This turned out to be my fault. When doing `npm publish` npm tags the published version as "latest". Because I published 1.0.17 after 1.1.0 it got marekd that way. I just changed latest tag using `npm dist-tag`. Thanks so much @retyui for noting
