### ISSUE TITLE
cannot find method method getOverflow()

### ISSUE THREAD

**Issue by ShaubertIlya** [kmagiera/react-native-gesture-handler#499]
![image](https://user-images.githubusercontent.com/35298274/53853428-9b7e7380-3fef-11e9-86d6-c758fd6c0b09.png)

on version 1.1.0

**Comment by Silverquark** [comment]
Same issue here

**Comment by osdnk** [comment]
Please update RN to newest version or use `< 1.1.0` version of RNGH

**Comment by ShaubertIlya** [comment]
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-gesture-handler": "^1.0.15"

but i'm still getting this issue

**Comment by Silverquark** [comment]
Using ^ will still update the minor Version. So that doesn't help. 

Try using this:
npm install react-native-gesture-handler@1.0.5

**Comment by ShaubertIlya** [comment]
> Using ^ will still update the minor Version. So that doesn't help.
> 
> Try using this:
> npm install react-native-gesture-handler@1.0.5

Thanks much. It works fine. But what version of  gesture handler is stable with RN 0.57.1? Is it critical to work with an old one?

**Comment by DungBuiDeveloper** [comment]
React-Native 0.57.0
"react-native-gesture-handler": "^1.0.5"

and same issue , please help

**Comment by jstansbe** [comment]
@DungBuiDeveloper remove the carrot from the version.
"react-native-gesture-handler": "1.0.5"
