### ISSUE TITLE
app is crashing after RN update to 0.50.1

### ISSUE THREAD

**Issue by shuuha** [kmagiera/react-native-gesture-handler#50]
Hello. After I updated the RN version to 0.50.1, the app is crashing. 
I was getting an error "Attempt to invoke virtual method java.lang.class".  But after reinstaliing the gesture-handler, the app crashes without any errors.
When commenting the override method in the MainActivity.java the app starts though the library does not work.

**Comment by kmagiera** [comment]
Thanks @shuuha for reporting. I'm currently working on adapting this lib to changes made in 0.50. Should be ready really soon!

**Comment by kmagiera** [comment]
Hey @shuuha the issue you're mentioning has been fixed in #44 

You should keep MainActivity.java the way it was in order for the library to work. I will release updated version of this library compatible with RN 0.50 shortly

**Comment by kmagiera** [comment]
Please try https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.0.0-alpha.30
