### ISSUE TITLE
RCTGetUIManagerQueue has moved in RN 0.50

### ISSUE THREAD

**Issue by jpaas** [kmagiera/react-native-gesture-handler#51]
`RNGestureHandlerModule.m` calls RCTGetUIManagerQueue, but with RN 0.50 it doesn't compile because it needs to:

```objc
#import <React/RCTUIManagerUtils.h>
```

**Comment by kmagiera** [comment]
Thanks @jpaas for reporting. I'm currently working on adapting this lib to changes made in 0.50. Should be ready really soon!

**Comment by kmagiera** [comment]
This got fixed by #44 
Thanks for reporting, new update will be released shortly with RN 0.50 compatibility fixes

**Comment by kmagiera** [comment]
Please try https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.0.0-alpha.30
