### ISSUE TITLE
cannot find method method getOverflow()

### ISSUE THREAD

**Issue by ShaubertIlya** [kmagiera/react-native-gesture-handler#510]
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-gesture-handler": "^1.0.15"

https://user-images.githubusercontent.com/35298274/53853428-9b7e7380-3fef-11e9-86d6-c758fd6c0b09.png

**Comment by anjalirughani** [comment]
+1

**Comment by ShaubertIlya** [comment]
Try using this:
npm install react-native-gesture-handler@1.0.5
It helps

**Comment by minhchienwikipedia** [comment]
I'm still want to use version 1.1.0. So what can I do to fix this issue?

**Comment by miraclesumail** [comment]
npm install react-native-gesture-handler@1.0.5   do u have try, why cheat me

**Comment by P147x** [comment]
Nah, i got the same error. Seems to be an different issue.
Using a different version isn't working.

`> Task :react-native-gesture-handler:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings
34 actionable tasks: 31 executed, 3 up-to-date
/Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
import android.support.v4.util.Pools;
                              ^
/Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:19: error: package Pools does not exist
  private static final Pools.SynchronizedPool<RNGestureHandlerEvent> EVENTS_POOL =
                            ^
/Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:3: error: package android.support.v4.util does not exist
import android.support.v4.util.Pools;
                              ^
/Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:19: error: package Pools does not exist
  private static final Pools.SynchronizedPool<RNGestureHandlerStateChangeEvent> EVENTS_POOL =
                            ^
/Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:20: error: package Pools does not exist
          new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
                   ^
/Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:20: error: package Pools does not exist
          new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
                   ^
Note: /Users/lucas/Projects/swipe-application/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors`

**Comment by oguzkaganeren** [comment]
I fix with this;
`npm i jetifier
npx jetify`

**Comment by kanzeparov** [comment]
> I fix with this;
> `npm i jetifier`
> `npx jetify`

Thanks @oguzkaganeren, it works for me!

**Comment by victoriiapetrenko** [comment]
> I fix with this;
> `npm i jetifier`
> `npx jetify`

Thanks, @oguzkaganeren, it works for me!

**Comment by muhammadashfaq** [comment]
> I fix with this;
> `npm i jetifier`
> `npx jetify`

Thanks @oguzkaganeren    it works fine .

**Comment by ugglr** [comment]
@oguzkaganeren Yeey! This worked for me as well, thank you for sharing!

**Comment by sillasgoes** [comment]
@oguzkaganeren  Thanks so much man! This worked here

**Comment by victor-s-santos** [comment]
@oguzkaganeren This worked for me too. Thanks ^^

**Comment by alcomide** [comment]
> I fix with this;
> `npm i jetifier`
> `npx jetify`

Perfect fix! Thank you!

**Comment by rendermanGL** [comment]
> Try using this:
> npm install react-native-gesture-handler@1.0.5
> It helps

This one really worked for me. Thank you!

**Comment by justinairbase** [comment]
I just removed `node_modules` and `yarn.lock` and set the version of "react-native-gesture-handler" in `package.json` like so: `"react-native-gesture-handler": "1.0.15",`. Then run `yarn install`. That should fix the issue. Looks like the newer versions of this is causing the problem.

**Comment by VictorThales** [comment]
> I just removed `node_modules` and `yarn.lock` and set the version of "react-native-gesture-handler" in `package.json` like so: `"react-native-gesture-handler": "1.0.15",`. Then run `yarn install`. That should fix the issue. Looks like the newer versions of this is causing the problem.


I did the above and it worked

**Comment by TivanDev** [comment]
just run 
`npm install react-native-gesture-handler@1.0.5
`
and secend step
`npx jetify`

then react-native run-android
