### ISSUE TITLE
peer dependencies 

### ISSUE THREAD

**Issue by voxspox** [kmagiera/react-native-gesture-handler#526]
I get the following warning for a react-native project using react-navigation 3:

    npm WARN react-native-gesture-handler@1.1.0 requires a peer of react-art@>= 16.3.2 but none is installed. You must install peer dependencies yourself.
    npm WARN react-native-gesture-handler@1.1.0 requires a peer of react-native-web@>= 0.7 but none is installed. You must install peer dependencies yourself.

It seems only the Example needs these packages but not RNGH itself. How can I fix this warning?

**Comment by osdnk** [comment]
Will be fixed in new release
