### ISSUE TITLE
Any plan for releasing new version to support 0.59

### ISSUE THREAD

**Issue by tianjyan** [kmagiera/react-native-gesture-handler#530]
I notice that you have a commit that support RN 0.59, but have no new version on npmjs.com. So could I know the plan that you release the new version to support 0.59.

**Comment by ziyoshams** [comment]
😱 is that why I am getting linking issues on `0.59.2`?
```
info Linking "react-native-gesture-handler" iOS dependency
error Something went wrong while linking. Error: Cannot read property 'match' of undefined
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues
error Cannot read property 'match' of undefined
```

**Comment by tianjyan** [comment]
@ziyoshams Do you have any sample repo to reproduce your issue ? Your issue  doesn't seem to be related to this repo.

RN 0.59 removed some components like Slider (For more information you can view: 
http://facebook.github.io/react-native/blog/#lean-core-is-underway and https://github.com/facebook/react-native/blob/0.59-stable/Libraries/react-native/react-native-implementation.js ) .

If you get any error message likes `xxx has been extracted from react-native core and will be removed in a future release.`, this maybe (I say maybe because other dependencies that you use can also get this error message.) an issue that related to this repo.

Hopes the words above could help you. Thanks~

**Comment by ziyoshams** [comment]
@tianjyan You are right. My issue was the commented line in Podfile (`# Add new pods below this line`). I added it and the linking started working.

**Comment by solkaz** [comment]
While this issue is old, I am wondering when there would be a new release to this package (last release was almost a two months ago)?

**Comment by osdnk** [comment]
Fixed in the new release.
