### ISSUE TITLE
not using extracted Slider and ViewPagerAndroid

### ISSUE THREAD

**Issue by yanush** [kmagiera/react-native-gesture-handler#535]
both Slider and ViewPagerAndroid have been extracted from react native core. need to start using the extracted components from react native community

**Comment by osdnk** [comment]
It's already merged to `master` so will be fixed in a next release.

**Comment by jan-happy** [comment]
Great news! When can we expect the next release?

**Comment by santiph** [comment]
Same question

**Comment by Abhijeetjaiswalit** [comment]
same question

**Comment by bluedaniel** [comment]
I'm waiting on a new release too.

**Comment by filipencus** [comment]
Waiting for it me too. I spent literally two day fixing related issues. Thanks.

**Comment by ertejaspatel** [comment]
Any updates on the next release date? Thanks...

**Comment by farshidshahmoradi1996** [comment]
i have same warning at 
  "react-native": "0.59.5",
   "react-native-gesture-handler": "^1.1.0",

**Comment by ldipasquale** [comment]
Waiting for the next release too.

**Comment by youssefali424** [comment]
same issue....
"react-native": "0.59.5",
"react-native-gesture-handler": "^1.1.0",

**Comment by redelman431** [comment]
I am on react native gesture handler 1.2.1 still having the same problem.

**Comment by obivandamme** [comment]
I updated to 1.3.0 and the Warnin is still present.
