### ISSUE TITLE
Unable to use stacked buttons

### ISSUE THREAD

**Issue by eyousefifar** [kmagiera/react-native-gesture-handler#549]
Hello, I'm trying to use one Button inside another, but the inside button doesn't work,

here is the info:
react: 16.6.3 
react-native: 0.57.8 
react-native-gesture-handler: 1.1.0
platform: Android

I've tested with waitFor and disallowInterruption props and zIndex in styles but no luck.
I would appreciate any help. 
Thanks

**Comment by dsznajder** [comment]
@eyousefifar Could you provide some reproduction example? You can use https://snack.io which has `react-native-gesture-handler` installed.

**Comment by eyousefifar** [comment]
@dsznajder okay I'm using react-native-navigation and I forgot to use gestureHandlerRootHOC on the main screen, now everything works as expected, testing on snack made me realize that, sorry for bothering you.
