### ISSUE TITLE
iOS draggable doesn't "keep up" with finger

### ISSUE THREAD

**Issue by scottmas** [kmagiera/react-native-gesture-handler#55]
The gist of this problem is that on iOS, when you drag a draggable element very quickly and the user's finger goes outside the bounds of the draggable element, the drag movement abruptly stops. Just run the code at https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/draggable/index.js on iOS and move your finger very quickly to see what I mean. 

On one level, this does make sense, since the user's finger is no longer on the draggable element. But from a usability perspective, it seems as though this is not the right interaction. And on Android, no matter how fast you move your finger, the draggable element is never lost, which is more in line with the interaction we would expect to see.

**Comment by kmagiera** [comment]
Hey @scottmas! Thanks for reaching out

This behaviour can be changed using `shouldCancelWhenOutside={false}` option set on `PanHandler` component. 

This option used to default to `true` on iOS. This has been recently changed here https://github.com/kmagiera/react-native-gesture-handler/commit/a15e534890d90e4fa422e4f14a4577160ce76175 – although that change hasn't yet been released.

**Comment by scottmas** [comment]
Oh excellent! Thank you
