### ISSUE TITLE
Not an issue - this library is amazing

### ISSUE THREAD

**Issue by scottmas** [kmagiera/react-native-gesture-handler#56]
I just wanted to say thank you for creating this library. It's amazing. It just immediately solved this draggable performance problem I had been banging my head against for weeks, producing silky smooth draggable animations on old devices. 

Thank you.

**Comment by kmagiera** [comment]
Thank you @scottmas ! Seeing others use it and solving their problems with it is very motivating. Good luck with the projects you are working on!
