### ISSUE TITLE
How to open the DrawerLayout from a button

### ISSUE THREAD

**Issue by cyborgium** [kmagiera/react-native-gesture-handler#567]
Hi,

I would very much like to use the DrawerLayout but for the design of the app im trying to make, there needs to be a button to open the Drawer as well as being able to open the Drawer by swiping. However, I can't find a way to do this at all. There is a different post about this exact thing, but one without a solution so I thought I'd try my luck..

Thanks in advance.

**Comment by hampustagerud** [comment]
Have you tried [this](https://github.com/kmagiera/react-native-gesture-handler/blob/c5c1cfbfade75beea3746ebf13814f505aa1ec01/DrawerLayout.js#L349) and [this](https://github.com/kmagiera/react-native-gesture-handler/blob/c5c1cfbfade75beea3746ebf13814f505aa1ec01/Example/horizontalDrawer/index.js#L126)? There is an example project that covers pretty much everything 👍

**Comment by cyborgium** [comment]
Sorry for the late response, I never got around to this project till now. 



> Have you tried [this](https://github.com/kmagiera/react-native-gesture-handler/blob/c5c1cfbfade75beea3746ebf13814f505aa1ec01/DrawerLayout.js#L349) and [this](https://github.com/kmagiera/react-native-gesture-handler/blob/c5c1cfbfade75beea3746ebf13814f505aa1ec01/Example/horizontalDrawer/index.js#L126)? There is an example project that covers pretty much everything 👍

According to that example, it should basically be `this.drawer.openDrawer()}` but whenever I do that, I get a `TypeError: undefined is not an object`
Do you have any idea?
This is my code:

```
<DrawerLayout
          drawerWidth={200}
          drawerPosition={DrawerLayout.positions.Left}
          drawerType='front'
          drawerBackgroundColor="#ddd"
          renderNavigationView={this.renderDrawer}>
          <View>
            <TouchableHighlight onPress={() => this.drawer.openDrawer()}>
              <Text style={{ marginTop: 50}}>
                nope
            </Text>
            </TouchableHighlight>

          </View>
        </DrawerLayout>
```

**Comment by hampustagerud** [comment]
It's `undefined` because you never set `this.drawer` to anything 🙂 You missed the [ref](https://github.com/kmagiera/react-native-gesture-handler/blob/c5c1cfbfade75beea3746ebf13814f505aa1ec01/Example/horizontalDrawer/index.js#L84-L86) part.

**Comment by cyborgium** [comment]
> It's `undefined` because you never set `this.drawer` to anything 🙂 You missed the [ref](https://github.com/kmagiera/react-native-gesture-handler/blob/c5c1cfbfade75beea3746ebf13814f505aa1ec01/Example/horizontalDrawer/index.js#L84-L86) part.

That was it.....

Thank you!

**Comment by Quiec** [comment]
I have same problem, I added ref part but.

My code:
```js
import React, {Component} from 'react'
import Anasayfa from './src/pages/Anasayfa'
import {Text, Content, Container, Button} from 'native-base'
import Sidebar from './src/components/Sidebar'
import DrawerLayout from 'react-native-gesture-handler/DrawerLayout';

class App extends Component {
	state = {
	  count: 0
	}
	renderDrawer = () => {
		return (
			<Container>
				<Content>
					<Text>I am in the drawer!</Text>
				</Content>
			</Container>
		);
	};
		
	render() {
		return (
			<Container>
				<DrawerLayout
					drawerWidth={200}
					drawerPosition={DrawerLayout.positions.Right}
					drawerType="front"
					drawerBackgroundColor="#ddd"
					renderNavigationView={this.renderDrawer}
					ref={drawer => {
						this.drawer = drawer;
					}}>
					<Button onPress={this.drawer.openDrawer()}><Text>Deneme</Text></Button>
				</DrawerLayout>
			</Container>
		)
	}
  }
  
export default App;
```

Error:
<img src='https://user-images.githubusercontent.com/46392667/94016160-76f71180-fdb6-11ea-9cf0-63c92f5a8aee.png' width=450 height=720>

**Comment by Quiec** [comment]
> I have same problem, I added ref part but.
> 
> My code:
> 
> ```js
> import React, {Component} from 'react'
> import Anasayfa from './src/pages/Anasayfa'
> import {Text, Content, Container, Button} from 'native-base'
> import Sidebar from './src/components/Sidebar'
> import DrawerLayout from 'react-native-gesture-handler/DrawerLayout';
> 
> class App extends Component {
> 	state = {
> 	  count: 0
> 	}
> 	renderDrawer = () => {
> 		return (
> 			<Container>
> 				<Content>
> 					<Text>I am in the drawer!</Text>
> 				</Content>
> 			</Container>
> 		);
> 	};
> 		
> 	render() {
> 		return (
> 			<Container>
> 				<DrawerLayout
> 					drawerWidth={200}
> 					drawerPosition={DrawerLayout.positions.Right}
> 					drawerType="front"
> 					drawerBackgroundColor="#ddd"
> 					renderNavigationView={this.renderDrawer}
> 					ref={drawer => {
> 						this.drawer = drawer;
> 					}}>
> 					<Button onPress={this.drawer.openDrawer()}><Text>Deneme</Text></Button>
> 				</DrawerLayout>
> 			</Container>
> 		)
> 	}
>   }
>   
> export default App;
> ```
> 
> Error:
> <img alt="" width="450" height="720" src="https://user-images.githubusercontent.com/46392667/94016160-76f71180-fdb6-11ea-9cf0-63c92f5a8aee.png">

@hampustagerud

**Comment by hardik-wts** [comment]
With **React Native Hooks** **OPEN** and **CLOSE** drawer in three simple steps

- 1 Initialize Reference 
- 2 Assign Reference
- 3 Use of Reference

**Code**

```
import React, { useRef, useEffect } from 'react'
import { View, Button } from 'react-native'
import DrawerLayout from 'react-native-gesture-handler/DrawerLayout';

const DrawerLayoutExample = () => {

    var refDrawer = useRef() // => Initialize Reference 

    var renderDrawer = () => {
        return (

            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
                <Button
                    onPress={() => refDrawer.current.closeDrawer()} // => Use of Reference
                    title='Close Drawer'>
                </Button>
            </View>

        );
    };

    return (
        <DrawerLayout
            ref={refDrawer} // => Assign Reference
            drawerWidth={200}
            drawerPosition={DrawerLayout.positions.Right}
            drawerType="front"
            drawerBackgroundColor="#ddd"
            renderNavigationView={renderDrawer}>
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
                <Button
                    onPress={() => refDrawer.current.openDrawer()} // => Use of Reference
                    title='Open Drawer'>
                </Button>
            </View>
        </DrawerLayout>
    )
}

export default DrawerLayoutExample
```

**Extras**  **(For Evaluating The Reference)**  

```
useEffect(() => {
        console.log('Drawer refrence ', refDrawer)
        return () => null
    }, [])
```

**Comment by desai-hardik** [comment]
With **React Native Hooks** **OPEN** and **CLOSE** drawer in three simple steps

- 1 Initialize Reference
- 2 Assign Reference
- 3 Use of Reference
 

**Code**

```
import React, { useRef, useEffect } from 'react'
import { View, Button } from 'react-native'
import DrawerLayout from 'react-native-gesture-handler/DrawerLayout';

const DrawerLayoutExample = () => {

    var refDrawer = useRef() // => Initialize Reference 

    var renderDrawer = () => {
        return (

            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
                <Button
                    onPress={() => refDrawer.current.closeDrawer()} // => Use of Reference
                    title='Close Drawer'>
                </Button>
            </View>

        );
    };

    return (
        <DrawerLayout
            ref={refDrawer} // => Assign Reference
            drawerWidth={200}
            drawerPosition={DrawerLayout.positions.Right}
            drawerType="front"
            drawerBackgroundColor="#ddd"
            renderNavigationView={renderDrawer}>
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
                <Button
                    onPress={() => refDrawer.current.openDrawer()} // => Use of Reference
                    title='Open Drawer'>
                </Button>
            </View>
        </DrawerLayout>
    )
}

export default DrawerLayoutExample
```
**Extras (For Evaluating The Reference)**

```
useEffect(() => {
        console.log('Drawer refrence ', refDrawer)
        return () => null
    }, [])
```
