### ISSUE TITLE
hitSlop with right and width properties are not respected on Android

### ISSUE THREAD

**Issue by satya164** [kmagiera/react-native-gesture-handler#569]
When a `hitSlop` of value `{ left: 0, width: 48 }` is supplied, the result is expected, 48dpi on the left activates a gesture. But if a value like `{ right: 0, width: 48 }`, it only works on iOS, i.e. 48dpi on the right activates the gesture on iOS, but on Android, it behaves like it's not specified.

The `DrawerLayout` component in the repo suffers from this bug when `drawePosition` is `right`.

For better understanding, here is a repro: https://snack.expo.io/@satya164/gesture-handler-hitslop-bug

cc @osdnk

**Comment by adamczyk777** [comment]
Hi @satya164 I will be addressing this issue in the near future I guess 😄

**Comment by adamczyk777** [comment]
The PR addressing this issue has been merged, allow me to close this issue 😌
