### ISSUE TITLE
Swipeable not working right at device

### ISSUE THREAD

**Issue by hellomaya** [kmagiera/react-native-gesture-handler#57]
Hi, first this component was really nice and helpful, thank you.

I have been running the Example at iOS simulator & iPhone 5C (10.3.3) device same time, the Swipeable.js from the component wasn't working right at device, in the Example:

Gesture handler based SwipeableRow, when I swipe it, it doesn't show action button at all...even the swiping gesture is working.

But in Table rows & buttons, that "Swipeable" component working well both in simulator & device.

I saw they are two different implementation, I am still looking for what's wrong with it.

Also feel obligated to report the issue here, and notice what happened.

**Comment by kmagiera** [comment]
Thanks for reporting @hellomaya !

Would be really helpful if you could share some code samples or screenshots videos so that we can better understand what's happening.

**Comment by hellomaya** [comment]
Hi, I uploaded a video to a local git repo site as its much more faster than github for me. Here is the link:

https://gitee.com/tomlike/RN-Sales-Manager-2.0/blob/master/RNGH-device-test.m4v

You can download it and check it, as you can see what happened, I tried table rows and swipeable both.

Thank you.

**Comment by kmagiera** [comment]
Sorry @hellomaya but I am unable to download you video file. Do you mind uploading it somewhere else? I get HTTP errors in the middle of download process each time I try (had quite a few attempts). Once you put it up somewhere else please reopen this issue

**Comment by hellomaya** [comment]
I am really sorry @kmagiera, I didn't know that, and it certainly waste your time.

I will upload here with a small size zipped version, hopefully you can see it  

[demo.mov.zip](https://github.com/kmagiera/react-native-gesture-handler/files/1521890/demo.mov.zip)
