### ISSUE TITLE
Customize color of ripple on Android

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#58]
For RectButton I believe this is done with underlayColor, but there doesn't seem to be an option for this on BorderlessButton

**Comment by gtfargo** [comment]
Wanted to note that `underlayColor` does not seem to be working on `<RectButton />` right now.

Just put together a Snack and realized this issue may be caused by setting a `backgroundColor` on the `<RectButton />`, though I'm not sure this is intended.

https://snack.expo.io/Bk2OQYRHG

**Comment by MyGuySi** [comment]
Just wanted to add I'm getting this issue @gtfargo described. I had set the `backgroundColor` but removing that doesn't help, the ripple is still semi-transparent black
