### ISSUE TITLE
Swipeable support for web (Dependent on TapGestureHandler and PanGestureHandler)

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#581]
Goal: Use the exact same swipeable component between ios/android and web. One that is performant, backed by rngh / reanimated.

Seems to be dependent on `PanGestureHandler` (#540) and `TapGestureHandler`.
https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js

**Comment by brunolemos** [comment]
Hey @EvanBacon, I see you made it work in the web! Are the changes coming to this repo?
https://twitter.com/Baconbrix/status/1141240199407517696?s=20

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/619186/59980117-8130cb80-95c7-11e9-93cb-e176d236038d.gif)

**Comment by EvanBacon** [comment]
Work is being tracked here https://github.com/kmagiera/react-native-gesture-handler/pull/555

**Comment by kmagiera** [comment]
Closing as #555 got recently merged 💘 🥓
