### ISSUE TITLE
DrawerLayoutProperties interface is Missing StyleProp<ViewStyle> on NPM

### ISSUE THREAD

**Issue by Brunohes** [kmagiera/react-native-gesture-handler#582]
Hi,

I gathered some evidence about the error to help found what is happening.
I think is missing some kind of update on NPM, because is fixed on Github but when i download through NPM come without the fixed declaration.
The Version Downloaded is the most recent one v1.1.0.

The Error
![erros-tsc](https://user-images.githubusercontent.com/7794999/56742007-5b638380-674a-11e9-960f-636db8eccb18.png)

Fixed on your Github
![yours-on-github](https://user-images.githubusercontent.com/7794999/56742078-7930e880-674a-11e9-86d0-d38b46497f80.png)

My Declaration file from Version 1.1.0
![missing-types](https://user-images.githubusercontent.com/7794999/56742161-982f7a80-674a-11e9-83d4-ff49f825bf82.png)

![package](https://user-images.githubusercontent.com/7794999/56742272-c6ad5580-674a-11e9-983d-5e0388385984.png)

Last time updated on Github
![last-time-updated-github](https://user-images.githubusercontent.com/7794999/56742306-d7f66200-674a-11e9-8000-62c8b0520f57.png)

Last time updated on NPM
![last-time-updated-npm](https://user-images.githubusercontent.com/7794999/56742318-df1d7000-674a-11e9-904e-097e1f28cc68.png)

**Comment by adamczyk777** [comment]
Hi @Brunohes, Is it still present in the latest release we published yesterday?

**Comment by Brunohes** [comment]
Problem Solved! @adamczyk777  Thanks!
