### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by jeffreyffs** [kmagiera/react-native-gesture-handler#584]
It has been almost two months since a new version was published and there have been lots of contributions to the project in the meantime.

Is there something holding back a release of a new version?

PS: @kmagiera love all your work on this, reanimated and screens :)

**Comment by kmagiera** [comment]
Hey! Sorry @jeffreyffs for the delay on that. Just have been busy with some other tasks lately. Maybe @osdnk could help with submitting a new release when he has some time

**Comment by kmagiera** [comment]
Many thanks to @adamczyk777 for working on the newest release. I'm closing this now. Thanks @jeffreyffs for keeping you eye on the release schedule!

**Comment by jeffreyffs** [comment]
No need to apologize. Thanks so much 👏
