### ISSUE TITLE
borderRadius on RectButton on Android

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#59]
Setting `borderRadius` on RectButton does not actually round the corners. Current workaround is to wrap a RectButton with a View that has a borderRadius set.

**Comment by vpodolyan** [comment]
The same with `borderWidth`

**Comment by osdnk** [comment]
This issue has been reffered in one of PRs. As soon as it will have been merged, I suppose the problem will be solved. 
I close the issue

**Comment by GoldenMaximo** [comment]
Why is this closed? I'm still unable to set `borderRadius` on RectButton.


> Setting `borderRadius` on RectButton does not actually round the corners. Current workaround is to wrap a RectButton with a View that has a borderRadius set.

Didn't work either.

![Screenshot_1](https://user-images.githubusercontent.com/51284438/64432559-291c4800-d093-11e9-93f2-0928f02ffdc0.png)

The border represents the view wrapping the RectButton and the grey area the RectButton itself.

Code:

```
<View style={style.borderRadiusOf50}>
  <RectButton>
    <View accessible style={[style.square, style.squareTypeOne]}>
      <Image
        resizeMode="center"
        source={oxygenLogo}
        style={style.logo}
      />
      <Text style={style.buttonLabel}>
        Recarga de cilindros de oxigênio
      </Text>
    </View>
  </RectButton>
</View>
```

### Solution

I found out while writing this comment that RectButton needs `backgroundColor` for `borderRadius` to work. I also just checked the docs and there's nothing mentioning this requisite in there so it's kinda unintuitive.

**Comment by kesha-antonov** [comment]
> Why is this closed? I'm still unable to set `borderRadius` on RectButton.
> 
> > Setting `borderRadius` on RectButton does not actually round the corners. Current workaround is to wrap a RectButton with a View that has a borderRadius set.
> 
> Didn't work either.
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/51284438/64432559-291c4800-d093-11e9-93f2-0928f02ffdc0.png)
> 
> The border represents the view wrapping the RectButton and the grey area the RectButton itself.
> 
> Code:
> 
> ```
> <View style={style.borderRadiusOf50}>
>   <RectButton>
>     <View accessible style={[style.square, style.squareTypeOne]}>
>       <Image
>         resizeMode="center"
>         source={oxygenLogo}
>         style={style.logo}
>       />
>       <Text style={style.buttonLabel}>
>         Recarga de cilindros de oxigênio
>       </Text>
>     </View>
>   </RectButton>
> </View>
> ```
> 
> ### Solution
> I found out while writing this comment that RectButton needs `backgroundColor` for `borderRadius` to work. I also just checked the docs and there's nothing mentioning this requisite in there so it's kinda unintuitive.

Thanks! Setting ```backgroundColor``` helped
