### ISSUE TITLE
Extract DrawerLayout to separate repo & move to reanimated

### ISSUE THREAD

**Issue by radex** [kmagiera/react-native-gesture-handler#601]
Hey! What do you think about extracting DrawerLayout out of this repo? I think it would make it easier to maintain and allow to upgrade it to `reanimated`, which would allow more intricate, more polished animations :) I might be willing to contribute to this effort.

**Comment by osdnk** [comment]
Hello, @radex 
Good idea!
What's more, it's almost finished
https://github.com/react-navigation/drawer

**Comment by radex** [comment]
@osdnk Oh! That's good to know! Curious: What's the reason for keeping DrawerLayout in this repo, then?

**Comment by osdnk** [comment]
@radex 
Bc it's not stable yet. It has some issues we need to resolve. 
After that, we'll make it a source of a drawer for react-navigation and then we will still keep it here for some time for backward compatibility (of react-navigation which relies on it).

**Comment by osdnk** [comment]
If you'd like to help, feel free to contribute!

**Comment by radex** [comment]
Understood, thank you! We are looking into `react-navigation`, and so we'll likely switch to the other repo and fix issues as needed :)
