### ISSUE TITLE
Couldn't install react-native-gesture-handler

### ISSUE THREAD

**Issue by jaysonderu** [kmagiera/react-native-gesture-handler#602]
![Capture](https://user-images.githubusercontent.com/50488299/57527024-8ad8d980-7361-11e9-87fd-9f4c42be84c7.JPG)

Couldn't install react-native-gesture-handler
I followed the instructions from https://reactnavigation.org/docs/en/getting-started.html
Please help

**Comment by PujanShah22** [comment]
@jaysonderu ,

I just get it work by removing react-native-safe-area-view from node-modules.
After that install react-native-gesture-handler which will auto install react-native-safe-area-view again.
 
Cheers 👍

**Comment by adamczyk777** [comment]
I was able to reproduce the issue without even installing react native gesture handler and only react-native-safe-area-view and react navigation. Closing this issue as it is unrelated to this project.
