### ISSUE TITLE
libRNGestureHandler.a not found on build (sometimes)

### ISSUE THREAD

**Issue by SirCameron** [kmagiera/react-native-gesture-handler#614]
Going from one build to the next AppCenter reports this file as not being present and failing the build, to the next build working - without any changes.

The path given is:
```
[project]/Build/Intermediates.noindex/ArchiveIntermediates/Release/BuildProductsPath/Release-iphoneos/libRNGestureHandler.a
```

Has anyone experienced this or has any idea how to correct it?

thanks!

**Comment by mchaelml** [comment]
Have same issue, so what I did is simply remove it from xcode projects linked library with binaries

**Comment by SirCameron** [comment]
hey @mchaelml can you elaborate?

**Comment by SirCameron** [comment]
I think I know what you mean. Wasn't sure what you meant about linking binaries.
I removed the RNGestureHandler.a from linked libraries and it build without pain.

**Comment by mchaelml** [comment]
yeah that worked :)

**Comment by ZenModeRy** [comment]
This didn't work for me, as RNGH is a dependency of React-Navigation in my case.
