### ISSUE TITLE
Is it possible to change the sensitivity of the rotation events?

### ISSUE THREAD

**Issue by thibault12** [kmagiera/react-native-gesture-handler#62]
I was wondering if it was possible to change the sensitivity of the rotation (how much is rotate for a given rotation gesture event)?

**Comment by kmagiera** [comment]
Thanks for reaching out @thibault12 

Could you clarify a bit what you mean by the sensitivity of rotation? Do you want to be able to set the threshold for the angle at which the handler would activate?

**Comment by kmagiera** [comment]
Closing this for now, if you find some time @thibault12 to answer this and continue the discussion feel free to reopen
