### ISSUE TITLE
Task :react-native-gesture-handler:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by Fausto95** [kmagiera/react-native-gesture-handler#628]
Hi there,

I'm getting this error when using this library and `react-native-camera` within the same project. 

If I remove `react-native-camera`, I don't get any erros showing up.

<img width="528" alt="Capture d’écran 2019-06-05 à 15 02 19" src="https://user-images.githubusercontent.com/23306911/58958338-fbc5b280-87a2-11e9-8880-b3a38d3a78e0.png">

My package.json looks like this:
```json
{
  "name": "rnTestingApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-camera": "^2.10.0",
    "react-native-gesture-handler": "^1.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by Fausto95** [comment]
This is likely because `react-native-camera` uses androidX

**Comment by jlally21** [comment]
@Fausto95  experiencing the same issue.  So what is your strategy?  Using `react-native-camera 2.6.0` resolves the issue for me but looking for a better solution.

**Comment by Fausto95** [comment]
I’ve also downgraded `react-native-camera` to version `2.9.0`

**Comment by mchaelml** [comment]
I'm not using react-native-camera but still getting same error. Any thoughts?

**Comment by jlally21** [comment]
@mchaelml you may have a different npm package that uses androidX

**Comment by joshuakoh7** [comment]
Is there any way to make this work with androidx?

**Comment by Fausto95** [comment]
You might want to fork the library and apply these changes https://github.com/kmagiera/react-native-gesture-handler/pull/589 and installing it from github into your project

**Comment by DedoJr** [comment]
"react-native": "0.59.8",
"react-native-camera": "2.1.0",
"react-native-gesture-handler": "1.1.0"

This solution worked for me...

**Comment by mchaelml** [comment]
guys, what worked for me was to go to the nam package and change the error references to androidx ones. so "android.support.v4.util.Pools" -> "androidx.core.util.Pools"

Hope this helps someone. Its not ideal way but works for dev

**Comment by Fausto95** [comment]
If you're running to the same issue, running `npx jetify` should help you or using the Android Studio option for migrating native libraries to Androidx might also help you!
