### ISSUE TITLE
Not able to run examples

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#63]
I keep getting this error even after recloning and clearing all caches:

```
Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/brunolemos/Projects/packages/react-native-gesture-handler/Example/index.ios.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/brunolemos/Projects/packages/react-native-gesture-handler/Example/node_modules/react-native-gesture-handler/Example/node_modules/react-native/package.json`
  * `/Users/brunolemos/Projects/packages/react-native-gesture-handler/Example/node_modules/react-native/package.json`
```

**Comment by brunolemos** [comment]
Running this inside the Example folder make it work:

```
rm -rf ../node_modules/react-native
ns -- --reset-cache
```

But that shouldn't be needed, something is wrong.

**Comment by TheCodeTalker** [comment]
@brunolemos after that also i getting this
`error: bundling failed: ambiguous resolution: module `/Users/thecodetalker/Documents/REACTNATIVE/react-native-gesture-handler/Example/index.ios.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/thecodetalker/Documents/REACTNATIVE/react-native-gesture-handler/Example/node_modules/react-native-gesture-handler/Example/node_modules/react-native-gesture-handler/Example/node_modules/react-native/package.json`
  * `/Users/thecodetalker/Documents/REACTNATIVE/react-native-gesture-handler/Example/node_modules/react-native/package.json`

**Comment by kmagiera** [comment]
Hey @TheCodeTalker 

Are you installing gesture handler lib from NPM? Because the package distributed via npm does not contain the Example folder. So it seems like you might have npm link it or maybe copy from git clone?
