### ISSUE TITLE
gestureHandlerRootHOC not available in 1.0.0-beta32

### ISSUE THREAD

**Issue by wmcbain** [kmagiera/react-native-gesture-handler#65]
Hey there, tried to install 1.0.0-beta32 but found that it's missing the `gestureHandlerRootHOC` on the install.

<img width="373" alt="screen shot 2017-12-05 at 1 23 31 pm" src="https://user-images.githubusercontent.com/7080654/33623604-8cecee1a-d9bf-11e7-92c6-8bd04add7af1.png">

Reverting to beta30 resolved, just wanted to give a heads up.

**Comment by kmagiera** [comment]
Thanks for the heads up @wmcbain !

This is weird as when I install the package the file is there. Would you mind checking if the file exists at all. There should actually be two versions of it: gestureHandlerRootHOC.android.js and gestureHandlerRootHOC.ios.js. 

Maybe this could be related to packager setup or sth?

**Comment by wmcbain** [comment]
I'm using the default Metro Bundler I believe, it is weird:

<img width="395" alt="screen shot 2017-12-05 at 3 21 46 pm" src="https://user-images.githubusercontent.com/7080654/33628920-4bb9c2d6-d9d0-11e7-8235-f29a3c0d7275.png">

<img width="964" alt="screen shot 2017-12-05 at 3 22 15 pm" src="https://user-images.githubusercontent.com/7080654/33628931-4f1255ec-d9d0-11e7-901a-19262817bcd7.png">

**Comment by kmagiera** [comment]
@wmcbain I just created a new project, installed RNGH and files are there. Is it possible that sth went wrong with your yarn install? When you `rm -r node_modules` and then `yarn install` again are these files still gone?

**Comment by wmcbain** [comment]
@kmagiera Wrote this up and came down with a horrible cold. Just getting back on my feet. I'm going to close this until I can test a little bit further.

**Comment by jarvisluong** [comment]
I also found the same problem
