### ISSUE TITLE
_RNGestureHandlerModule.default.Direction in react native 0.60.0

### ISSUE THREAD

**Issue by Harsh2402** [kmagiera/react-native-gesture-handler#673]
I have used the following configurations.
```
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.0",
    "react-navigation-fluid-transitions": "^0.3.2"
``` 

In react-native latest version 0.60.0, facing an issue.

**Comment by PluginIO** [comment]
I'm also seeing this same issue. I used the typescript template and used the following:

```
yarn add react-navigation
yarn add react-native-gesture-handler
react-native link
```

I see the same error as described above.

**Comment by godested** [comment]
Same problem

**Comment by hellotoby** [comment]
Looks like this is to do with the new autolinking feature in RN 0.60. To fix for now just add the following podspec for RNGesureHandler to `ios/Podfile`

```
pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
```

Then in the `ios` directory run `pod install` to install it.

**Comment by Harsh2402** [comment]
@hellotoby 
Thanks, it works for me.

**Comment by keithj0nes** [comment]
@hellotoby 

After about 2 hours of trying to figure this out, this worked. Insane that this seems to be a huge problem for everyone.

**Comment by hallowcard13** [comment]
HI @hellotoby i followed your fix but still i'm still having same error

```
TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

My depedencies

"@react-native-community/masked-view": "^0.1.10",
"@react-native-community/toolbar-android": "0.1.0-rc.2",
"@react-native-firebase/app": "^8.2.0",
"@react-native-firebase/auth": "^8.2.0",
"@react-navigation/native": "^5.7.2",
"@react-navigation/stack": "^5.8.0",
"react": "16.13.1",
"react-native": "0.63.1",
"react-native-gesture-handler": "^1.7.0",
"react-native-reanimated": "^1.10.1",
"react-native-safe-area-context": "^3.1.1",
"react-native-screens": "^2.9.0"

i followed the installation here https://reactnative.dev/docs/navigation 

Can you please help me ?

**Comment by alexlabrioche** [comment]
Hello same problem here 

`    "@react-native-community/masked-view": "^0.1.10",
    "react": "^16.13.1",
    "react-native": "^0.63.2",
    "react-native-calendar-events": "^1.6.4",
    "react-native-check-version": "^1.0.4",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.5.4",
    "react-native-fbsdk": "^1.1.2",
    "react-native-firebase": "^5.4.0",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-router-flux": "4.2.0",
`

But only on **Android build**

**Comment by jakub-gonet** [comment]
Duplicate of #494.

**Comment by Sayyamabbasi786** [comment]
Finally solved the problem for android
-react-native link react-native-gesture-handler
-react-native link react-native-safe-area-context 
-build from android 
- npx react-native run-android
Enjoy!!!!

**Comment by mohammadribhee** [comment]
THX man it's work like charm @Sayyamabbasi786
