### ISSUE TITLE
How to open DrawerLayout component from button?

### ISSUE THREAD

**Issue by henrikra** [kmagiera/react-native-gesture-handler#68]
I can't find any function etc in DrawerLayout that I could open it with. For example if I wan't to have hamburger menu button which opens the drawer for me. Tell me if more info is needed :) Dragging works fine but having button for opening would be nice too

**Comment by kmagiera** [comment]
Have you tried calling this method:
```
https://github.com/kmagiera/react-native-gesture-handler/blob/master/DrawerLayout.js#L292
```
Sorry its not documented anywhere. Mainly wanted to match "official" drawerlayout API that has this command.

You need to get a ref to the drawer first in order to call the method. LMK if you need further assistance

**Comment by jadamduff** [comment]
Is there any update on this? I see the openDrawer function in the docs, but I'm getting an error saying "openDrawer is not a function"

**Comment by jadamduff** [comment]
Nevermind I figured it out!

**Comment by cyborgium** [comment]
> Nevermind I figured it out!

Could you let me know what you did?

**Comment by ferdicus** [comment]
@cyborgium, you have to save a `ref` to the DrawerLayout and then call the `openDrawer` method on that. Something like this:

```
drawer = null;

<DrawerLayout
  ref={ drawer => this.drawer = drawer }
  drawerWidth={200}
  drawerPosition={DrawerLayout.positions.Right}
  drawerType='front'
  drawerBackgroundColor="#ddd"
  renderNavigationView={this.renderDrawer}>
  <View>
    <Text>
      Hello, it's me
    </Text>
  </View>
</DrawerLayout>

```
