### ISSUE TITLE
DrawerLayout component with absolute positioned children

### ISSUE THREAD

**Issue by henrikra** [kmagiera/react-native-gesture-handler#69]
Looks like that dark overlay that DrawerLayout is creating on top of the screen's content on drawert drag is not on top of absolutely positioned elements 🤔

**Comment by henrikra** [comment]
Also if you try with `drawerType="front"` and absolutely positioned screen elements you get in weird situtations :D

**Comment by henrikra** [comment]
Ahaa I got it! It was because my elements had `elevation` set (shadow on Android) it also raised zindex. So adding `elevation` to overlay helps: https://github.com/kmagiera/react-native-gesture-handler/blob/master/DrawerLayout.js#L457 I just added `elevation: 1000` similar to zIndex

**Comment by kmagiera** [comment]
Thanks for investigating. Would you mind sending a PR with this change?

**Comment by osdnk** [comment]
@henrikra 
I suppose the problem has been solved. If you still face the issue, let us know
