### ISSUE TITLE
null is not an object ( evaluating '_RNGestureHandlerModule.default.createGestureHandler)

### ISSUE THREAD

**Issue by darsodango** [kmagiera/react-native-gesture-handler#691]
Has anyone encountered this error? Btw, I'm using `react-navigation` with version `3.11.0` and `react-native-gesture-handler` version `1.3.0`

**Comment by hieuluis96** [comment]
are you using iOS ? you need "pod install" on ios folder before running app.

**Comment by darsodango** [comment]
@hieuluis96 my bad, I'm using Android.

**Comment by stenlyadam** [comment]
I have same problem, fix in ios but still error in android. Any solutions? thanks

**Comment by nttrungqnh** [comment]
same my problem, anyone can help?

**Comment by wqzwh** [comment]
The same problem with me

**Comment by wqzwh** [comment]
vim ios/Podfile

add line code

```
pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
```
run pod install

react-native run-ios

you can solve the problem

**Comment by darsodango** [comment]
For iOs, there's no problem so far. But in Android, we're getting the error that I mentioned.

**Comment by stenlyadam** [comment]
Solved by follow this tutorial 
https://youtu.be/NcQhDlC7hT8

**Comment by darsodango** [comment]
I've fixed this particular error on my end. I'm not sure if this would solve the problem for the others. So here's what I did. Btw, my `react-native` version is `0.60.0`

**Steps**

make sure you have the following in your `android/app/src/main/java/com/yourApp/MainApplication.java`

add `import com.facebook.react.PackageList;`

**remove** `import com.facebook.react.shell.MainReactPackage;` (_if you have still this on your_ `MainApplication.java` _file_)

**remove** `import java.util.Arrays;` (_if you have still this on your_ `MainApplication.java` _file_)

**replace** this
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
);
```
with **this**
```
@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
}
```
**_Note:_** in `react-native` `0.60.0` the linking of dependencies is already automated so you don't need to link the `react-native-gesture-handler`

add an `"postinstall": "npx jetify"` on your `scripts` section

install `npm i --save-dev jetifier`

_**Note:**_ I added first the `"postinstall: npx jetify"` before installing the `react-native-gesture-handler` because any time your dependencies update the `jetifier` runs again.

install `npm i react-native-gesture-handler`

then run `react-native run-android`

And I think that's it. :grin:
