### ISSUE TITLE
REACT-NATIVE  automatic linking 

### ISSUE THREAD

**Issue by ramanasak** [kmagiera/react-native-gesture-handler#696]
I am using react-navigation for my react-native app , as docs said to use these commanads 
npm install react-native-gesture-handler
npm install react-navigation 

as my react-nnative version is 0.60.3 it said it will link automatically 
i was getting error like this after build 
![image](https://user-images.githubusercontent.com/24754280/61511618-ed5eed80-aa14-11e9-990f-2194292dfaa3.png)

then i used these commands 

react-native install --save react-native-gesture-handler
react-native link  react-native-gesture-handler.

after build it said error like " react-native 0.60.3 uses autolinking u have linkled  react-native-gesture-handler manually ".
then i have unlinked it using below command as it suggested .

react-native unlink react-native-gesture-handler

now ....
after build it is working ... . react-navigation is working  after linking and unnlinking ..
?

**Comment by oscar-gallog** [comment]
This is horrible, I have the same problem and if this library doesn't work, react-navigation doesn't work either. I can't fix it at all.

**Comment by recursiveKirs** [comment]
A workaround is to link the libraries manually.

In Xcode just go to libraries > add files to "Project Name"
<img width="360" alt="Screen Shot 2019-07-23 at 7 36 03 PM" src="https://user-images.githubusercontent.com/19338303/61754450-431ef700-ad81-11e9-829f-3e80e69b10c5.png">

and navigate to Project Name > Node Modules > react-native-gesture-handler > ios > RNGestureHandler.xcodeproj and hit ADD

Then go to Build Phases > Link Binary with Libraries and hit the PLUS and search for libRNGestureHandler.a and add that.

This should do that trick until auto-linking.

**Comment by smeekmeister** [comment]
for auto linking iOS you need extra step
cd ios
pod install
this installs the pod for Gesture handler.

**Comment by MANTENN** [comment]
> for auto linking iOS you need extra step
> cd ios
> pod install
> this installs the pod for Gesture handler.

I still get the same error. A temporary work around is to run: `react-native link react-native-gesture-handler`

**Comment by MANTENN** [comment]
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#what-do-i-need-to-have-in-my-package-to-make-it-work

In order for it to be compatible with autolinking, the podspec file needs to be moved to the root. I am not sure how this will affect older versions of react.

**Comment by rodrigowpl** [comment]
@smeekmeister I've tried that and having the same issue

RN Version: 0.60.4
react-native-gesture-handler: 1.3.0

basically, we already need link manually, right?

**Comment by smeekmeister** [comment]
you need to remove the Gesture handler Xcode project from your project en do via cocoa pods.

**Comment by MANTENN** [comment]
> @smeekmeister I've tried that and having the same issue
> 
> RN Version: 0.60.4
> react-native-gesture-handler: 1.3.0
> 
> and run pod install again
> 
> basically, we already need link manually, right?

add it to your `Podfile` and run `cd ios && pod install`

**Comment by smeekmeister** [comment]
Maybe clean your project and start over again. I am using over 20 libraries all via cocoapods. My pod file has the standard react entries as per documentation in rn diff purge so React, React-Core, etc until Follly, then all the firebase ones, the FBSDK ones, GoogleSignIn and lottie-ios. If I run pod install all pods are installed including the ones from package json, eg.  react-native-reanimated, rnc’s etc ... and also react-native-gesture-handler

**Comment by tapz** [comment]
When is autolinking going to be supported? Currently I get either the RN autolink error or does-not-found error.
