### ISSUE TITLE
TouchableWithoutFeedback onPress, onPressIn, onPressOut don't fire on Android inside of a RN 0.59.10 Modal

### ISSUE THREAD

**Issue by EmperorEarth** [kmagiera/react-native-gesture-handler#731]
TouchableWithoutFeedback `onPress`, `onPressIn`, `onPressOut` handlers don't fire inside React Native 0.59.10's [`<Modal>`](https://facebook.github.io/react-native/docs/0.59/modal)

Issue
* Android on Windows 7x64

Fine
* iOS on macOS 10.15

**Comment by hsource** [comment]
This is a long-running issue and a duplicate of #332, #139

Workarounds include:

1. Using another modal component that does mount to the root view (for example, creating a modal screen using `react-navigation`
2. Using normal Touchables when inside a modal (fine if you don't use it very much)

**Comment by EmperorEarth** [comment]
closed as probable duplicate of #139
