### ISSUE TITLE
Problem using 2 PanGestureHandler simultaneously

### ISSUE THREAD

**Issue by oktapodia** [kmagiera/react-native-gesture-handler#733]
Hello,

I'm currently trying to build a react-native app which is simulating a trackpad.

I should be able to click on a button, move above and then, release the button (or everything).

Everything is working like a charm on Android, but only the parent `PanGesture` (Move area) is working on IOS, no action triggered when touching the buttons.

Any ideas?

Regards

**Comment by dsznajder** [comment]
@oktapodia Could you share some example how you actually build it? I've created something similar to keep track & touch on both platforms, so maybe I could help you with that :)

**Comment by oktapodia** [comment]
Thank you for your reply @dsznajder, I think I found the issue, android is starting the event on the touchdown even if we don't move our finger, ios need the finger to move for a minimum distance.

Even if I am setting up these options

```
              <PanGestureHandler
                minDist={0}
                minDeltaX={0}
                minDeltaY={0}
/>
```

Any ideas?

**Comment by Ashkan-Oliaie** [comment]
@oktapodia Have you tried TapGestureHandler ?
I'm not sure about your issue though.

**Comment by oktapodia** [comment]
I can't use TapGestureHandler because I have to handle press and longPress at the same time

**Comment by dsznajder** [comment]
@oktapodia I've build something similar with LongPressGestureHandler + TapGestureHandler. You don't really need PanGestureHandler as `onGestureEvent` can stream you position too :)

**Comment by oktapodia** [comment]
Working with the LongpressGestureHandler, thank you for your help! @dsznajder I need the PanGestureHandler to get the velocity as well
