### ISSUE TITLE
Max / Min scale for pinch

### ISSUE THREAD

**Issue by jhalborg** [kmagiera/react-native-gesture-handler#74]
A prop for max/min scale relative to initial scale would be awesome!

**Comment by kmagiera** [comment]
Would you be able to provide more details on that? Do you want the scaling to stop at a certain scale level or have a min distance between fingers at which the pinch recognizer would activate?

If the former is your choice you can achieve that by using Animated.interpolate:
```
valueBoundToHandler = new Animated.Value(1);
valueUsedInStyles = valueBoundToHandler.interpolate({
  inputRange: [0.5, 1.5],
  outputRange: [0.5, 1.5],
  extrapolate: 'clamp'
});
```
Don't try to run this code as I haven't tested it, just made it to mark my idea. The value that you should use in transform (`valueUsedInStyles`) is going to be clamped at 0.5 and 1.5

**Comment by jhalborg** [comment]
The former, and of course - had forgotten about interpolation. I'm sorry, I'm still a bit new to the Animated API. 

Thanks 😁
