### ISSUE TITLE
React-Native 0.61.0-rc.0 - Touchable* & *Button does not trigger `onPress` event.

### ISSUE THREAD

**Issue by dsznajder** [kmagiera/react-native-gesture-handler#745]
Hi, 

With newest RC version, `onPress` event is not triggered. I'm not sure yet with GestureHandlers but I will create repro example with both 60.x & 61.x.

**Comment by drewhamlett** [comment]
I'm seeing this with just Android.  iOS still seems to be working.

**Comment by immortalx** [comment]
Just to confirm, upgraded to the latest rn 0.61.0-rc.2 and onPress is not triggered in Android.
iOS works fine.

**Comment by JonnyBurger** [comment]
With 0.61.0-rc.2 also all the components relying on PanGestureHandler don't seem to work. Native Swipeable and `react-native-modalize` don't accept any swipe gestures anymore.

**Comment by rafaelmotta** [comment]
I don't know why, but in my simulator, I don't get any issue, but in production I get. My problem was also in the library react-native-modalize, which uses react-native-gesture-handler under the hood.

This is the issue I got in sentry:
Unsupported top level event type "onGestureHandlerStateChange" dispatched

Ended reverting to 0.60.5

**Comment by jfrolich** [comment]
I found the code snipped in this issue #320 fixes the issue:

```js
for (let k in UIManager) {
  if (
    UIManager.hasOwnProperty(k) &&
    UIManager[k] &&
    UIManager[k].directEventTypes
  ) {
    UIManager[k].directEventTypes.onGestureHandlerEvent = {
      registrationName: 'onGestureHandlerEvent',
    }
    UIManager[k].directEventTypes.onGestureHandlerStateChange = {
      registrationName: 'onGestureHandlerStateChange',
    }
  }
}
```

**Comment by delold** [comment]
Using `gestureHandlerRootHOC` has worked for me instead: 

https://github.com/react-native-community/releases/issues/140#issuecomment-532819601

**Comment by jfrolich** [comment]
> Using `gestureHandlerRootHOC` has worked for me instead:
> 
> [react-native-community/releases#140 (comment)](https://github.com/react-native-community/releases/issues/140#issuecomment-532819601)

That didn't work for me. But that was 0.61-rc.0, didn't test after that.

**Comment by dsznajder** [comment]
@kmagiera I'm closing this as RNGH is working properly with RN 61.1.

Thanks 🙌 🙌 🙌

**Comment by lake2** [comment]
same issue on RN 61.2

**Comment by panda0603** [comment]
still seems not to be fixed in RN 0.61.5

**Comment by curiousdustin** [comment]
I have been able to reproduce this behavior in the current example app. 

https://github.com/software-mansion/react-native-gesture-handler/issues/920

**Comment by Artoering** [comment]
@panda0603  me too, after read the documentation follow that step still seems not to be fixed in RN 0.61.5

**Comment by avinashlng1080** [comment]
Any update on this ticket please?

**Comment by qayyummdnoor** [comment]
Yup, confirm android RN 0.61.5 PanGestureHandler not working, any update or workaround?

**Comment by avinashlng1080** [comment]
Can anyone please point us to a solution ?

**Comment by avinashlng1080** [comment]
I was having the same issue and then by removing the useScreen() function from react-navigation, all the touches on Android went through.  It might be helpful to note it.

**Comment by qayyummdnoor** [comment]
I found a workaround, replace componentDidUpdate() to UNSAFE_componentWillUpdate(), working on RN 0.61.5.

**Comment by todorone** [comment]
@dsznajder This issue can be reproduced with the latest RN version, could You please reopen the issue?

**Comment by saczuac** [comment]
Same issue here

**Comment by callaars** [comment]
For me, the problem was solved by using the `Touchable*` from the `react-native-gesture-handler` package instead of the ones from `react-native`. On RN 0.63 it also doesn't work with the new `Pressable` component.

**Comment by jfrolich** [comment]
I found that this happens after opening a modal. All touchables or gestures stop working. When you remove flipper from the app the problem is gone. So it's probably a new bug in flipper.
