### ISSUE TITLE
PanGestureHandler nativeEvent.state never ENDs

### ISSUE THREAD

**Issue by quizzy** [kmagiera/react-native-gesture-handler#747]
version: `react-native-gesture-handler: 1.4.1`

Hi,

The `PanGestureHandler` doesn't seem to fire an `END` state when the touch is lifted.
I wasn't sure if this was expected behaviour at first, as it's not covered in the documentation, but I see it being referenced in the [react-native-reanimated example](https://github.com/kmagiera/react-native-reanimated/blob/master/Example/PanRotateAndZoom/index.js#L31) which uses the `PanGestureHandler`.

Below is some sample code for how I'm using the `PanGestureHandler` (along side `reanimated`). All I'm doing in this sample code is just logging out the `nativeEvent.state`s.
The `State.END` condition never returns true.

Am I doing something wrong?

```JS
export const DraggableItem = () => {
  const yPos = new Value(0);

  const handleGestureEvent = event([
    {
      nativeEvent: ({ state, translationY }) =>
        block([
          cond(
            debug('state active', eq(state, State.ACTIVE)),
            set(yPos, translationY),
          ),
          cond(
            debug('state end', eq(state, State.END)),
            set(yPos, translationY),
          ),
        ]),
    },
  ]);

  return (
    <Wrapper>
      <PanGestureHandler onGestureEvent={handleGestureEvent}>
        <Box
          style={[
            {
              transform: [
                {
                  translateY: yPos,
                },
              ],
            },
          ]}
        />
      </PanGestureHandler>
    </Wrapper>
  );
};
```

**Comment by quizzy** [comment]
Sorry - I just realised it's because I didn't include the `onHandlerStateChange` prop for the `PanGestureHandler`... 🤦‍♂

**Comment by euroclydon37** [comment]
Not an uncommon error. Thanks for coming back to comment. It helped me.

**Comment by rafeautie** [comment]
@quizzy Can you please post an example of how you fixed this? I am passing the `onHandlerStateChange` pro but the `event()` condition is still never seeing the END state.
