### ISSUE TITLE
Android: Scale when pinching cannot go under 1

### ISSUE THREAD

**Issue by jhalborg** [kmagiera/react-native-gesture-handler#75]
Hello, 

Testing the code from the example, scaleAndRotate, the image is not scalable below 1 on Android, but it works fine on iOS - why is that? And is there any way to change this behavior?

**Comment by kmagiera** [comment]
Hey @jhalborg. Sorry for getting here so late, completely missed this issue.

Can you maybe provide some videos/gifs on what exactly is happening on Android vs iOS. This would make it a lot easier for me to make sure I know what you are asking about and would help me investigate.

**Comment by jhalborg** [comment]
Hey :) No worries. As evident from #73 , I haven't had time to get back into it for a while. Other tasks on the project has had higher priority, and then there was christmas, of course. I expect this part of the project will be a priority again in the beginning of February.

I mostly test on devices, so it's a bit cumbersome to set up a gif of it, but the problem is fairly simple to explain. 

Let's say the "base" image is 3x3 cm in size on the screen when the example is rendered. When I pinch-to-zoom on the image, it behaves differently on Android than on iOS:

**iOS**: The image scales as expected, both up and down in size. 
**Android**: The image scales as expected up in size, but _cannot_ scale below the original size. 

As a user, I would expect to be able to make the image smaller than the initial size _as well_ as larger. 

If you're still in doubt, please let me know, then I'll figure out a way to make a gif of the issue :-)

**Comment by osdnk** [comment]
@jhalborg 
I'm extremely sorry that we haven't minded this issue before.
I wish you take a look on our Example app and its "scale, rotate and tilt". I've just checked on Android phone and everything seems to work fine. 
If you still face the problem, please prepare some sample app or gif.

**Comment by osdnk** [comment]
@jhalborg 
This issue seems yo be inactive
If you still face the problem,  reopen the issue
