### ISSUE TITLE
Stopped working completely after upgrading react-native from 0.60.5 to 0.61.0

### ISSUE THREAD

**Issue by almeida-samuel** [kmagiera/react-native-gesture-handler#772]
Someone is having issues with react-native-gesture-handler@1.4.1? Isn't working at all after upgrading to 0.61 from 0.60.5. Both emulator and real devices. I tested twice and seems to be due to the react-native version bump. Someone can confirm?

**Comment by yogeshkotadiya** [comment]
Yes, I can confirm react-native-gesture-handler is not working on RN0.61

**Comment by dekameron22** [comment]
+1

**Comment by piuholo** [comment]
If I read the discussion correctly, it seems that there is no fix for RN 0.61 in projects built with `react-native-navigation` where there is no root component to wrap with `gestureHandlerRootHOC`.
I assume we have to wait for later RN release?

**Comment by dekameron22** [comment]
sry, my issue was related to Reactotron, which logged an event each time screen changes without checking if its a debug mode.
looked solution here as one of the latest stack traces was TouchRemove

**Comment by almeida-samuel** [comment]
Thanks @yogeshkotadiya @dekameron22 and @piuholo . I'm going to left this issue open for other to see.

**Comment by piuholo** [comment]
@kmagiera The `react-native` release 0.61.1 notes claim that it would fix the issue with `react-native-gesture-handler`. However, the latest release seems to have the same the exact same critical issue as the previous one.

Is there any information on upcoming / unreleased fixes?

**Comment by kmagiera** [comment]
I believe you are talking about Android and issues on 0.61.0 – There is already a patch updated done on the react native core side to fix this problem in 0.61.1 – please upgrade RN version and you should be good.

I'm going to close this issue. If it is a different setup that you see the problems with (not Android with 0.61) please open a new issue and specify the details of your setup.

**Comment by waqaramjad** [comment]
react-native gesture not working properly in   "react-native": "0.61.2",
