### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#78]
Currently this is the only package in my dependencies that doesn't have type definitions.
EDIT: Now this and react-native-navigation

Tried to use https://github.com/Microsoft/dts-gen but it doesn't support es6 modules (Microsoft/dts-gen#42) which this repo uses.

I'm new to Typescript so I'll not jump into a PR right away.

**Comment by kmagiera** [comment]
cc @krzysztofciombor who was interested in working on providing TS definitions

**Comment by kmagiera** [comment]
Closing as per https://github.com/kmagiera/react-native-gesture-handler/pull/86
