### ISSUE TITLE
cannot read property 'direction' of undefined / IOS / React Native

### ISSUE THREAD

**Issue by zeinMch** [kmagiera/react-native-gesture-handler#789]
After I update XCode to version 11.1 my project couldn't run on IOS I tried to follow a lot of solution (#671 #686 #497)  but I still have the same problem

![Screen Shot 2019-10-11 at 4 57 01 PM](https://user-images.githubusercontent.com/39551878/66706992-10f2b500-ed32-11e9-9e42-0cdef0b10789.png)

Here is my dependencies :

"dependencies": {
    "EventEmitter": "^1.0.0",
    "axios": "^0.19.0",
    "babel-core": "^6.26.3",
    "fbjs": "^1.0.0",
    "gradle": "^1.0.9",
    "i": "^0.3.6",
    "i18next": "^17.2.0",
    "jetifier": "^1.6.4",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "path": "^0.12.7",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-i18next": "^10.13.1",
    "react-native": "0.61.2",
    "react-native-elements": "^1.2.6",
    "react-native-fabric": "^0.5.2",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-hide-show-password-input": "^1.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-locale-detector": "^1.0.1",
    "react-native-material-tabs": "^4.1.2",
    "react-native-navigation": "^2.27.9",
    "react-native-orientation": "^3.1.3",
    "react-native-paper": "^2.16.0",
    "react-native-pdf": "^5.1.6",
    "react-native-reanimated": "^1.3.0",
    "react-native-screens": "^2.0.0-alpha.4",
    "react-native-snap-carousel": "^3.8.2",
    "react-native-splash-screen": "^3.2.0",
    "react-native-timeago": "^0.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-view-more-text": "^2.1.0",
    "react-native-xml2js": "^1.0.3",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.4",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-form": "^8.2.6",
    "regenerator-runtime": "^0.13.3",
    "rn-fetch-blob": "^0.11.2",
    "start": "^5.1.0",
    "yarn": "^1.19.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/preset-env": "^7.6.3",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/eslint-config": "0.0.5",
    "@types/enzyme": "^3.10.3",
    "babel-jest": "^24.9.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.15.1",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "jest-fetch-mock": "^2.1.2",
    "jest-mock-axios": "^3.1.1",
    "metro-react-native-babel-preset": "^0.56.0",
    "mocha": "^6.2.1",
    "react-devtools-core": "^4.2.0",
    "react-dom": "^16.10.2",
    "react-native-dotenv": "^0.2.0",
    "react-test-renderer": "^16.9.0",
    "ts-jest": "^24.1.0"
  },

**Comment by lonnylot** [comment]
@zeinMch Did you find a solution to this?

**Comment by zeinMch** [comment]
@lonnylot yes I did 
1- delete Pods file from /ios 
2-run : pod install 
it will works, if not you have to open your project with XCode (/ios/App.xcworkspace) then go to 
Product ->Scheme -> Manage Scheme then check react 

![Screen Shot 2019-12-02 at 11 52 41 AM](https://user-images.githubusercontent.com/39551878/69953866-6e1d1280-14fa-11ea-921a-93aac6a4a217.png)

**Comment by jakub-gonet** [comment]
Duplicate of #494.

(just linking related issues, don't mind me 😄)
