### ISSUE TITLE
Warning: Module RNGestureHandlerModule requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#79]
> Module RNGestureHandlerModule requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/619186/33955687-8e029b14-e023-11e7-9ffc-9fbdf5dcbc48.png">

---

"react-native": "^0.51.0",
"react-native-gesture-handler": "^1.0.0-alpha.35",

**Comment by kmagiera** [comment]
Great stuff @brunolemos. Thanks for the heads up, I'll def look into this soon. Do you know what the next release is planned for?
