### ISSUE TITLE
RN v0.61.2 cause RectButton to crash the whole app without any stack trace

### ISSUE THREAD

**Issue by muhaimincs** [kmagiera/react-native-gesture-handler#798]
In development mode it's working fine as it should but this occur when I'm running `react-native run-android --variant=release`.

I haven't test the temp workaround (`gestureHandlerRootHOC`) but I believe this is critical

**Comment by filippoitaliano** [comment]
Same issue here. I use this module in conjunction with react-navigation-drawer. In dev mode my menu works as expected. In release mode each drawer interaction results in app crash. Before upgrading to RN 0.61.2 the menu worked fine.

**Comment by SylvioMigliorucci** [comment]
I added

`import 'react-native-gesture-handler'`

at top of index.js file as suggested in #320 and it works now ￼

**Comment by muhaimincs** [comment]
it's like a magic
