### ISSUE TITLE
[Question] Disable Ripple/Bubble Feedback on iOS

### ISSUE THREAD

**Issue by tolu360** [kmagiera/react-native-gesture-handler#80]
First off, thank you for sharing your work. This is by way of a question and not an issue. I was wondering if the `ripple/bubble feedback on IOS` was, somewhat, configurable? I would like to know how I can totally turn it off on my project please.

Thanks.

**Comment by kmagiera** [comment]
Hey @tolu360 thanks for reaching out. I'm not sure though if I understand you issue correctly. Are you talking about Button components? Ripple effect should not be displayed on iOS but only on Android as that is the native way in which clickable elements would respond to actions.

**Comment by tolu360** [comment]
Hi @kmagiera, I'm glad you replied, thanks. I was playing around with the sample app and I'm referring to this feedback for touches anywhere on the screen. Please see screenshots below - that bubble of some sort:

![gesture buble 3x](https://user-images.githubusercontent.com/3914854/34042977-4e4d30a6-e19f-11e7-9719-5582a659319f.png)

**Comment by zachgibson** [comment]
@tolu360 Example/ios/MBFingerTipWindow.m is where this is implemented.

**Comment by tolu360** [comment]
Thanks @zachgibson, you are right.

**Comment by kmagiera** [comment]
Thanks @zachgibson for answering!

I'm closing this issue as it seems to be resolved for you @tolu360 In case you want to discuss further please go ahead and re-open it
