### ISSUE TITLE
[Swipeable] Not working on older iOS versions

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#81]
Tried the `Swipeable` component on iOS 8.1 and it throws this exception:

[Swipeable.js:195:40](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js#L195) `undefined is not a function (evaluating 'Math.sign(toValue)')` 
Fix: #82

On iOS 9.0 the swipe gesture works but it doesn't show the buttons.

**Comment by kmagiera** [comment]
Not sure why github didn't close this automatically. Anyways, closing it now, thanks @brunolemos again for your fix!

**Comment by brunolemos** [comment]
@kmagiera it's because I only fixed the crash, but the swipeable buttons still doesn't show up on older ios versions. Please reopen :)

**Comment by pfyod** [comment]
@kmagiera still shows weird artifacts instead of buttons on older iOS versions (at least 9.3.5).
