### ISSUE TITLE
dragging makes app crash

### ISSUE THREAD

**Issue by pouyaalikhanzade** [kmagiera/react-native-gesture-handler#836]
hi i'm having an issue with my sidebar dragging using react-native-gesture-handler it works perfectly in debug version but the app crashes when u do it on apk release or even if it sidebar appears it would crash if u press where ever in app except the back button of android.

i m using  "react-native-gesture-handler": "^1.5.0",
    "react-native": "0.61.2",
    "react-navigation-drawer": "^2.2.2",

**Comment by RomanISWG** [comment]
Same problem here. The apps is crashing even on touch of the left side area for dragging the drawer. And only on Android in release mode.

**Comment by MrSucik** [comment]
Same issue here, we don't use drawer, but the app crashes when I touch PanGestureHandler.
with error
    "react-navigation": "4.0.10",
    "react-navigation-stack": "1.10.3",
    "react-navigation-tabs": "2.5.6",
    "react-native-reanimated": "1.4.0",
    "react-native-gesture-handler": "1.5.0",
Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched

**Comment by RomanISWG** [comment]
The workaround for this is to put this import as the first thing in the index.js 
`import 'react-native-gesture-handler'`

**Comment by pouyaalikhanzade** [comment]
@RomanISWG that worked for me as well tnx

**Comment by MrSucik** [comment]
@RomanISWG above solution does not work for me
