### ISSUE TITLE
Listener available for PanGestureHandler?

### ISSUE THREAD

**Issue by zachgibson** [kmagiera/react-native-gesture-handler#91]
Is it possible to get the value of a PanGestureHandler x/y? I’m working on a Slider component and I need the value as it’s being dragged.

**Comment by zachgibson** [comment]
This IS possible! It’s just an `Animated.event()` which accepts an object as the second arg which contains an async listener. If anyone is interested and not sure what I mean it looks like:

```JSX
this._onGestureEvent = Animated.event(
  [
    {
      nativeEvent: {
        translationX: this._translateX,
      },
    },
  ],
  {
    useNativeDriver: true,
    listener: e => {
      this.setState({ x: Math.floor(e.nativeEvent.translationX) });
    },
  },
);
```

**Comment by kmagiera** [comment]
@zachgibson you can also do sth like:
```
this._translateX.addListener(value => console.log("VALUE", value))
```
