### ISSUE TITLE
Question: Transferring an in progress gesture

### ISSUE THREAD

**Issue by nixterrimus** [kmagiera/react-native-gesture-handler#94]
Hello!

I'm working on a keypad that has multiples pages, buttons that press, buttons that long press and bring up a popover and popovers that you can pan between options.  Wheh!  Here's what I've got so far:

![gesture-in-progress](https://user-images.githubusercontent.com/18454/34627599-14a9cb3e-f216-11e7-983f-69c9b7d9f047.gif)

I think I need to transfer the long press gesture to the pan gesture so that I can select items in the submenu.  Is there any way to do this?  Things are kind of working by using `simultaneousHandlers` on the pan gesture handler but that eats up the paging gesture.  What I really want to say to the pan gesture handler- Wait until the long press is fired and then when the finger moves begin to recognize.

**Comment by nixterrimus** [comment]
Here's a link to the movie for slightly better fidelity: https://imgur.com/a/QE0Ht

**Comment by kmagiera** [comment]
Thanks @nixterrimus for reaching out.

I'm not sure I fully understand your usecase but let me try to answer regardless:

So I think what you may want to try is just having the LongPressHandler to implement button along with the submenu. You should be able to use `onHandlerStateChange` event to determine when long press occurs and show submenu and also have `onGestureEvent` callback registered to be able to get pointer (finger) position while long press is happening. Also you should set `shouldCancelWhenOutside={false}` as you don't want longpress handler to cancel when you swipe away from the button while panning over the submenu. Please note that you will be getting raw gesture events (via `onGestureEvent` callback) only when the state of the handler is ACTIVE.
