### ISSUE TITLE
'react-native-router-flux': cannot get it to work

### ISSUE THREAD

**Issue by afilp** [kmagiera/react-native-gesture-handler#95]
Hi!

I cannot get this to work with the 'react-native-router-flux'. 

I added the  HOC on each "scene" but it seems that this works only for the 1st scene? Not for the second pushed scene? Not sure how this could work. I just want to wrap the entire application with a TapHandler so that I can detect the inactivity state.

Is this supported somehow?

Thanks!

**Comment by kmagiera** [comment]
Thanks @afilp for reaching out.

react-native-router-flux is not considered to be a **native** navigation library in a sense that it does not include any native code (just JS code). Therefore you shouldn't need to use the HOC. Just follow the installation instructions form the main README https://github.com/kmagiera/react-native-gesture-handler/blob/master/README.md#installation and you should be good to go.

I'm going to close this issue but feel free to reopen if the above doesn't solve your issue.
