### ISSUE TITLE
pictures in readme

### ISSUE THREAD

**Issue by fxfactorial** [kmagiera/react-native-gesture-handler#98]
Hi, I think it would help a lot to have pictures in the README of the various components provided.

**Comment by kmagiera** [comment]
Thanks for the suggestion @fxfactorial – I'll take a note on that as we are revamping docs at the moment. I'm going to close this issue for the time being, hope you will like new docs page we are preparing at the moment and should be available in the near future

**Comment by brighthero** [comment]
@kmagiera Any eta on the new docs? I'm really struggling to understand the basics of this project seemingly because of the lack of proper documentation etc.
