### ISSUE TITLE
3-Finger PanGestureHandler Not Working on Android

### ISSUE THREAD

**Issue by jcady** [kmagiera/react-native-gesture-handler#99]
I have a `PanGestureHandler` configured in the following way:

```
<PanGestureHandler
  minOffsetY={200}
  minPointers={3}
  maxPointers={3}
  avgTouches={true}
  onActivated={onGestureRecognized}
>
  {...}
</PanGestureHandler>
```

The idea is to create a three-finger swipe up gesture (like mission control on MacOS). This gesture works great on iOS, but not on Android.

Looking at the state of the gesture handler, it fails almost immediately after starting. Debugging the native code, it looks like the offending line is [this](https://github.com/kmagiera/react-native-gesture-handler/blob/master/android/lib/src/main/java/com/swmansion/gesturehandler/PanGestureHandler.java#L277). The gesture is failing because at some point `event.getPointerCount()` is returning 2 pointers (despite three being present). I'm not exactly sure why this is, but my guess is this is due to there being no "debouncing" of the touch events. Because it's virtually impossible to touch all three fingers to the screen at the exact same time, the gesture will fail when it detects 2 fingers.

`avgTouches` doesn't seem to make a difference, it will fail the same regardless of its presence. Reducing the min and max pointers to 2 makes the gesture work great with 2 fingers. I would do the detection manually by examining the `nativeEvent` of the `onGestureEvent` callback, but that doesn't seem to report number of touches, making it impossible to know if the gesture is being correctly executed.

**Comment by kmagiera** [comment]
hey @jcady ! thanks for reporting and investigating this issue. You are right that we should not be comparing against mMinPointers in that place until handler is in ACTIVE state. It is happening because POINTER_DOWN events will never arrive at the same time. I should have a fix for this really soon

**Comment by jcady** [comment]
Thanks for the quick fix @kmagiera!
